### ISSUE TITLE
XCTest/XCTest.h file not found

### ISSUE THREAD

**Issue by kamoljan** [adjust/ios_sdk#107]
Hi guys

We are using latest Swift 1.2 with latest xCode 6.3.1.
In our bridging header file:

    // Adjust
    #import <XCTest/XCTest.h>
    #import "Adjust.h"

Our Podfile:

      pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.2.3'

Any bug?

**Comment by semvox** [comment]
We are still facing that issue. We tested with XCode 3.6.1 and 3.6.2. We also added $(PLATFORM_DIR)/Developer/Library/Frameworks to the framework search paths since we found that as a common solution on stackoverflow. But it is still not working.
