### ISSUE TITLE
Adjust doesn't work with iOS 9, when app transport security is enabled

### ISSUE THREAD

**Issue by bashery** [adjust/ios_sdk#118]
The console is filled with logs like this:
[Adjust]e: Failed to track session. (An SSL error has occurred and a secure connection to the server cannot be made.) Will retry later.

See Apple's technical note about App Transport Security for help fixing this: https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

**Comment by bashery** [comment]
Looks like app.adjust.com is using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA for its ciper, which is not on the white list for App Transport Security

**Comment by uerceg** [comment]
@bashery Thank you for this info, we'll take a look at it and let you know as soon as there's an update on our side.

**Comment by roa** [comment]
@bashery thank you for bringing this to my attention. we are working on that problem. as we need to do some testing to guarantee downward compatibility this could take some time. but we will fix this asap.

**Comment by bashery** [comment]
@roa @uerceg no problem!

**Comment by roa** [comment]
Hello @bashery ,

right now this is what we support of the mentioned ciphersuites with TLS 1.2

```
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384    ECDHE-RSA-AES256-GCM-SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256    ECDHE-RSA-AES128-GCM-SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384    ECDHE-RSA-AES256-SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256    ECDHE-RSA-AES128-SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA       ECDHE-RSA-AES128-SHA
```
I included the openssl formatted name so you can check that they are working with:

```
openssl s_client -cipher $CIPHER -tls1_2 -connect app.adjust.io:443 -debug
```

e.g.

```
openssl s_client -cipher ECDHE-RSA-AES128-SHA -tls1_2 -connect app.adjust.io:443 -debug
```

We are not enforcing these ciphers though. Does that fix your issue?

**Comment by roa** [comment]
I just realized, that we are still using SHA1 certificates, so i guess your issue is not fixed. I will update this as well.

**Comment by roa** [comment]
@bashery 

Okay, i also updated our certificates to have SHA2 signature hashes. Can you please test, if that fixes your issue? If not, can you somehow give me a self contained test? Thanks in advance!

**Comment by bashery** [comment]
@roa looks like it's fixed! Good call on the SHA2 certificates. I was just looking at the ciper suite that Firefox was preferring (as a quick test as to why the connection might be failing). Thanks for fixing this so quickly!

**Comment by roa** [comment]
You are very welcome. Thanks again for bringing this to our attention. I will close that issue now.
Have a nice weekend!

**Comment by bashery** [comment]
You too!
