### ISSUE TITLE
AdjustDelegate is retain

### ISSUE THREAD

**Issue by senryxie** [adjust/ios_sdk#122]
The code line 91 in ADJConfig.h
@property (nonatomic, retain) NSObject<AdjustDelegate> *delegate;

Although Normally Adjust will be implemented in AppDelegate which will never be released, it's still not a good code practice to use retain with delegate property.

**Comment by wellle** [comment]
For reference: [ADJConfig.h#L91](https://github.com/adjust/ios_sdk/blob/1ee63ff89bc421f828bacf7f5844b73b6e4fa6dc/Adjust/ADJConfig.h#L91)

**Comment by nonelse** [comment]
Thanks for catching that, we will change it for the next release

**Comment by uerceg** [comment]
Fixed in https://github.com/adjust/ios_sdk/pull/124.
