### ISSUE TITLE
4.2.9 breaks iOS 7 compatibility

### ISSUE THREAD

**Issue by strefethen** [adjust/ios_sdk#126]
Just FYI, we did a pod update today and found that 4.2.x is no longer compatible due to:

In ADJUtil.m
    dateFormat.calendar = [NSCalendar calendarWithIdentifier:NSGregorianCalendar];

We've manually locked our build back to v4.2.4 but we previously had "~> 4.2.4" in our podfile and we were allowing it to float so this was an unexpected breaking change.

**Comment by uerceg** [comment]
@strefethen Please update to v4.3.0 where we fixed this and which we released today and give it a try.

**Comment by uerceg** [comment]
@strefethen Did you test the update?

**Comment by strefethen** [comment]
@uerceg Not yet we're sticking on the build we have live (v4.2.0) for now. Is there a changelog available? I don't see one.

**Comment by uerceg** [comment]
@strefethen We recently had requirements for changelog feature and will introduce it as soon as we can. Regarding the calendar issue, it was already fixed in our `4.3.0` release, but is now definitely closed in https://github.com/adjust/ios_sdk/pull/131.
