### ISSUE TITLE
Crash with Adjust

### ISSUE THREAD

**Issue by senryxie** [adjust/ios_sdk#128]
![image](https://cloud.githubusercontent.com/assets/1171418/9989929/085d5604-605d-11e5-9f60-978d9d9dc9d5.png)
Please check the ScreenShot. No more detailed information about it.

**Comment by senryxie** [comment]
Another one here:
![image](https://cloud.githubusercontent.com/assets/1171418/9989974/7a132440-605d-11e5-9d17-8d316c8ee283.png)

**Comment by uerceg** [comment]
@senryxie Thank you for the report. Can you please tell me in which iOS SDK version did you encounter this issue?

**Comment by senryxie** [comment]
@uerceg I integrate the SDK on 26th August, so it should be v4.2.8.

**Comment by uerceg** [comment]
@senryxie Can you reproduce this issue while testing your app in sandbox environment?

**Comment by senryxie** [comment]
@uerceg Sorry I can not reproduce this in my sandbox environment.
The crash rate of these are not so high I think it is not easy to reproduce.

**Comment by nonelse** [comment]
@senryxie, just to clear out an hypothesis, are you using `[Adjust setEnabled:...]` anywhere in your code?

**Comment by senryxie** [comment]
@nonelse , no, I do not use any [Adjust setEnabled:] method in my project.

**Comment by uerceg** [comment]
@senryxie Any luck in reproducing this issue? We were testing and trying to reproduce it, but no luck at all.

**Comment by uerceg** [comment]
@senryxie Any news about this issue you had? Are you still seeing these crashes in your app? We didn't get this reported by anyone else and were unable to reproduce it.

**Comment by uerceg** [comment]
Please reopen if this is still an issue with the newest SDK version.
