### ISSUE TITLE
CocoaPods trunk

### ISSUE THREAD

**Issue by x2on** [adjust/ios_sdk#133]
Could you please provide the 4.4.0 to CocoaPods trunk repository.

Actually also there are warnings in the new release, `stringByAddingPercentEncodingWithAllowedCharacters` is deprecated.

**Comment by nonelse** [comment]
Hey, sorry you are right, we forgot to release it in cocoapods.
The `stringByAddingPercentEncodingWithAllowedCharacters` is actually only being used the `Criteo` plugin, so if you are not using that in tvOs it should be fine.
We'll make a release soon with that update and pushed to cocoapods.
Thanks

**Comment by x2on** [comment]
Hi @nonelse ,

we are using that plugin.

best,

Felix

**Comment by nonelse** [comment]
Just pushed v4.4.1 to cocoapods, it should be there soon!
Thanks for the warning
