### ISSUE TITLE
Adjust SDK is still logging despite logLevel = ADJLogLevelAssert

### ISSUE THREAD

**Issue by arielelkin** [adjust/ios_sdk#136]
I'm setting up Adjust thus:

    let adjustConfig = ADJConfig(appToken: "myToken", environment: ADJEnvironmentSandbox)
    adjustConfig.logLevel = ADJLogLevelAssert
    Adjust.appDidLaunch(adjustConfig)

And this gets logged to the console: 

```
2015-11-02 12:13:49.434 MyApp[3652:425909] 	[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
```

Thank you very much, but I do not expect there to be log messages given that setting.

**Comment by nonelse** [comment]
Hi @arielelkin, thanks for the feedback.
The log level configuration allows to filter different levels of logging messages. The possible levels, from more generic, to more specific are:
 - Verbose
 - Debug
 - Info
 - Warn
 - Error
 - Assert

By choosing a more specific log level, you can only see log messages of that level or more specific. So, if you choose `Assert` level, you will only see log messages with `Assert` level. The level of `Assert` is the most critical, and currently we only have 1 message with that level. Having the correct environment configured is critical to the correct functioning of our tracking.

If there is still any doubts, just ask

**Comment by arielelkin** [comment]
@nonelse thanks for the information. 

Couple of points:

On iOS, `Assert` is something associated with assertions, as in runtime sanity checks (see [`NSAssert`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Functions/) and [`assert`](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html)). So using `Assert` to describe _logging_ doesn't make much sense on iOS and tends to cause confusion. 

> Having the correct environment configured is critical to the correct functioning of our tracking.

While I wholeheartedly support efforts to minimise programmer errors, _you, a third-party library, should not force **your** error-checking on the programmers **if they expressly disallow it**_, usually because they have their own error-checking methods in place. 

So, please:
* Reconsider the choice of words for log level configuration on iOS.
* Add a proper `None` option.

**Comment by nonelse** [comment]
I understand the confusion. These log levels were originally from Android, where logcat allows to filter the log messages natively. In iOs and Windows as well, we ported the same concept to try to make the sdk the most consistent as possible thru the different platforms. Internally, same naming of classes as `Handlers` shows a bit of that legacy.
But your suggestion of adding a `None` level that omits any log is a good one, and we will probably add it in a future update.
Thanks.

**Comment by arielelkin** [comment]
:+1:

**Comment by jomnius** [comment]
Still waiting for ADJLogLevelNone

**Comment by ynmehel** [comment]
I agree with @jomnius , .None would be a good idea

**Comment by nonelse** [comment]
We look into adding this feature as an option for our next release

**Comment by uerceg** [comment]
Added to https://github.com/adjust/ios_sdk/releases/tag/v4.9.0.
