### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by kamoljan** [adjust/ios_sdk#137]
Hi guys

Adjust SDK does not support Bitcode yet?!!

    pod 'Adjust', '4.4.1'

When are you going to support it?

**Comment by nonelse** [comment]
HI @kamoljan.
We will add the `ENABLE_BITCODE = YES` option inside the `project.pbxproj` file in the next release, but I believe that this option is already enabled by default and our SDK supports it as well. Have you had any problem trying to make a bitcode app while using the adjust sdk?

**Comment by kamoljan** [comment]
Hi @nonelse 

you are right, Adjust does support Bitcode already.
I just had to add this code into Podfile:

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
      end
    end

Thank you!
