### ISSUE TITLE
What's the reason for adjIdForAdvertisers implementation?

### ISSUE THREAD

**Issue by sebastianludwig** [adjust/ios_sdk#138]
I'm currently evaluating the adjust SDK and I stumbled upon the implementation of [`adjIdForAdvertisers`](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJAdditions/UIDevice%2BADJAdditions.m#L62) which looks unnecessary complicated and a bit shady - like what malware would do to disguise what it's actual doing. I can see that it's _not_ doing anything spooky, still could you please shed some light on the reasons why it has been chosen to implement it that way?

Thanks!

**Comment by nonelse** [comment]
Hi, thanks for bringing this up.
It's actually a legacy mechanism. Nowadays, there is a checkbox when releasing an app, that allows to use idfa even when the app does not have ads.
We are going to make a branch to de-obfuscate and test it with some clients. At some point in the future, it should be merged into a release version

**Comment by nonelse** [comment]
We've pushed the branch [plain-idfa](https://github.com/adjust/ios_sdk/tree/plain-idfa) with that change.
Feel free to test it before.

**Comment by sebastianludwig** [comment]
Thank you very much for clarifying!
