### ISSUE TITLE
Include dSYM and bcsymbolmap in prebuilt dynamic framework archive

### ISSUE THREAD

**Issue by akolov** [adjust/ios_sdk#149]
Could you include these files in the prebuilt zip file please?
They're quite helpful for debugging and the latter is required for bitcode submissions.
Thank you!

**Comment by uerceg** [comment]
Hi @akolov 

`AdjustSdkDynamic.framework.zip` is now updated, please re-download it and you will find `dSYM` file attached. Let me know if that went okay.

Regarding `bcsymbolmap` - can you explain us maybe a bit more how to generate this file? Thanks in advance.

**Comment by akolov** [comment]
Hey @uerceg. Thanks for the update!
The bcsymbolmap should be already generated for you since the bitcode generation is enabled in target settings. It's name can be a little obscure though, something like these 3 files (for each platform):
```
21B1FAF4-684C-30D9-B7CC-70D4C28B8ACF.bcsymbolmap
58ED9C39-F860-30EF-B2A2-C1F94149847A.bcsymbolmap
EC950394-28FE-3453-ABCE-D9371471E2D6.bcsymbolmap
```

If you're using carthage it's easy to build and archive the whole package (including dSYM and bcsymbolmap files):
```
carthage build --no-skip-current
carthage archive AdjustSdk
```

This will generate AdjustSdk.framework.zip in the root folder of the project with everything already included.

**Comment by uerceg** [comment]
@akolov Thanks for the instructions. And give it another try one more time. :)

**Comment by akolov** [comment]
Yep, all is good now. Thank you!
