### ISSUE TITLE
BitCode Support

### ISSUE THREAD

**Issue by loretoparisi** [adjust/ios_sdk#151]
Please add support for bitcode.

**Comment by uerceg** [comment]
@loretoparisi We have BITCODE enabled by default: https://github.com/adjust/ios_sdk/commit/0af6f608740a66356a622879710e4fca375173c3

For more information, we had this question already: https://github.com/adjust/ios_sdk/issues/137

**Comment by loretoparisi** [comment]
@uerceg :100: thanks!
