### ISSUE TITLE
Deep Links are not working from Native email client and Calendar and whatsapp

### ISSUE THREAD

**Issue by jazz-mobility** [adjust/ios_sdk#153]
Hi,

I am using this sdk but it seems like deep links are not working from any of the apps like, native Mail client, Calendar and whatsapp.
It works fine when i click on Gmail app. Can you please help me quickly here I have to submit the app to Appstore ASAP.

**Comment by uerceg** [comment]
Hi @jazz-mobility 

Can you maybe describe me scenario which you are performing in order to test deep linking?

If you are in a hurry, feel free to email support@adjust.com and refer in there to this issue, so that we can maybe solve this thing faster.

Cheers

**Comment by jazz-mobility** [comment]
I have a sharing feature in my app which shares the url on email.
URL is like - https://app.adjust.com/myadjustID?deep_link=myappname://sometext

It sends the url and when i click the url from gmail app, it goes to google chrome and it works.
But when i open from iOS Native Mail client, it goes to safari and it does not redirect to app, it redirects to the custom url provided in Adjust web settings.

So, if i understood it correctly deep links are not working from safari, but same url works from chrome.

Thanks.

**Comment by NeoHuang** [comment]
@jazz-mobility have you encoded the `deep_link` parameter?

**Comment by jazz-mobility** [comment]
Can you send me the encoding type, i tried encoding with NSUTF8 and ASCII but still not worked.
Tried the universal linking as well, I am on iOS 9.2 but it is not working as well.

Just for the update everything works fine on iOS 8. can you please suggest me.

![screen shot 2016-01-13 at 4 55 54 pm](https://cloud.githubusercontent.com/assets/2293605/12300197/b0854366-ba1a-11e5-8b21-45d269fe6679.png)

**Comment by NeoHuang** [comment]
@jazz-mobility it should be URL encoding, you can find some online tool like this
http://meyerweb.com/eric/tools/dencoder/
for instance 
`myappname://sometext` would be encoded like `myappname%3A%2F%2Fsometext`

for universal link: as far as we tested, content type `application/pkcs7-mime` is not required

**Comment by NeoHuang** [comment]
@jazz-mobility as stated in https://docs.adjust.com/en/universal-links/ custom scheme deeplinking doesn't work in iOS 9.2 or above. pls implement Universal link to handle it. pls also notice that Universal link is a new feature start from iOS 9.0. so we highly recommend that you implement both custom scheme deeplinking and universal link. and adjust will choose which to use according to iOS version.

**Comment by jazz-mobility** [comment]
I have implemented both. Got the URL as well and updated the provisioning profiles and entitlements.
Still not redirect to the app. I can see json file at myurl/apple-app-site-association, it shows correct data.
It redirects from chrome but not from safari.
Can you please confirm if I need to change the url as well?
https://app.adjust.com/xxxxx?deep_link=myapp://
It would be nice if we can discuss this on skype, my skype is jazz1404. I am really looking to solve it quickly.

**Comment by NeoHuang** [comment]
please encode the deeplink as I described before.

**Comment by jazz-mobility** [comment]
I did that already, that was just for example. It looks like this. with my id in place of xxxxx.
https://app.adjust.com/xxxxx?deep_link=myapp%3A%2F%2Ftest

**Comment by NeoHuang** [comment]
Pls fire an issue to support@adjust.com with some technical details including tracker token and app token so that we can have a closer look if you still have the problem. Thanks

**Comment by jazz-mobility** [comment]
Have you guys figured out the problem with Adjust Automatic deep linking ? I can see lot of changes in documentation after I raised this issue. Can you please let me know how can I test it without uploading my app to app store. May be there is some way using test flight ?

**Comment by NeoHuang** [comment]
@jazz-mobility thanks for your comments. As we found out redirected Universal link doesn't work when the click is not triggered from Safari. this seems a limitation from Apple which we can not do too much. sorry.

**Comment by jazz-mobility** [comment]
Can you please have a look why redirection is working fine on Google Chrome, As far as I understand they are also using the Webkit.

**Comment by NeoHuang** [comment]
@jazz-mobility for Google Chrome our backend still response with scheme deeplink, not universal link. although Chrome share most part with Safari, there are still difference of some detail implementation. Also we know that some WebView is still working with scheme deeplink.

**Comment by jazz-mobility** [comment]
So, You guys found a way to make it work on iOS 9.2, or I have to remove the Adjust from my project ?

**Comment by NeoHuang** [comment]
@jazz-mobility as I mentioned before. Universal Links works on iOS 9.2 with some limitation. this is not a limitation from us, but from Apple - redirected Universal Link only works when the click happens within Safari. We feel sorry about your decision.

**Comment by uerceg** [comment]
@jazz-mobility We do have solution which works for all iOS versions. You can read about it in here: https://docs.adjust.com/en/universal-links/ especially paragraph `3.2 | Redirecting to Universal Links directly`.

If you encounter any issues with this, feel free to reach us in here or by sending us an email on support@adjust.com and referencing this issue.

Cheers

**Comment by Anurag-Srivastav** [comment]
The url opens the app if i touch it from notes or messages but does not triggers the app when i try clicking the same link from an email.Can somebody tell what is the problem.

**Comment by sletthaug** [comment]
@Anurag-Srivastav 
Please reach out to your Adjust technical account manager if you have one, alternatively to support@adjust.com with all the information about this issue, including videos of the behaviour you are observing. They will help you find the reason for what is going on.

**Comment by 1pavanb** [comment]
> The url opens the app if i touch it from notes or messages but does not triggers the app when i try clicking the same link from an email.Can somebody tell what is the problem.

@Anurag-Srivastav When testing whether an email link redirects you to the app, use an email sender to Compose your email. Eg https://putsmail.com/

If you compose via your inbox Email clients may create a proxy link. Due to the proxy link having a different domain, Android never triggers the redirect to the App.

I assume you have added the [asset links](https://developer.android.com/training/app-links/verify-site-associations) file to your website.
