### ISSUE TITLE
About bitCode I used Adjust version 4.5.1static framework

### ISSUE THREAD

**Issue by zhangyu528** [adjust/ios_sdk#160]
Is it supported BitCode?
I archive build my app with the adjust framwork.
error:AdjustSdk.framework/AdjustSdk(ADJTimerCycle.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

**Comment by mpatafio** [comment]
I figured out with the same problem. I submitted a pull request. Try to add the following user defined setting to the Adjust project and recompile the libs:
BITCODE_GENERATION_MODE=bitcode 

this should provide full bitcode support

**Comment by zhangyu528** [comment]
Great! When can release the version?

**Comment by uerceg** [comment]
We'll check the PR internally and let you know, but IMHO ASAP.

**Comment by uerceg** [comment]
https://github.com/adjust/ios_sdk/pull/163

Btw, although enabled for static library, once merging it with `lipo` to target multiple platforms, looks like `lipo` was removing BitCode from the library. Something for reference: https://forums.developer.apple.com/thread/9451

Anyway, we'll probably merge this PR today. Will keep you posted in here.

**Comment by nonelse** [comment]
Just released [v4.5.3](https://github.com/adjust/ios_sdk/releases/tag/v4.5.3) that works even with lipo

**Comment by uerceg** [comment]
Let us know if it works for you now. Thanks in advance.

**Comment by mpatafio** [comment]
It works but I get thousands of warnings.

**Comment by uerceg** [comment]
Will be solved in next release (probably tomorrow).

**Comment by uerceg** [comment]
@mpatafio Can you tell me how are you adding our SDK to your app?

**Comment by uerceg** [comment]
Fixed in https://github.com/adjust/ios_sdk/releases/tag/v4.5.4.

Feel free to reopen the issue if you encounter it again.
