### ISSUE TITLE
Parsing Universal Links form Adjust 

### ISSUE THREAD

**Issue by marciok** [adjust/ios_sdk#162]
Hi guys,
I implemented Universal Links for Adjust (Added the hash subdomain).
Everything works fine, although I'm confused.

 The URL that I received on `-application: continueUserActivity:restorationHandler:`  has the Adjust format: `[hash].uilink.adjust.com/uilink/path`.
Do I have to parse manually and extract the desired values? or I should've received something else?

**Comment by uerceg** [comment]
Hi @marciok

Yes, pretty much that's the idea behind it. Parse the path to obtain the info you wrote to the URL and perform some actions in your app based on that. 

Cheers

**Comment by marciok** [comment]
I see, thanks @uerceg.
It would be great if the Adjust SDK could extract the info, i.e
```objective-c
NSString *myPathAndQueries = [Adjust extractPathAndQueriesFromUniversalLink:userActivity.webpageURL]; 
// myPathAndQueries would be: path/?key=foo&value=bar or nil if it's not an Adjust link
```
Than I wouldn't have to worry about maintaining my own parser. What If you guys decided to change the URL format on the backend? I will have to always ping here to make sure my parser is updated. Furthermore this is a common problem, every SDK user has to write its own code to solve a common issue.

**Comment by uerceg** [comment]
@marciok I see your point. We'll discuss it internally and let you know what we decided about it. Thanks for the suggestion.

**Comment by marciok** [comment]
:+1:

**Comment by uerceg** [comment]
@marciok Would you expect this new method from `Adjust` instance to give you back `NSString` or `NSURL` object? I don't know if you were building your further parsing logic on parsing `NSURL` object you were getting, or you maybe just converted it to `NSString` and parsed the string object afterwards.

**Comment by uerceg** [comment]
@marciok We added this method https://github.com/adjust/ios_sdk/commit/82086dc598db041cb87ede12ab09d6e0556849b1 as part of our latest release (https://github.com/adjust/ios_sdk/releases/tag/v4.5.4).

Method is going to return `NSURL` object which you were expecting with "old" deep linking if you pass your scheme name to the method, so you don't need to change your parsing logic.

Cheers
