### ISSUE TITLE
Criteo not found

### ISSUE THREAD

**Issue by danielebogo** [adjust/ios_sdk#170]
I've installed the last version of adjust using cocoapods. I've to use Criteo in my project, but i don't find any plugin in the pod folder. Any idea? The adjust podspec seems right.

**Comment by nonelse** [comment]
We have our plugins as submodules in cocoapods. 
For Criteo replacing `pod 'Adjust'` with `pod 'Adjust/Criteo'` should install the Criteo plugin.

**Comment by uerceg** [comment]
Hi @danielebogo 

Did you manage to solve this issue?

**Comment by danielebogo** [comment]
Hi @uerceg , yes i've solved it using the ```pod 'Adjust/Criteo'``` to install also the plugin with cocoapods. Thanks a lot @nonelse .

**Comment by uerceg** [comment]
Great! Glad it worked. :+1:
