### ISSUE TITLE
Adjust exposes internal files in the documents directory

### ISSUE THREAD

**Issue by ogkent** [adjust/ios_sdk#171]
We see these 3 files getting written to the documents directory:
- AdjustIoActivityState
- AdjustIoAttribution
- AdjustIoPackageQueue

When [file sharing](https://support.apple.com/en-us/HT201301) is enabled for the app, these files can be modified/deleted from inside iTunes.

Apple's recommendation is to store these files in the `Library/Application Support` directory. See https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html.

**Comment by nonelse** [comment]
That is a good point, @ogkent. We will look into add it to the next major release.
Thanks!

**Comment by Constantine-Fry** [comment]
Are there any plans to fix this issue?

**Comment by Neonkoala** [comment]
Checking if there are any updates on this. It's 2017, why is there metadata being stored in the Documents directory?

If there are no plans to fix this we'll be moving to a competitor.

**Comment by uerceg** [comment]
This is being internally discussed these days and will probably be added in one of the upcoming updates. After discussion we'll hopefully have more clearer ETA on this and I will update you on this issue.

**Comment by sebastato** [comment]
Any updates on this? With iOS11 and Files.app these files are a major issue.

**Comment by uerceg** [comment]
@sebastato 

Yes, we are getting close to iOS SDK v4.12.0 release in which we have migrated Adjust files from `Documents` to `Application Support/Adjust` folder. Still no definite ETA, but it is in final stages. Will keep you posted in here, but definitely with next update files will be migrated out from `Documents` folder.

**Comment by uerceg** [comment]
@ogkent @Constantine-Fry @Neonkoala @sebastato 

As of iOS SDK v4.12.0 (https://github.com/adjust/android_sdk/releases/tag/v4.12.0), Adjust internal files will be migrated from `Documents` folder to `Application Support/Adjust` folder.

Cheers

**Comment by phenze** [comment]
It looks like tvOS Apps cannot write to Application Support Folder.
is there any workaround for this ?

Im getting this error:

`[Adjust]e: Error Domain=NSCocoaErrorDomain Code=513 "Du hast nicht die Zugriffsrechte, um die Datei „Application Support“ im Ordner „Library“ zu sichern." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/F082E868-B10C-400F-9438-B6BAA9ED39EA/Library/Application Support, NSUnderlyingError=0x282f18270 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}`
