### ISSUE TITLE
Build Failure - Duplicate Symbols

### ISSUE THREAD

**Issue by ccsidev** [adjust/ios_sdk#173]
I went through the steps from this site to integrate the iOS SDK in to my project.  My iOS target is 7.0 so I downloaded the static framework zip file.  After adding the basic setup code to my project I tried to run it but it failed to compile.

I'm getting a bunch of duplicate symbol errors (see attached file).
[adjust_error.txt](https://github.com/adjust/ios_sdk/files/153758/adjust_error.txt)

I have contacted support at Adjust.com, and, after exchanging a couple emails, was told to come here to post the issue.

I have already gone through the build phases (several times) and have not found anything amiss here.  I even removed the Adjust frame work and all references to it and added it again just to make sure I followed the instructions properly with the same results.

Looking at the error messages, it appears the duplicates are in the Adjust.o library file.

If you need any more info, please let me know.

Thanks.

**Comment by uerceg** [comment]
Hi @ccsidev 

Thank you for reaching us. Which iOS SDK version are you trying to integrate?

Cheers

**Comment by ccsidev** [comment]
As I mentioned above, the static version.  I downloaded adjustSdkStatic.framework.zip.

**Comment by uerceg** [comment]
I was thinking which version number? The latest version `4.5.4`?

**Comment by ccsidev** [comment]
I downloaded it 2 days ago so I believe it is the latest.  The creation date on the files in the SDK folder is Feb. 5, 2016.

**Comment by uerceg** [comment]
Ah, now I see that we accidentally named the static SDK in release with small letter A. I have updated that now, feel free to re-download the latest static SDK release and give it a try.

But that won't probably solve your issue. Anyway, I tested static framework from latest release again and I didn't see any issues. Can you show me the code you are using to initialise SDK and where are you doing?

Btw, if you think that sharing your code in here is to sensitive for you, feel free to reach us on support@adjust.com and I will get in touch with you per email to continue discussing this issue.

Cheers

**Comment by ccsidev** [comment]
I removed the old framework and copied over the new version I just downloaded.  Getting same error.  I just have the basic initialization code:

`
    NSString* token = [Common getAdjustSDKToken];
    if (token) {
        ADJConfig* adjustConfig = [ADJConfig configWithAppToken:token environment:ADJEnvironmentSandbox];
        [adjustConfig setLogLevel:ADJLogLevelVerbose];
        [Adjust appDidLaunch:adjustConfig];
    }
`

I did a bit of searching on the error I'm getting and it appears to be due to me using an older version of Xcode (version 5.1.1).  To upgrade my version of Xcode, I would need to update the Apple OS on this computer first so it is a hassle I'm trying put off until I absolutely have to.  Any chance of getting I library I can test with that works with older versions of Xcode?

Here is a link to another library where the same issue was reported:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/271

**Comment by uerceg** [comment]
Hm. I was investigating this thing a bit. It looks like Xcode version below 7 reports this issue if bitcode is supported in framework (like it is in couple of our latest releases).

This is the first release where we introduced bitcode support: https://github.com/adjust/ios_sdk/releases/tag/v4.5.3

And this is the version before adding bitcode support: https://github.com/adjust/ios_sdk/releases/tag/v4.5.2

Can you maybe try these two versions and see if maybe version `4.5.2` works for you and doesn't report these errors? If so, than it looks like it is related to bitcode support we have added.

**Comment by ccsidev** [comment]
Excellent, version 4.5.2 compiles for me.  Unless this earlier version is not supported, I will use this until I eventually upgrade my Xcode version.  Thanks.

**Comment by uerceg** [comment]
Glad it worked for you. We will investigate if there's a way to bypass these errors on older Xcode version with bitcode support added to the framework. If we don't manage to do that, maybe worst case scenario will be to maybe attach both versions of framework (with and w/o bitcode support) to the release.

But we'll discuss this thing internally first.

If you encounter any other issues regarding this thing feel free to reopen the issue and once we investigate this further and come up with solution, I will update you in here.

Cheers
