### ISSUE TITLE
Unsupported Architectures

### ISSUE THREAD

**Issue by nateboxer** [adjust/ios_sdk#175]
When I add the Adjust ios_sdk framework to my project, I am no longer able to upload to itunesconnect. It specifically states that the ios_sdk framework includes binaries compiled for i386 architecture. No where in my xcode settings does my app include such architectures. I've included a screen shot of the errors.
![screen shot 2016-03-01 at 11 31 49 am](https://cloud.githubusercontent.com/assets/11063769/13469365/f239c2b6-e05b-11e5-9026-7293af64d924.png)
I installed the framework using the latest Carthage build.

**Comment by uerceg** [comment]
Hi @nateboxer 

Hm. That is weird. Are you maybe doing a store build while a simulator is chosen, instead of a device in Xcode?

We have those architectures supported in our library for a long time and this is the first time we see this issue reported.

```
adjust:A uerceg$ lipo -info AdjustSdk 
Architectures in the fat file: AdjustSdk are: armv7 armv7s i386 x86_64 arm64
```

**Comment by nateboxer** [comment]
I am disconnecting all devices and using generic ios to build. I've tried
it several times, cleaned, etc...

**Comment by uerceg** [comment]
What is the lowest supported iOS version in your app? Did you maybe added `AdjustSdk.framework` in `Copy Bundle Resources`?

**Comment by nateboxer** [comment]
We support iOS 8.4+

And yes, I was unable to use Adjust without copying due to the dyld linker
error - can't find the framework. Is that what's causing this?

**Comment by uerceg** [comment]
To be honest, I am no Carthage guru, but once I was experimenting with Carthage in our example app, I was simply following instructions from their GitHub page: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

So, I added our SDK to app by adding this line to `Cartfile`:

```
github "adjust/ios_sdk"
```
And by creating this Copy Script they mentioned:

<img width="1010" alt="screen shot 2016-03-02 at 23 30 08" src="https://cloud.githubusercontent.com/assets/1741635/13477939/f1d21b7a-e0ce-11e5-9f47-2b3054b17f96.png">

As you can see, I didn't add the framework to `Copy Bundle Resource` part.

**Comment by uerceg** [comment]
And now when I pay even more attention to their docs, it says following:

```
This script works around an App Store submission bug triggered by universal binaries and ensures that necessary bitcode-related files and dSYMs are copied when archiving.
```

This issue: http://www.openradar.me/radar?id=6409498411401216

Which kinda looks like yours.

**Comment by nateboxer** [comment]
That did it! Thank you! I apologize, I'd done that before with another
framework but I'd never gotten those errors before so I thought it must
have been something different.

**Comment by uerceg** [comment]
No problemo, glad it worked for you. :+1:
