### ISSUE TITLE
Deprecated iAd framework

### ISSUE THREAD

**Issue by Johannes-HAWHH** [adjust/ios_sdk#196]
Dear adjust team,

I would like to add your iOS SDK to our project.

Under “3. Add the AdSupport and iAd framework”, you are mentioning the iAd Framework, which will be deprecated (See https://developer.apple.com/iad/ and https://developer.apple.com/support/iad/ ).

Will I be able to upload my app to the app-store, even if I use the deprecated iAd Framework? Or is there a workaround possible?

Thanks in advance!

**Comment by nonelse** [comment]
Hi. Our SDK is not using any of the classes or their API that are being deprecated.
Our use of the iAd framework is to detect if the app was installed from an iAd of another app, not to actually display ads.
We only use `ADClient` class and it's API's. From the [link](https://developer.apple.com/support/iad/):
`ADClient APIs (requestAttributionDetailsWithBlock and addClientToSegments) will continue to work`.

**Comment by pavm035** [comment]
But is it still good to have these deprecated framework in the SDK?

**Comment by uerceg** [comment]
Our SDK does not contain iAd framework. If user has included iAd framework in the app for some reason (handling Apple Search Ads for example), our SDK will read some info from iAd framework using the classes which Apple didn't state as deprecated ones in their announcement. So adding our SDK to the app doesn't mean that our SDK implicitly adds iAd.framework to it, that's up to user to decide. If iAd framework is not present, our SDK simply doesn't use stuff from it and continues to operate normally.

Apple has confirmed that iAd framework v3 is required for tracking Apple Search Ads and usage of the iAd framework for these purposes will not lead to app rejection. Please contact your Apple representative for more details on this.

**Comment by pavm035** [comment]
Thanks bunch @uerceg  :)
