### ISSUE TITLE
Why is Deployment Target 9.1?

### ISSUE THREAD

**Issue by mono0926** [adjust/ios_sdk#198]
I installed the SDK by Carthage.
The app crashed when running on an iOS 8 device.

This is error log:

```
dyld: Symbol not found: ___NSArray0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DEB4C604-AB55-4E46-9529-74647CEE6DFE/JoinUs.app/Frameworks/AdjustSdk.framework/AdjustSdk (which was built for iOS 9.1)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/DEB4C604-AB55-4E46-9529-74647CEE6DFE/JoinUs.app/Frameworks/AdjustSdk.framework/AdjustSdk
```

Should I fork this if I'd like to use for iOS 8?

<img width="658" alt="screen shot 2016-06-15 at 6 21 31 pm" src="https://cloud.githubusercontent.com/assets/1255062/16074648/71df329a-3326-11e6-945e-01d9a3c4db2b.png">

**Comment by uerceg** [comment]
Hi @mono0926 

Thanks for letting us know, no need to fork it, we will update it to be 8.0. 👍 

Cheers

**Comment by mono0926** [comment]
@uerceg 

Thank you.
I noticed that the PR https://github.com/adjust/ios_sdk/pull/192 fixed this.
When will you merge the PR?

**Comment by uerceg** [comment]
Pretty much as soon as possible. Hopefully it will be live on Friday.

**Comment by mono0926** [comment]
@uerceg 

Okay, thanks 👍

**Comment by uerceg** [comment]
Added PR #192 to `v471` branch. @mono0926 Can you for test sake just try to add our SDK via Carthage from that branch?

I guess you should just modify your `Cartfile` entry to:
```
github "adjust/ios_sdk" "v471"
```
If it works for you, we'll merge it to master.

Thanks in advance for feedback.

**Comment by mono0926** [comment]
@uerceg 

> If it works for you, we'll merge it to master.

It works nice, thanks 👍

**Comment by uerceg** [comment]
Awesome, will be merged soon, so that you can retarget the master branch in your `Cartfile` instead of this `v471`. Will update in here and close the issue once it's merged.

**Comment by mono0926** [comment]
Okay, thanks 🎉

**Comment by uerceg** [comment]
Released https://github.com/adjust/ios_sdk/releases/tag/v4.7.1. You might now try from master branch as well and let me know if it works.

**Comment by mono0926** [comment]
Thank, it works well 🎉
