### ISSUE TITLE
Universal Links are supported since iOS 9, aren't they?

### ISSUE THREAD

**Issue by mono0926** [adjust/ios_sdk#200]
https://github.com/adjust/ios_sdk/blob/master/README.md

> **Important**: Tracker URLs with `deep_link` parameter and your custom URL scheme
in it are no longer supported in `iOS 8 and higher` and clicks on them will not 
cause your app to be opened nor `openURL` method to get triggered. Apple dropped 
support for this way of deep linking into the app in favour of `universal links`. 
However, this approach will `still works for devices with iOS 7 and lower`.

> #### <a id="universal-links">Universal Links

>**Note**: Universal links are supported `since iOS 8`.

I think this is incorrect.
Universal Links are supported since iOS 9, aren't they?

See: https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by uerceg** [comment]
@mono0926 

And again, thanks for your contribution. Updated in https://github.com/adjust/ios_sdk/pull/201.

Cheers!

**Comment by mono0926** [comment]
@uerceg 

Thanks 😋
