### ISSUE TITLE
trademob branch crashes on iOS 8

### ISSUE THREAD

**Issue by cargath** [adjust/ios_sdk#204]
We are using the trademob branch in our project, i.e. the Cartfile looks like this:

    github "adjust/ios_sdk" "trademob"

This always worked fine, but now we ran into trouble running our app on iOS 8 devices. It crashes with with the error message:

    dyld: Symbol not found: ___NSArray0__
    Referenced from: /private/var/mobile/Containers/Bundle/Application/674D8B5A-5673-4566-8E05-F276476C3D7C/Airberlin.app/Frameworks/AdjustSdk.framework/AdjustSdk (which was built for iOS 9.1)
    Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
    in /private/var/mobile/Containers/Bundle/Application/674D8B5A-5673-4566-8E05-F276476C3D7C/Airberlin.app/Frameworks/AdjustSdk.framework/AdjustSdk

Looks like you raised the iOS deployment target to iOS 9.1? We need to support iOS 8, could you lower the deployment target again or is there a specific older commit we should be using?

**Comment by nonelse** [comment]
Hi. Thanks for pointing out that our plugin branches were not updated to the latest version v4.7.1. This issue should be solved now

**Comment by cargath** [comment]
Thanks for the quick reply! It's working again.
