### ISSUE TITLE
Adjust doesn't compile against iOS 10 SDK beta 2

### ISSUE THREAD

**Issue by nikolaykasyanov** [adjust/ios_sdk#205]
https://github.com/adjust/ios_sdk/blob/a42769dde9f8232549237e3e8e99d03d218e557f/Adjust/ADJSystemProfile.m#L70-L73

Those two defines aren't here anymore.

Edit: fixed the link.

**Comment by nonelse** [comment]
hi @nikolaykasyanov 

I haven't updated to the beta2, but the beta1 still has those two defines. I'll update to new beta to test it.
That change will be will also included in the new release of the adjust SDK that will support Xcode 8 and iOS 10.

Thanks for letting us know about the new update!

**Comment by uerceg** [comment]
Fixed in https://github.com/adjust/ios_sdk/releases/tag/v4.7.3. Thanks to @thomasrzhao for PR!
