### ISSUE TITLE
Build error on xCode 8.0 beta 2

### ISSUE THREAD

**Issue by hovox** [adjust/ios_sdk#207]
Hi there,

We are receiving this build errors :

`ADJSystemProfile.m:70:14: Use of undeclared identifier 'CPUFAMILY_INTEL_YONAH'`

`ADJSystemProfile.m:72:14: Use of undeclared identifier 'CPUFAMILY_INTEL_MEROM'`

Note that on xCode 8.0 beta 1 there is no any build errors.

**Comment by uerceg** [comment]
Fixed in https://github.com/adjust/ios_sdk/releases/tag/v4.7.3. Thanks to @thomasrzhao for PR!
