### ISSUE TITLE
Error message "SDK click failed"

### ISSUE THREAD

**Issue by billypchan** [adjust/ios_sdk#212]
Hello support manager,

I found there is a lot of log message produced when I running UI tests. Is it normal?
The message looks like:

[Adjust]e: SDK click failed (SDK click missing tracker) (app_token: ???, adid: ???)

Thanks in advance.

**Comment by uerceg** [comment]
Hi @billypchan 

Does it look like something like this? https://github.com/adjust/ios_sdk/#ts-iad-sdk-click

**Comment by billypchan** [comment]
@uerceg Thanks!
