### ISSUE TITLE
Using 4.8.0 with Criteo?

### ISSUE THREAD

**Issue by davidblaesing** [adjust/ios_sdk#213]
I want to use `ADJCriteo` with `4.8.0` currently I was using the `criteo` branch for that.
Can I get it with `4.8.0`?

**Comment by uerceg** [comment]
Hi @davidblaesing 

Thanks for reporting this, will be enabled ASAP.

**Comment by uerceg** [comment]
Hi @davidblaesing 

Can you explain us a bit what is the exact problem you are facing with? `ADJCriteo` is part of the `4.8.0` release, if you check the current `criteo` branch, here it is: https://github.com/adjust/ios_sdk/tree/criteo/Adjust/Criteo

**Comment by davidblaesing** [comment]
@uerceg 
When I go for Carthage github `"adjust/ios_sdk" ~> 4.8.0` I miss the `ADJCriteo`.
Do I have the latest version of Adjust, when I am using `"adjust/ios_sdk" "criteo"`?

**Comment by davidblaesing** [comment]
Its was a bit confusing for me, but I am just updating `"adjust/ios_sdk" "criteo"` now (:

**Comment by uerceg** [comment]
Yeah, that's how it should be used. :) 👍
