### ISSUE TITLE
Concurrency issues and request failures

### ISSUE THREAD

**Issue by scelis** [adjust/ios_sdk#215]
We have a user who is getting into a loop in the Adjust SDK. ADJPackageHandler is trying to send its package up to the Adjust servers but always receives a 500 error with the following response:

> Event failed (Ignoring duplicate event. Last event count: 105 this event count: 105 last event time: 2015-02-27T05:15:07 this event time: 2015-02-27T05:15:07) (app_token: APP_TOKEN_HERE, adid: ADID_TOKEN_HERE)

This causes the Adjust SDK to sleep using a backoff strategy and to try again later. However, due to the way that the Adjust SDK handles concurrency, this sleep on line 93 of ADJPackageHandler.m has negative impacts on other code in our app:

`[NSThread sleepForTimeInterval:waitTime];`

Adjust's PackageHandler uses an internal `dispatch_queue` on which it performs most of its work. However, due to the way that iOS uses dispatch queues, multiple queues can actually share the same backing thread. By sleeping the entire thread here, our own queues that have been assigned to the same thread are now unable to perform any work.

These two issues, when combined together, cause parts of our app to grind to a halt for that user because the Adjust PackageHandler completely ties up a thread sleeping again and again.

As such, I think there are a few separate issues here:

1. We have a user that gets stuck in a loop because the Adjust server continually responds to PackageHandler requests with a 500 error.
2. [ADJPackageHandler.m](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJPackageHandler.m#L93) is sleeping the thread when it should probably be doing a `dispatch_after` to relinquish the current thread and let other work continue in the interim.
3. It also appears that there is a similar thread sleeping issue in [ADJSdkClickHandler.m](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJSdkClickHandler.m#L114)

**Comment by uerceg** [comment]
@scelis Thank you very much for this detailed description. We will check this and get back to you as soon as possible.

**Comment by uerceg** [comment]
@scelis Saw your comment with exception message. Did you generate the exception with the branch now with additional commits which @nonelse added or just the one which contained only your commit?

**Comment by scelis** [comment]
@uerceg Yeah I deleted my comment when I saw that a fix had already been applied to this branch. Thanks!

**Comment by nonelse** [comment]
Fixed with v4.8.1
