### ISSUE TITLE
Use of undeclared identifier: CPUFAMILY_INTEL_YONAH & CPUFAMILY_INTEL_MEROM (Version 8.0 beta 3 (8S174q))

### ISSUE THREAD

**Issue by manderson420** [adjust/ios_sdk#218]
This is a pre-emptive attempt to address a compilation failure for the upcoming XCode 8 release. Our iOS team is attempting to preemptively address any issues with XCode 8 (specifically converting our Swift 2.x syntax to Swift 3.0 syntax using the built in conversion tool...yikes).

One of the issues we are having is with the `ADJSystemProfile.m` file method `+ (NSString*) cpuFamily`. Here are the reproduce steps:

1. Download the XCode 8 beta 3 from the developer portal.
2. Open your project that should contain an Adjust SDK as a Pod. Specifically `pod 'Adjust', '4.7.1'` in addition to code using Swift 2.x syntax
3. You will be prompted with the auto-conversion tool update alert.
4. Choose 'Convert'
5. Opt in/choose Swift 3.0 syntax as your preference
6. Choose 'Save' when the change-set preview appears.

Expected: Yay, the project compiles and life is good.
Actual: `Use of undeclared identifier CPUFAMILY_INTEL_YONAH` and `Use of undeclared identifier CPUFAMILY_INTEL_MEROM` compiler errors in the `ADJSystemProfile.m` file. If I command click into the `machine.h` file and search for the macros, they do appear to have been removed.

I know its beta software and all, but just a heads up before you start getting angry emails from your users :) This issue should be resolved so that we don't have to fork anything or modify Adjust SDK source on our end.

![screen shot 2016-07-27 at 5 31 16 pm](https://cloud.githubusercontent.com/assets/17992590/17197255/020650dc-5420-11e6-9eb0-e29196a70d0e.png)

**Comment by uerceg** [comment]
Hi @manderson420 

This issue was already reported to us and we actually updated the SDK to prevent these errors from happening in iOS 10 beta.

For reference: https://github.com/adjust/ios_sdk/issues/207 and https://github.com/adjust/ios_sdk/issues/205

Which SDK version are you using?

**Comment by manderson420** [comment]
@uerceg Thanks for the update. We just updated our SDK to use version 4.8 and the issue is resolved. Sorry, should have checked before opening the issue!
