### ISSUE TITLE
AdjustConfig delayStart property doesn't work

### ISSUE THREAD

**Issue by AmmarSaadDine** [adjust/ios_sdk#243]
Using `[adjustConfig setDelayStart:5.5]` as mentioned in the documentation doesn't really delay anything by itself. I'm setting it when I initialise the ADJConfig object before calling 
`[Adjust appDidLaunch:adjustConfig]`

I tried to look a bit into the issue and it looks like Adjust doesn't apply the delay because it depends on a condition set in the ADJInternalState, and the developer has no control over that.
So is this an issue or am I just not using it properly?

**Comment by nonelse** [comment]
The delay start only applies for the install. Further session will not be delayed with this setting.
The purpose of this feature is to allow session parameters, such as session callback parameters to be send in the first session, even if they are only know after the adjust sdk start. 
You can test this feature by setting a delay start and seeing in the verbose logs the delay from the first session package enqueue and the response obtained after sending it

**Comment by AmmarSaadDine** [comment]
Thanks for the explanation. I tested it and it works perfectly.
