### ISSUE TITLE
Latest release binary doesn't include simulator architectures

### ISSUE THREAD

**Issue by akolov** [adjust/ios_sdk#244]
When installing via Carthage, prebuilt binary (v4.10.1) does not include simulator architectures (x86_64 and i386):
```
$ file AdjustSdk
AdjustSdk: Mach-O universal binary with 2 architectures: [arm_v7: Mach-O dynamically linked shared library arm_v7] [arm64]
AdjustSdk (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
AdjustSdk (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by uerceg** [comment]
Hi @akolov 

Thanks for reporting this. Please, retry and let us know if it works for you now.

Cheers

**Comment by akolov** [comment]
New 4.10.1 doesn't have prebuilt binaries attached at all :)

**Comment by uerceg** [comment]
Better now? :)

**Comment by akolov** [comment]
Nope, Carthage doesn't pick "AdjustSdkDynamicWithSimulator.framework.zip" up 😭

**Comment by uerceg** [comment]
Hm, that is weird. 😕 

I have an example app in which I have `Cartfile` with this content:

```
github "adjust/ios_sdk" == 4.10.1
```

After I `carthage update` and `carthage build`, I get `AdjustSdk.framework` built in `Carthage/Build/iOS` folder. If I go inside of the framework and say:

```
lipo -info AdjustSdk
```

I get:

```
Architectures in the fat file: AdjustSdk are: i386 x86_64 armv7 arm64
```

If I build an app for iOS simulator in Xcode and run it on simulator, everything works just fine.

:

**Comment by akolov** [comment]
Yeah it works if I build the framework (you do that explicitly with carthage build, I work around by either pointing to `master` or `--no-use-binaries` flag), not if I let Carthage download prebuilt archive.
For example:
```
$ carthage version
0.18
$ cat Cartfile
github "adjust/ios_sdk" == 4.10.1
$ carthage update --platform iOS ios_sdk
*** Fetching ios_sdk
*** Downloading ios_sdk.framework binary at "Remove backgroundSessionConfigurationWithIdentifier"
*** xcodebuild output can be found in /var/folders/11/qznmhg015wj1x9sj6sthlysc0000gn/T/carthage-xcodebuild.7gfov5.log
$ lipo -info Carthage/Build/iOS/AdjustSdk.framework/AdjustSdk
Architectures in the fat file: Carthage/Build/iOS/AdjustSdk.framework/AdjustSdk are: armv7 arm6
```

**Comment by uerceg** [comment]
Hoho, this is good. Lemme try one thing to see if it will work. Ping you soon.

**Comment by uerceg** [comment]
And give it a try now.

**Comment by akolov** [comment]
Yep, works fine now! Thank you :)
