### ISSUE TITLE
Nullability annotations needed to prevent silent-ish failures in Swift 3

### ISSUE THREAD

**Issue by benasher44** [adjust/ios_sdk#246]
I recently discovered a bug with Swift 3 while using the Adjust SDK, which can be fixed by adding nullability annotations. The Swift bug is filed [here](https://bugs.swift.org/browse/SR-2767). The following code will work in Swift 2.3, but it will fail in Swift 3:

```
let criteo = ADJCriteo(id: "some_id", price: 1.0, quantity: 1) // Returns an implicitly unwrapped optional, since ADJCriteo.h has no nullability annotations
let str = ADJCriteo.createCriteoVB(from: [criteo])
/*
The above method take [Any]! because there are no nullability annotations.
It then returns nil because of the mentioned Swift bug.
When this class method checks what kind of class the criteo object is, it returns _SwiftValue, which causes this to fail
*/
```

This can be easily prevented from happening by adding nullability annotations to ADJCriteo.h. It'll also generally make this SDK more friendly for Swift users 😊.

Currently, the easy workaround is to just explicitly unwrap the `ADJCriteo` object upon creation with a `!`.

**Comment by benasher44** [comment]
Because the Adjust SDK doesn't have nullability annotations, this class of bugs could happen in many more scenarios, but this is the one that I've experienced so far.

**Comment by uerceg** [comment]
Hi @benasher44 

Thanks for reporting this! We will try to add this in our next update. 👍 

Cheers

**Comment by benasher44** [comment]
Thanks!

**Comment by AppsTitude** [comment]
Hey guys! Could we please have an update on that?

**Comment by uerceg** [comment]
Hey @AppsTitude 

Sorry for delay in answer. We didn't add this in our 4.11.0, but we are planning to add it to our next patch version (probably 4.11.1). No exact ETA on it, though, but it is in our roadmap.

Cheers

**Comment by AppsTitude** [comment]
Ok thx

**Comment by uerceg** [comment]
Hi @benasher44 @AppsTitude 

Can you please share some code example you're using in your app which generates this issue except the one from the entry post?

Thanks in advance.

**Comment by benasher44** [comment]
Is the provided sample code not sufficient? Can you be specific as to what would be an improvement over the sample code that has already been provided?

**Comment by uerceg** [comment]
You named that example, I just wanted to check if you maybe encountered this issue with the SDK in other situations in the meantime and just to test those other scenarios to see if the fixes will successfully resolve them as well.

**Comment by benasher44** [comment]
That's the only example I remember encountering directly. Finding more would require auditing the SDK public headers for those that are missing nulllability annotations or missing type annotiaons for collections (i.e. NSArray instead of NSArray<Type *>). Fixing and cleaning up those would be sufficient to trigger warnings in people's projects and prevent this kind of bug.

**Comment by uerceg** [comment]
Hi @benasher44 

We are getting close to v4.11.1 release which will contain Swift annotations. One question I wanted to ask you. I have built dummy Swift app where I included our SDK and Criteo plugin files and now I am looking at your code you explained above:

```swift
let criteo = ADJCriteo(id: "some_id", price: 1.0, quantity: 1) // Returns an implicitly unwrapped optional, since ADJCriteo.h has no nullability annotations
let str = ADJCriteo.createCriteoVB(from: [criteo])
```

This does not even compile for me. First of all, constructor you are using in first line does not exist on `ADJCriteo` class, but rather on `ADJCriteoProduct`, right?

And I can not invoke `createCriteoVB` method, since it's part of Obj-C `.m` file (https://github.com/adjust/ios_sdk/blob/master/plugin/Criteo/ADJCriteo.m#L231) and not public header.

How does the code from above work for you? Can you explain me maybe to set it up and test if I can encounter this particular issue now once annotations are added to the SDK?

Thank you in advance.

**Comment by benasher44** [comment]
Ah yep apologies. I meant that to be `ADJCriteoProduct(id:…`.

For the 2nd line, I was just illustrating the method where things fell apart. It falls apart in that method, but we were getting there by calling (in Swift):

```
+ (void)injectTransactionConfirmedIntoEvent:(ADJEvent *)event
                                   products:(NSArray *)products
                              transactionId:(NSString *)transactionId
                                newCustomer:(NSString *)newCustomer
```
Does that clear things some? Sorry for the somewhat fuzzy initial code example.

**Comment by uerceg** [comment]
Hi @benasher44 

And thanks for the update. Any chance that you might find some time to try edited version of `ADJCriteo` plugin to check if it fits your expectations? You can find it in here: https://github.com/adjust/ios_sdk/tree/v4111/plugin/Criteo

I initialised `ADJCriteoProduct` with code you provided earlier and also executed `injectTransactionConfirmedIntoEvent:products:transactionId:newCustomer:` method without compile/run time errors/warnings.

Looking forward to hear from you soon.

Cheers

**Comment by benasher44** [comment]
Looks good! thanks!!

**Comment by uerceg** [comment]
Added to v4.11.1: https://github.com/adjust/ios_sdk/releases/tag/v4.11.1

Cheers.
