### ISSUE TITLE
Cannot submit build with Xcode 8 (Swift 3) and Carthage

### ISSUE THREAD

**Issue by patricks** [adjust/ios_sdk#249]
I currently try to release a new version of our app. But I get the following error:

![adjust-problem](https://cloud.githubusercontent.com/assets/132167/19037185/3fa320f2-8975-11e6-98aa-1259802effe1.png)

Any ideas how to fix this problem?

**Comment by patricks** [comment]
It looks like the minimum iOS value should be >= 8.0. Maybe this is because Swift 3.0 requires iOS >= 8.0

**Comment by uerceg** [comment]
Hi @patricks 

Thanks for reporting this, seems like that's the reason. Will investigate this and update you ASAP.

Cheers

**Comment by nonelse** [comment]
Should be fixed with the [v4.10.2](https://github.com/adjust/ios_sdk/releases/tag/v4.10.2)

**Comment by uerceg** [comment]
Hi @patricks 

Any update on this issue? Did latest version managed to fix your issue?

Cheers

**Comment by patricks** [comment]
Hi, thanks this fixed my problem.

**Comment by uerceg** [comment]
:+1:
