### ISSUE TITLE
The value of adjFbAttributionId is always empty.

### ISSUE THREAD

**Issue by AlexTatarinchik** [adjust/ios_sdk#250]
The macro "defined (TARGET_OS_TV)" is preprocessed like TRUE even without TVOS environment.
The method adjFbAttributionId of category ADJAdditions always returns empty string value.
TARGET_OS_TV is 0 value.

Xcode Version 8.0 (8A218a)
Cocoapods 1.0.1
Integration via Cocoapods
pod 'Adjust', '4.10.2'

**Comment by nonelse** [comment]
Yes, the use of the `TARGET_OS_TV` preprocessor variable is correct in the rest of the file, changing the same line to `#if ADJUST_NO_UIPASTEBOARD || TARGET_OS_TV` should resolve the issue.
It will be fixed in the next release, thanks!

**Comment by uerceg** [comment]
Fixed in 4.11.0. https://github.com/adjust/ios_sdk/releases/tag/v4.11.0

One more time, thanks for the suggestion!

Cheers
