### ISSUE TITLE
Leave SDK version in Adjust.h file

### ISSUE THREAD

**Issue by philippb** [adjust/ios_sdk#251]
Add the SDK version number to the Adjust.h file so it's easy to see what version is currently in code.

**Comment by uerceg** [comment]
Hi @philippb 

Thanks for suggestion, good one. Will add the comment with this info starting from next update. 👍 

Cheers

**Comment by nonelse** [comment]
Included in [v4.10.3](https://github.com/adjust/ios_sdk/releases/tag/v4.10.3) release
