### ISSUE TITLE
Install event not being tracked

### ISSUE THREAD

**Issue by fcamaster** [adjust/ios_sdk#253]
Hi, 

We're trying to see the installs from our app within Adjust platform, but after trying it for several days we haven't been able to see them. 
Some events like "sessions" are being tracked.

We have try https://github.com/adjust/ios_sdk#im-seeing-the-session-failed-ignoring-too-frequent-session-error
and https://github.com/adjust/ios_sdk#im-not-seeing-install-tracked-in-the-logs 

But the thing is that we are not even able to see the "Install tracked" event on the console nor the 
"Session failed (Ignoring too frequent session."
We have also monitor the calls to see if Adjust is sending the install event and it seems that is not being sent. (I think it was called "startup")

These are the only logs that Adjust prints in the console: 

```
2016-10-27 15:38:31.802   [566:52865] 	[Adjust]a: PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
2016-10-27 15:38:31.802   [566:52865] 	[Adjust]d: Delegate implements adjustAttributionChanged:
```

We've try this in both sandbox and production and with different app ids, as we have different apps, but the result is the same.

Can you help us out with this?
Thanks in advance.

**Comment by uerceg** [comment]
Hi @fcamaster 

Couple of things:

1. Feel free to use sandbox while testing, just not to mix your testing traffic with the one which is being produced with your official released app installs.
2. When in sandbox, turn adjust SDK log level to verbose to see all the infos which are displayed in the logs. For now, I would advise you to run your all with this setup (sandbox environment and verbose log level turned on) and track one event (for example) with your app. Once event is tracked, check all the parameters which are being sent to our backend with that event and you will see `idfa` parameter of your device.
3. Uninstall the app from your device (completely remove it, don't reinstall it).
4. Go to your web browser and load this URL: http://app.adjust.com/forget_device?app_token={yourAppToken}&idfa={idfaValue} where you need to put in your app token and IDFA value (of course, without curly brackets). If your device is successfully forgotten you will see message `Forgot device` and if not (our backend doesn't have info about it) you will see message `Device not found`.
5. After this is done install your app on the device and run it. Once our SDK is started, you should see in the logs that install has been tracked.

Give it a try and lemme know if you need further assistance with this.

Cheers

**Comment by fcamaster** [comment]
Hi @uerceg

We've been also testing with Sandbox mode, but we just wanted to check that the installs were being tracked.

For sandbox mode, with Verbose Log enabled I am able to see the "Install tracked" log.
I've being trying by forgetting the device from your backend while testing all this, but no luck with that for production as for sandbox. I get the "Forgot device" message, and if I call that url again I get "Device not found" which means that it worked.

I'll try to explain the scenario I performed:

1- Remove the app
2- Forget the device from Adjust backend (Checking that the device has being forgotten)
3- Install the app again 

By monitoring the calls for those scenarios:
Adjust SDK pointing to Production:
I get the session event like this:
{
	"app_token": "{app-token}",
	"adid": "{adid}",
	"attribution": {
		"tracker_token": "mtasaq",
		"tracker_name": "Organic",
		"network": "Organic"
	},
	"ask_in": 2000
}

and for the Sandbox version:
{
	"app_token": "{app-token}",
	"adid": "{adid}",
	"timestamp": "2016-10-27T14:01:31.676Z+0000",
	"message": "Install tracked",
	"attribution": {
		"tracker_token": "mtasaq",
		"tracker_name": "Organic",
		"network": "Organic"
	},
	"ask_in": 2000
}

Which, I would think might be normal because of the environment used for this, so the response doesn't need to be the same.
But the thing is that in Adjust Dashboard for that application I cannot see the install logs from those we performed yesterday or those we performed today, while I can see that sessions are being tracked properly.

We also tried with another app that doesn't have traffic at all, so we should have seen some Install events there, but we haven't been able to see them. 


Sorry I didn't wrote with "code" block, but it seems that the text display in line, which is not as readable.

**Comment by uerceg** [comment]
Okay, I don't think I quite understood what's happening. Are you saying that when you test scenario from above in sandbox environment you're seeing the message that install got tracked and for production mode you don't?

Did you try to implement `adjustSessionTrackingSucceeded` callback (https://github.com/adjust/ios_sdk#event-session-callbacks) ? In here, you can get info about the message in your app and check it's content.

Can you implement this callback and retry the whole scenario with environment set to production and lemme know what is the message content?

**Comment by fcamaster** [comment]
Yes, here it is the response from a fresh start (Device forgotten and app installed):

2016-10-27 17:04:18.466065  [480:42750] [INFO] -[AppDelegate adjustSessionTrackingSucceeded:]-302 Session Success msg:(null) time:(null) adid:41029cb27d389e9d7dbaa3273e31d156 json:{
    adid = 41029cb27d389e9d7dbaa3273e31d156;
    "app_token" = {app_token};
    "ask_in" = 2000;
    attribution =     {
        network = Organic;
        "tracker_name" = Organic;
        "tracker_token" = mtasaq;
    };
}

**Comment by uerceg** [comment]
Ah okay, right. Sorry for delay in my thoughts. When in production, our backend doesn't send us the messages in the responses, just while in sandbox. That's why you don't see the message that install got tracked, but still - the scenario I described above (about repeating the same scenario and waiting a bit until install appears in your production traffic in the dashboard) should also work just fine.

**Comment by fcamaster** [comment]
Ok, thanks @uerceg for confirming that. 
With those steps we checked that events are being tracked after a while.

Thank you so much!

**Comment by thuannhanACM** [comment]
Hi guys, i'm facing this issue in iOS (i'm using unity package - for both android and iOS impementation). 
In my app, the install event not tracked with the iOS build which submitted to app store (environment: Production, LogLevel: Suppress)...noted that sandbox worked, and the android build production worked too.
I already have a build with same defines as the app store build,, same adjust environment, log level...and this build tracked install event as well.
could not figure out the reason till now, please give me some insights on what could be wrong?

**Comment by Kushagra79** [comment]
> Hi guys, i'm facing this issue in iOS (i'm using unity package - for both android and iOS impementation). In my app, the install event not tracked with the iOS build which submitted to app store (environment: Production, LogLevel: Suppress)...noted that sandbox worked, and the android build production worked too. I already have a build with same defines as the app store build,, same adjust environment, log level...and this build tracked install event as well. could not figure out the reason till now, please give me some insights on what could be wrong?

same issue, was it resolved?
If yes, then how was it solved?
