### ISSUE TITLE
Use of Adjust in iMessage extension - UIApplication

### ISSUE THREAD

**Issue by helkarli** [adjust/ios_sdk#254]
I am trying to track events with Adjust in an iMessage extension, but can't use Adjust for the iMessage extension target. The following error appears: 

'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead. 

Can I use adjust in an extension and how?

**Comment by nonelse** [comment]
hello @helkarli, when iMessage extensions appeared, we tested our sdk with some success.
We'll revisit it in the next release, where we'll include an example app if it's possible

**Comment by mxcl** [comment]
My client wants to use Adjust in an extension, is this ticket still valid?

**Comment by uerceg** [comment]
Hi @mxcl,

It is in our TODO queue, higher prio things at this moment in there (upcoming SDK update), but after SDK is updated we will focus on this and probably add an example extension app in our repository with example how our SDK can be used in there. 

Will keep you posted in here. 

Cheers

**Comment by RTodorov** [comment]
Hello there, any news on this field? This ticket is from Nov 2016! Can we use adjust on the Today's widget for example?

**Comment by uerceg** [comment]
Hi @RTodorov 

Yeah, we had a bit of rough roadmap lately and we didn't really find time for this feature. But we have it in our list and hopefully will be able to start working on them soon. No exact ETA on this yet.

**Comment by uerceg** [comment]
Hey guys. We have just released iOS SDK v4.14.2 update (https://github.com/adjust/ios_sdk/releases/tag/v4.14.2) where you should be able to have support for `iMessage` target. Will close this issue now, but feel free to reopen it or ping in here in case you have any issues or further questions.

Cheers.
