### ISSUE TITLE
No logs in iOS 10

### ISSUE THREAD

**Issue by peacemoon** [adjust/ios_sdk#258]
I set adjustConfig.logLevel = ADJLogLevelVerbose but see nothing Xcode. I think it relates to problems with NSLog in iOS10.

**Comment by uerceg** [comment]
Hi @peacemoon 

Which environment variable do you have set up when initialising`ADJConfig` object? Are you running you app directly from the Xcode and checking logs in log output of the Xcode IDE or are you checking the logs of your device in `Device` window of the Xcode?

Cheers

**Comment by peacemoon** [comment]
I'm running it in Debug mode and directly from xcode. I can see lots of Adjust logs in Xcode when running on real devices with iOS 9.3.5, but on devices with iOS 10.0.2 & 10.1.1, I see nothing in Xcode logs

**Comment by uerceg** [comment]
Regarding environment I was aiming to get info whether you're using the adjust SDK `sandbox` environment and not the `production` one, but I guess you're using `sandbox`.

That's interesting. Which Xcode version are you using?

I am having `Xcode Version 8.1 (8B62)` and testing an example app with the SDK inside (sandbox environment and verbose log level) and I am able to see all the log output from the adjust SDK.

**Comment by peacemoon** [comment]
``
            let environment: String
            #if DEBUG
                environment = ADJEnvironmentSandbox
            #else
                environment = ADJEnvironmentProduction
            #endif

            let adjustConfig = ADJConfig(appToken: TargetConfiguration.AdjustAppToken, environment: environment)
            #if DEBUG
                adjustConfig.logLevel = ADJLogLevelVerbose
            #else
                adjustConfig.logLevel = ADJLogLevelAssert
            #endif

            adjustConfig.delegate = self

            Adjust.appDidLaunch(adjustConfig)
``

I use `sandbox` environment and also have Xcode 8.1 (8B62). Do you see the logs also in iOS 10 device?

**Comment by uerceg** [comment]
Ah, yeah, sorry, forgot to mention, yes. Xcode 8.1 with iOS 10.1.1 device. I can see all the logs. Hm. 🤔

**Comment by peacemoon** [comment]
Huhm ok, I made a quick search in Google and found this: http://stackoverflow.com/a/39503602/452115. It's a bug in Xcode8 & iOS 10 :( . Sorry for confusion. I should have searched google before asking here.

**Comment by uerceg** [comment]
No problemo. Btw, if you manage to solve this somehow, would be great if you can post a solution in here as well.

**Comment by peacemoon** [comment]
Summary: this is a bug of Xcode8 + iOS10, we can solve it in this way:

Open in Xcode8:

`Product -> Scheme -> Edit Scheme -> Run -> Arguments -> Environment Variables`

When on sumulator, add the Name "OS_ACTIVITY_MODE" and the Value "disable" and check it. When on device, only add "OS_ACTIVITY_MODE" and check it（Don't add the Value）. You will see the NSLog in the Xcode8 Console.

Credit: http://stackoverflow.com/a/39503602/452115

**Comment by uerceg** [comment]
Good news!

I guess we can close this issue now.
