### ISSUE TITLE
Randomly moving to AppStore and url convertation

### ISSUE THREAD

**Issue by ihorzabrotsky** [adjust/ios_sdk#261]
Hello!
Currently I'm testing deep linking on iPhone 5c with iOS 9.3.5 and on iPhone 7 with iOS 10.0.2 and sometimes I am moved to the AppStore. Here's my `continueUserActivity` implementation:

`- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    if ([[userActivity activityType] isEqualToString:NSUserActivityTypeBrowsingWeb]) {`

       NSURL *url = [userActivity webpageURL]; 
        NSURL *oldStyleDeeplink = [Adjust convertUniversalLink:url scheme:@"myapp"];
        NSLog(@"url: %@", url);
        NSLog(@"oldStyleDeeplink: %@", oldStyleDeeplink);
        [Adjust appWillOpenUrl:url];
    }
    return YES;
 `}`

1. When I click on [https://xxxx.adj.st/](url) link I am redirected to the app and the method above is triggered.
2. When I click on [https://app.adjust.com/...](url) I am always redirected to the AppStore and the method above is never triggered.
3. When I click on the shared link from my app which I receive from the backend and it looks like [https://myapp/x/xxxx](url) sometimes I am redirected to the app and sometimes to the AppStore. Also, in this case when trying to convert the url using `+ (NSURL *)convertUniversalLink:(NSURL *)url scheme:(NSString *)scheme` I get en error "Url doesn't match as universal link or short version". Does this mean that the link of this type is bad and I have to work only with links described above? Should I just convert somehow this link to the short universal link, for example?

**Comment by uerceg** [comment]
Hi @ihorzabrotsky 

1. Seems good.
2. Doesn't seem good. :) Can you please give me the links you're using in 1 and 2? Feel free to omit any sensitive stuff like tracker token or maybe something from your deep link.
3. I am not really sure where does this format come from https://myapp/x/xxx? How are you making this `click` on that kind of URL from your app which you're getting from your backend?

Error you're getting with the `convertUniversalLink::` method is probably because the link you're trying to convert is not matching format of the universal link which our SDK is expecting and that's either https://github.com/adjust/ios_sdk/blob/ec223b61dd1bd8f88d25250e539be73fbca20251/Adjust/ADJUtil.m#L35 or https://github.com/adjust/ios_sdk/blob/ec223b61dd1bd8f88d25250e539be73fbca20251/Adjust/ADJUtil.m#L36

How does the link look like which you're trying to convert when getting this error message?

Cheers

**Comment by ihorzabrotsky** [comment]
Hi @uerceg !
Concerning 2: the link looks like one of 2 standard links for testing from [test links](https://docs.adjust.com/en/universal-links/#testing-universal-link-implementations):
https://app.adjust.com/xxxxxx?deep_link=myapp://
where "xxxxxx" - is my tracker and "myapp" is my app deep link prefix.
Concerning 3: As I do understand [here](https://docs.adjust.com/en/universal-links/#running-campaigns-through-universal-links) are those 2 types of links specified and no other links are permitted. Right?
Also, the link I get such error for looks like https://myapp.xxxx.xx/x/xxxx

**Comment by ihorzabrotsky** [comment]
Hi @uerceg !
I have a little UPD on my issue. The case is that I click on https://myapp.xxxx.xx/x/xxxx and then my server redirects me to https://xxxx.adj.st/...
Should it work fine in case of redirection or we need to directly click on the Adjust-base link?

**Comment by uerceg** [comment]
Hi @ihorzabrotsky 

Sorry for delay in answer.

Regarding your **UPD** claim: Older Chrome versions tend not to open the app with the universal link. Newer ones should.

Can you please just update in here what are your current issues and the scenarios in which you are able to reproduce them?

Cheers

**Comment by uerceg** [comment]
Hi @ihorzabrotsky 

Any update on this issue?

**Comment by ihorzabrotsky** [comment]
Hi @uerceg !
Here's the situation: I get a link like [https://myapp/x/xxxx](url) from my server. When I use it in Chrome I am sent to my server and then my server redirects me to [https://app.adjust.com/abcdef?...](url) and then my app is opened on the needed page.
But when I click on my custom link I am redirected to my app and `- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler` is called where I receive the same link. Can I somehow receive the needed Adjust link from my custom link to which my server redirected me in Chrome? Should I use some Adjust methods or I need to perform a call to my server where I get this redirection link?

**Comment by uerceg** [comment]
Hi @ihorzabrotsky 

And sorry for delay in answering. Did you manage to solve this issue? If you are still having issues with it, let me know and I will ping someone from our backend team to get involved in here, since this is more their area of work.

Cheers

**Comment by uerceg** [comment]
@ihorzabrotsky 

Feel free to reopen the issue if you're still facing the problem described above.

Cheers
