### ISSUE TITLE
Deferred deeplink processing problem

### ISSUE THREAD

**Issue by iubondar** [adjust/ios_sdk#265]
Adjust needs to get attribution info in order to process deferred deep link after app install. However, there are cases when ADJAttributionHandler is unable to get that info.
ADJActivityHandler, line 150:
`self.internalState.background = NO;` with comment `// in the background by default`
Due to this default value `ADJAttributionHandler` is being initialized with `self.paused = YES` and `requestAttributionI` returns early.
In that case deferred deep link is processed after app goes background and foreground, after `[ADJActivityHandler applicationDidBecomeActive]` call, but this is not an expected behavior.
I was able to work around this issue by setting `adjustConfig?.sendInBackground = true` (Swift), but it took some time to figure out the cause of a problem.

**Comment by nonelse** [comment]
Hi @iubondar.

The default behaviour of the sdk is to not send network requests if the app is in the background.
We think that this default behaviour makes sense to most apps. It could be surprising for the app to re-open or send requests after being put in the background. Is it the case that your app works differently, expecting activity while being in the background?

In the default behaviour, the sdk will get and open the deferred deeplink when the app is back in the foreground. Was this not your experience?

Thanks for the feedback!

**Comment by iubondar** [comment]
Hi, @nonelse.

I totally agree about background data sending. In cases I face the described issue the app defines it's state incorrectly on first launch. I think the issue is a some kind of data race. However, I was wrong about the cause of the issue (I was confused by comment `// in the background by default` while actual value of `background` property is NO). I can't repeat the issue at the moment so I suggest to close it and reopen if I can provide the actual steps to reproduce.

Thanks for your help.
