### ISSUE TITLE
Failed to verify bitcode in Adhoc builds

### ISSUE THREAD

**Issue by jessemx109** [adjust/ios_sdk#272]
I'm using carthage to build the Adjust framework and when I create an Adhoc build I am getting the Error "Failed to verify bitcode in AdjustSdk.framework/AdjustSdk"

After doing some research I stumbled upon the same issue with the Alamofire framework and they were able to fix it by adding a user defined setting BITCODE_GENERATION_MODE with the value of bitcode to their framework targets. 

Here is their discussion on it
https://github.com/Alamofire/Alamofire/issues/835

Please add that setting so I can create Adhoc builds using your frameworks and not the source itself

**Comment by uerceg** [comment]
@jessemx109 

Sorry for the delay in answering and thanks for letting us know. Next iOS SDK release will contain `BITCODE_GENERATION_MODE` setting in each framework.

Cheers

**Comment by uerceg** [comment]
Added to v4.11.1 (https://github.com/adjust/ios_sdk/releases/tag/v4.11.1).

Feel free to ping if you face any other issues.

Cheers.
