### ISSUE TITLE
Deeplink using traditional Adjust deeplink

### ISSUE THREAD

**Issue by fcamaster** [adjust/ios_sdk#273]
Hi guys,

I have a problem with Universal links on the app.
I've configure both the app and the Adjust dashboard to use Universal links.

I'll try to explain below the scenarios I've tested and the result of them (in the two ways described here https://docs.adjust.com/en/universal-links/#running-campaigns-through-universal-links
) :

1. Using deeplink: https://abcd.adj.st/?adjust_t=abc123 
    - App installed: The app is directly opened 
    - App not installed: Open App Store.
Scenario 1 is working as expected.

2. Using the tradicional Adjust deeplink (https://docs.adjust.com/en/universal-links/#universal-links-and-deep-link-parameters-within-adjust-trackers)   https://app.adjust.com/tr4ck1ng1d?deep_link=myapp://promotion:
    - App Not Installed: Open the app store page. Deferred deep link works fine.
    - App Installed: Open the app store page. (_**should open directly the app**_).

I also tried by encoding the deep_link parameter and by clicking on the link from Mail, Notes app, Messages and none of these worked when the app is installed. It always redirects to the app store.

By looking at the table on the documentation I can see which are the recommended approach for every method. 

Note: If I paste the url directly on chrome it will act as a deep link to an URI, (prior to iOS 9) asking the user if he/she wants to open the app (continueUserActivity is not called). By clicking Open the app is opened and the deferred deep link works fine.
Tested using iOS 9.3.1 and iOS 10.1.

I have also checked some other issues: https://github.com/adjust/ios_sdk/issues/153
So, if I understood correctly, depending on the method we're using to target the users, the links have to be built one way or another. Haven't they?, however our app still supports iOS 8, so I guess we should always use the traditional deep link parameter.

Our main focus will be targeting by Facebook, so deep link parameters should be used, however, how can I test this?
If I run a campaign through email, the users won't be able to open the offer unless they specifically click on the link in Safari or **Universal Links** is used to create the campaign (which again, leads me to the question below).

As specified here (https://docs.adjust.com/en/universal-links/#universal-links-and-deep-link-parameters-within-adjust-trackers), "Adjust will recognise if Universal Links should be used", but 
does it works upside down? If using Universal Link, will the app still be opened on iOS 8 by using the normal scheme approach?

Is there a way of only using one of the methods above to make it work for all iOS versions?

Thanks.

**Comment by uerceg** [comment]
Hi @fcamaster 

And thanks for detailed issue description.

First, I would like to check you scenario 2. You have said that when using traditional adjust tracking URL and once your app is installed, hitting that link redirects you to the store and doesn't open the app (which should happen, of course).

Where are you clicking on the URL? Is it hosted on some web page which you are opening from your mobile browser and clicking on it or are you just pasting the URL to the URL bar? Which browser are you using? Which iOS version does your test device have?

Cheers

**Comment by fcamaster** [comment]
Hi @uerceg 

I've tested that with iOS 9.3.1 and iOS 10.1

I've tried by clicking on Mail, Notes and pasting directly on Safari. - All of these redirected to the App Store
I've also tried pasting the link on Chrome, which act as a deep link to an URI. It works from Chrome after the user clicks on "Open".

**Comment by erikvillegas** [comment]
I also ran into this issue. The only way I could get it working was when the link was already embedded in a webpage. I set up a simple webpage that had a button that when clicked, opened the https://app.adjust.com/tr4ck1ng1d link. At that point, when Adjust redirects to the app's universal link, iOS opens up the app. But as you described, if the link was tapped on outside of Safari (like in Mail or Notes) it will not trigger the universal link to open.

I'm not sure if this is a bug or just how Apple intended it to work.

**Comment by fcamaster** [comment]
Thanks @erikvillegas for you comment. I'll try with that.

**Comment by uerceg** [comment]
Hi @fcamaster,

Any update on this issue?

**Comment by fcamaster** [comment]
@uerceg Sorry for the late reply.
It is working as Erik commented, thanks

**Comment by uerceg** [comment]
Lovely. Thanks for the update! 🍺

**Comment by tawhidkuet04** [comment]
I attempted to send this message through Slack, and it was successful. However, I encountered issues when using Messenger, Chrome, and Safari. It's quite peculiar.

**Comment by uerceg** [comment]
Hi @tawhidkuet04,

If you are willing, please feel free to send the specific deep link you are trying to use in those scenarios and what exactly you are attempting to do on support@adjust.com and someone from support team more knowledgable on this topic will try to help you with this.
