### ISSUE TITLE
iOS 10.3 keychain workaround

### ISSUE THREAD

**Issue by erikvillegas** [adjust/ios_sdk#278]
Hello, regarding the [upcoming changes to the keychain in iOS 10.3](https://forums.developer.apple.com/thread/72271), I noticed the use of `kSecAttrAccessGroupToken` as a workaround. Do you know if this is specifically allowed by Apple, and if they'll continue to support this?

Also, according to the docs values stored with this access group are available to _all_ apps. Is there any security concerns regarding other apps reading/writing this value?

**Comment by nonelse** [comment]
hi @erikvillegas, thanks for the warning.
this behaviour was not expected, but we have figured out that it will still work and did not have issues with the app submission process.
we will look into updating it to take that into consideration soon

**Comment by erikvillegas** [comment]
Sounds good, thanks!
