### ISSUE TITLE
`eventBufferingEnabled` causes deferred deeplinks to be delayed

### ISSUE THREAD

**Issue by lozhuf** [adjust/ios_sdk#281]
I was having lots of trouble getting deferred deep links to work correctly, until stumbling across a solution by accident. Here are my steps:

1) Reset device. Remove app from device. Forget device with the "https://app.adjust.com/forget_device" link. 
2) Open url (https://app.adjust.com/abc123?deep_link=foo://bar) on device. This opens the appstore page for our app, as expected.
3) Install app. Tap 'Open' once installed. App opens, but deeplink is not followed.
4) Leave the app open on the device, and after about 1 to 3 minutes it suddenly reacts and the deeplink is opened.

I was seeing this 1-3 minute delay only in the release build - the debug build from Xcode opens the deeplink almost instantly. The only difference between release & debug is that in release "eventBufferingEnabled = true" and environment is Production rather than Sandbox. 

When I tried enabling eventBuffering in the debug build it also took 1 minute for the deeplink to open. 

This seems like a very strange choice - this seems to be a bug from my perspective (attribution doesnt seem like it should be tied to event handling). At the very least this should be documented in the code.

This is using the AdjustSDK v4.11.0 (CocoaPods), on an iPhone 7 running iOS 10.2.1.

**Comment by uerceg** [comment]
Hi @lozhuf 

Thanks for reporting this. Indeed, this is like you described it and it is environment agnostic. It is the result of the behaviour of event buffering which, if enabled, buffers all sessions and events in the SDK for a minute and then sends them. This is how event buffering always behaved even before deferred deep linking support.

Deferred deep link will not arrive from our backend unless it tracks an install and gets info that app is installed at first place on the device. But event buffering will postpone this for a minute and this is the reason you are seeing this behaviour.

This is something we have internally discussed and event buffering behaviour will most probably be changed in upcoming releases to prevent things like this happening even if this feature is switched on.

For the moment, no exact ETA on this, but it is on our roadmap and I will keep you informed on the progress on this issue in here.

Cheers

**Comment by lozhuf** [comment]
Hi @uerceg
Thanks for the quick response. I assumed it must have been something along the lines of as you described. This seems like rather peculiar choice of behaviour, but I understand that decisions need to be made based on existing architecture. However, at the very least this should really be documented in code more clearly. The current comment does not describe this behaviour at all, making it seem entirely related to event tracking:
``` 
// Enable event buffering if your app triggers a lot of events. 
// When enabled, events get buffered and only get tracked each minute. 
// Buffered events are still persisted, of course
```
I spent an entire day investigating why my deferred deeplinks were not opening in the app - it was only by luck & chance that I left the app sitting open for 60secs and saw activity. I hope this GH issue is a help to anyone else that has been burnt by this.

Thanks again for your swift response on GH.
Cheers

**Comment by uerceg** [comment]
Hi @lozhuf 

Thanks for pointing that out as well, indeed, comment should be more descriptive in terms of explaining that it doesn't refer only to events but sessions as well (back then probably event was classified like everything that happens in app which is about to be tracked).

If we don't change this behaviour in next release, at least this comment will be updated, but we'll give our best that this change also becomes part of next release.

Thanks one more time for your observations.

Cheers

**Comment by uerceg** [comment]
Hi @lozhuf 

Quick update on this one: As of upcoming release (4.12.0), we will give deferred deep link advantage in this case (since at the end of the day UI interaction with your users is most important), so event buffering will not buffer first session ever (install) whose tracking will result in deferred deep link being delivered into your app. So, even with event buffering turned on, deferred deep linking flow will be untouched and behave as normally expected.

Will update you in here once update is live.

**Comment by uerceg** [comment]
Hi @lozhuf 

This should not be the case anymore with newest iOS SDK v4.12.0 (https://github.com/adjust/android_sdk/releases/tag/v4.12.0).

Please feel free to reopen the issue if you encounter this issue with this SDK version.

Cheers.
