### ISSUE TITLE
Importing Adjust in the Bridging header if installed via Cocoapods

### ISSUE THREAD

**Issue by brototyp** [adjust/ios_sdk#284]
I had no success importing Adjust in the Bridging header via `#import "Adjust"` or `#import <Adjust/Adjust.h>`. Importing it via `@import Adjust;` works though.

I am Using Xcode 8.3.2 and Cocoapods 1.2.1.

**Comment by uerceg** [comment]
Hi @brototyp 

Hm. I am using exact same versions of Xcode and Cocoapods and after adding Adjust SDK to the app via Cocoapods, `#import "Adjust.h"` worked just fine for me.

I see that you said above that you tried `#import "Adjust"`. Did you maybe missed `.h` in the include statement?

**Comment by brototyp** [comment]
Hi @uerceg,

the missing `.h` was just an issue here in the ticket. I attached a test case that displays the issue I am experiencing. Just try to build the project and you will get an error regarding a not defined symbol.

[Adjust Testcase.zip](https://github.com/adjust/ios_sdk/files/958363/Adjust.Testcase.zip)

**Comment by uerceg** [comment]
Aha, you are using Swift. Will check and get back to you soon.

**Comment by uerceg** [comment]
@brototyp 

Okay, this is everything you need to read: http://stackoverflow.com/a/31885253/1498352

I have tried both approaches with Swift:

1. `Podfile` containing `use_frameworks!` directive.
2. `Podfile` not containing `use_frameworks!` directive.

In 1st case (which is your case from this example app), you don't need bridging header file, the only thing you need to do is to import Adjust SDK to your `AppDelegate.swift` like this:

```swift
import Adjust
```

and that's it.

In 2nd case (if you're using Adjust SDK from Pods not as framework, but source files), you need bridging header with this import statement:

```objc
#import "Adjust.h"
```

Give it a try and lemme know if it worked for you.

**Comment by brototyp** [comment]
That works perfectly and is what we were using. Maybe you can add another "If you are using cocoapods with swift ..." comment in the Getting started documentation. That could save others some time.
Thanks for digging in!

**Comment by uerceg** [comment]
Yep, definitely. Thank you for opening this issue, our official README will be updated with this use case as well.

Cheers!
