### ISSUE TITLE
Redirected Universal Link in Mail/Messages

### ISSUE THREAD

**Issue by gngrwzrdsb** [adjust/ios_sdk#287]
Looking at this ticket #153. Was there ever a solution for this?

I've tried using your recommendation by building a universal link according to these docs https://docs.adjust.com/en/universal-links/#building-your-direct-universal-links

But clicking them from mail or messages, or anywhere other than Safari doesn't open the app if I have it installed.

**Comment by uerceg** [comment]
@gngrwzrdsb 

Can you share in here how does your universal link look like that you are trying with Mail/Messages app? Feel free to change anything from the URL you think that is sensitive with some dummy values.

Thanks in advance.

**Comment by uerceg** [comment]
@gngrwzrdsb 

Any update on this one?

**Comment by uerceg** [comment]
@gngrwzrdsb 

Feel free to reopen the issue if the problem still persists.

Cheers
