### ISSUE TITLE
dyld: Library not loaded: AdjustSdk.framework

### ISSUE THREAD

**Issue by SoftwareEngieer** [adjust/ios_sdk#292]
I have get buid error after adding Adjust sdk framework to my project. 

Error like below:

_dyld: Library not loaded: @rpath/AdjustSdk.framework/AdjustSdk
  Referenced from: /var/containers/Bundle/Application/ADB9806B-4B6F-4EEE-88CC-BC66DA8207D3/LCWaikiki.app/LCWaikiki
  Reason: image not found_

**Comment by SoftwareEngieer** [comment]
**For solution i followed the steps below:**

- _Add the AdjustSDK.framework to the "Embedded Binaries" section of the "General" tab of the Xcode project settings._

- Close Xcode

- Delete derived data
        Open Terminal and enter below command:
                   rm -rf ~/Library/Developer/Xcode/DerivedData

- Clean project

- Rebuild

**Comment by gerchicov-bp** [comment]
@SoftwareEngieer I have the same issue with cocoapods in xcode 10. Cleaned, reinstalled cocoapods and etc. The bug is stable each even run

**Comment by josipbernat** [comment]
Same thing happens to me when I use Adjust with Cocoapods on Xcode 10.
