### ISSUE TITLE
Random crashes in dictionary enumeration

### ISSUE THREAD

**Issue by ilyapuchka** [adjust/ios_sdk#294]
Random crashes happen in `[ADJUtil convertDictionaryValues]` trying to mutated dictionary while enumerating it on a different thread.
<img width="539" alt="screen shot 2017-06-23 at 15 30 29" src="https://user-images.githubusercontent.com/1488293/27484719-91a5d99c-582a-11e7-9b52-f7c98d489c92.png">

SDK version 4.11.0, commit sha 2f18ea1f01c06a78de8b8cda8d0fbe560492f11a

**Comment by ilyapuchka** [comment]
@uerceg unfortunately it's still crashing after update

**Comment by ilyapuchka** [comment]
@uerceg any chance this will be addressed any time soon. That's pretty annoying bug.

**Comment by ilyapuchka** [comment]
Is there guaranty this happens only on simulator in debug?

**Comment by uerceg** [comment]
@ilyapuchka We are working on iOS SDK v4.11.5 update and will try to consider this to be part of the update as well. No ETA though, but should be in next couple of weeks.

Is there any scenario in which you can reproduce this issue?

**Comment by ilyapuchka** [comment]
It should be related to bad network conditions.

**Comment by uerceg** [comment]
Hi @ilyapuchka 

Wanted to follow up on this one. Do you have any information on whether you have seen this issue in latest iOS SDK releases? We were trying to reproduce it, but no luck.

**Comment by uerceg** [comment]
Hi @ilyapuchka 

We tried to address some issues in [latest iOS SDK release](https://github.com/adjust/ios_sdk/releases/tag/v4.21.3) and I think it should hopefully address this issue as well. In case you can give it a shot and let us know if the issue is still there, feel free to comment/reopen the issue.

Cheers
