### ISSUE TITLE
URL not found error

### ISSUE THREAD

**Issue by palneel** [adjust/ios_sdk#296]
Hi,
I recently started using Adjust. I am using it to create universal links using which I can open a specific screen within my ios app. I have set everything up on the adjust dashboard including my universal link which is - pxwq.adj.st 
I have also enabled associated domains in my app like applinks:pxwq.adj.st 
This worked the first time I tried to use universal links but ever since then, whenever I try using the universal link, it says "URL not found" on safari as well as chrome. 
My app is published on the app store but I am currently testing Adjust in debug mode.

Let me know if u need any more info.

**Comment by uerceg** [comment]
@palneel 

Did you maybe press back button in upper right status bar corner at some point which had back arrow icon and `adj.st` next to it at some point? If you did, this is causing universal link URL to be broken.

Workaround to use the same link again might be to long press it, and choose `Open with <YOURAPP>`. After that, your app should launch and every next attempt to click on that link while your app is installed should result in app being opened.

Alternative is to create tracker in Adjust dashboard for testing and to append `adjust_t=abc123` (where `abc123` is your tracker token) to this short universal link. With tracker info appended to it, app should open.

Lemme know if it worked for you.

Cheers

**Comment by uerceg** [comment]
Hi @palneel 

Any update on this one?

**Comment by uerceg** [comment]
@palneel 

Feel free to reopen the issue if the problem still persists.

Cheers
