### ISSUE TITLE
nullability warnings in criteo branch

### ISSUE THREAD

**Issue by geme** [adjust/ios_sdk#300]
Please add a nullability type specifier to 2 methods.

Branch: "criteo"
XCode: 8.3.3
Swift: 3.1
Dependency Manager: Carthage

File: ADJCriteo.h

Methods: 
+ (void)injectUserSegmentIntoCriteoEvents:(NSString *)userSegment;
+ (void)injectCustomerIdIntoCriteoEvents:(NSString *)customerId;

Warning:
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

**Comment by uerceg** [comment]
Hi @geme 

Nice catch. There rather seem to be two duplicated declarations of those methods:

- https://github.com/adjust/ios_sdk/blob/criteo/Adjust/Criteo/ADJCriteo.h#L31 and https://github.com/adjust/ios_sdk/blob/criteo/Adjust/Criteo/ADJCriteo.h#L64
- https://github.com/adjust/ios_sdk/blob/criteo/Adjust/Criteo/ADJCriteo.h#L35 and https://github.com/adjust/ios_sdk/blob/criteo/Adjust/Criteo/ADJCriteo.h#L62

We'll update the header file and remove duplicated methods w/o nullability checks from there.

**Comment by uerceg** [comment]
@geme 

Can you retry and see if the warnings are still out there?

**Comment by geme** [comment]
everything is fine now, thanks a lot :)

**Comment by uerceg** [comment]
Great. 👍  Thanks for the update.
