### ISSUE TITLE
"app_version" column sends "Build version"

### ISSUE THREAD

**Issue by MasaYanagida-every** [adjust/ios_sdk#304]
Adjust iOS SDK seems to send "Build version" as "app_version" column.
Adjust Android SDK sends app_version correctly.
Is it a bug??

**Comment by uerceg** [comment]
Hi @MasaYanagida-every 

Maybe naming of the parameter itself we're sending to backend might sound a bit misleading, but it is not a bug.

`app_version` in iOS is what `CFBundleVersion` gives back to you.
`app_version_short` in iOS is what `CFBundleShortVersionString` gives back to you.

I guess that app version you are looking for in iOS would in this case be `app_version_short`.

**Comment by MasaYanagida-every** [comment]
@uerceg 
Thanks!! :) 👍
