### ISSUE TITLE
Calling Adjust methods from a background thread

### ISSUE THREAD

**Issue by asalom** [adjust/ios_sdk#309]
Hi,

We are having some issues with the SDK tracking sales with Smartlys, the tracking shows as organic instead of sales.
I would like to know if the following methods can be called from a background thread.
`adjust.trackEvent(event)`
`adjust.appDidLaunch(configuration)`
`Adjust.getInstance()`
`ADJConfig(appToken: "token", environment: environment, allowSuppressLogLevel: true)`

Thanks,
Alex.

**Comment by Obaied** [comment]
Hey @asalom 
All our networking and IO are being handled in background threads. If this is not an issue with the SDK itself, please feel free to shoot an email to support@adjust.com to help you out with the tracking results.

**Comment by asalom** [comment]
Thanks for your reply. We already did that and everything seems fine in the Dashboard. Is it also fine to call `appDidLaunch` from the background thread? That will mean that it will be called from outside `application:didFinishLaunchingWithOptions`

**Comment by uerceg** [comment]
@asalom 

It is up to you to decide where to call `appDidLaunch` method. Regardless of where do you call it (background or UI thread), we do our processing in the background and are not blocking UI thread.

We strongly advise you to follow the README instructions and initialise SDK as soon as possible (aka in `application:didFinishLaunchingWithOptions` method of the `AppDelegate` class). In this way, install will be tracked as soon as your user opens an app for the first time and delaying SDK initialisation might affect this if (for example) you decide to initialise SDK way later in your app and user, even though he installed your app, never reached that point in the app - thus SDK never tracked an install. At the end, it is your call, but like said - would be good if you follow README instructions.

Also, I see you are mentioning `Adjust.getInstance()` method -> please, use Adjust SDK interface like described in example Swift app (https://github.com/adjust/ios_sdk/blob/master/examples/AdjustExample-Swift/AdjustExample-Swift/AppDelegate.swift). When communicating with `Adjust` class, please use static interface, no need to create an instance.

Cheers

**Comment by asalom** [comment]
I got a session recorded with Charles with the problem. Could you provide me with an email so I can send it to with information about what we do in the iOS code?
What happens is: a user installs the app from a Facebook campaign. Opens the app then the SDK makes a call to `https://app.adjust.com/session` and gets a `500 Internal Server Error`

```
"error": "Session request check interval failed (Ignoring too frequent session. Last session: 2017-11-08T09:58:49, this session: 2017-11-08T10:00:52, interval: 2m3s, min interval: 20m) (app_token: XXX, XXX)"
}
```
In the mean time some events and clicks are sent with response `OK`. Then the user makes a purchase and an attribution is sent with tracker as Organic instead as Campaign.

**Comment by uerceg** [comment]
@asalom

This response from backend happens when you have already tracked a session on our backend from this device and then for some reason (and most common reason is you probably uninstalling app from device and reinstalling it again) you send another session to our backend within 20 minutes since previous one. 

Backend just drops this session as too frequent, but apart from that, tracking works normaly (for follwing events/sessions).

**Comment by uerceg** [comment]
Also, you can always drop an email to support@adjust.com and reference this issue.

**Comment by asalom** [comment]
Thanks, I already sent an email.

For the test, we used a fresh device, installed a different app that belongs to the same account and also uses Adjust, deleted that, then install the app with the campaign issue and made a purchase.

Just to make it more clear, the problem we are having is that after installing the app from a Facebook campaign and making a purchase, the attribution is sent as Organic but we expect Campaign.

As I mentioned we have a second app with Adjust. There everything works fine. Marketing team made sure both apps are configured the same way and in fact they exchanged some emails with you guys. From the code side, the only difference I could find is that in the problematic app we send all events in a background thread.

**Comment by uerceg** [comment]
Ah, okay, thanks for the detailed explanation. Email will be fwded to our team soon probably. The fact that your test install is being attributed to different source is most probably more of a test setup issue rather than SDK issue itself. I am sure that someone from our integration team will reply to you and help you with this test case.
