### ISSUE TITLE
Authentication required on the reset session data link

### ISSUE THREAD

**Issue by babzich** [adjust/ios_sdk#322]
Hi guys,

It seems that the page to reset the session data of a device now required authentication. This seems weird, is it something intended? (I don't think it was the case a couple of weeks ago). 

`http://app.adjust.com/forget_device?app_token={yourAppToken}&adid={adidValue}`

![screen shot 2018-02-12 at 11 54 34](https://user-images.githubusercontent.com/868749/36093662-963fbc38-0feb-11e8-8b26-82884d2ea207.png)

Thanks

**Comment by uerceg** [comment]
Hi @babzich 

Yeah, this is no longer public API, but rather if you want to forget your device, you should do that within `Testing Console` on your dashboard. If you need any assistance with it, please feel free to ping your dedicated AM or write the email to support@adjust.com

Cheers
