### ISSUE TITLE
Crash in [ADJActivityState isGdprForgotten]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by fabiankoebel** [adjust/ios_sdk#344]
There is currently a critical bug in the iOS SDK. In random (it looks like) situations we get an exception. Unfortunately it occurs to many many users.

`Fatal Exception: NSInvalidArgumentException`
`-[ADJActivityState isGdprForgotten]: unrecognized selector sent to instance `

`0  CoreFoundation                 0x18476ad8c __exceptionPreprocess`
`1  libobjc.A.dylib                0x1839245ec objc_exception_throw`
`2  CoreFoundation                 0x184778098 __methodDescriptionForSelector`
`3  CoreFoundation                 0x1847705c8 ___forwarding___`
`4  CoreFoundation                 0x18465641c _CF_forwarding_prep_0`
`5              ... 0x102e39130 -[ADJActivityHandler eventI:event:] (ADJActivityHandler.m:921)`
`6              ... 0x102e354cc __33-[ADJActivityHandler trackEvent:]_block_invoke (ADJActivityHandler.m:263)`
`7             ... 0x102e5c4b8 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke (ADJUtil.m:1271)`
`8  libdispatch.dylib              0x182f08aa0 _dispatch_call_block_and_release`
`9  libdispatch.dylib              0x182f08a60 _dispatch_client_callout`
`10 libdispatch.dylib              0x182f471d4 _dispatch_queue_serial_drain$VARIANT$armv81`
`11 libdispatch.dylib              0x182f47af8 _dispatch_queue_invoke$VARIANT$armv81`
`12 libdispatch.dylib              0x182f4849c _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81`
`13 libdispatch.dylib              0x182f5046c _dispatch_workloop_worker_thread$VARIANT$armv81`
`14 libsystem_pthread.dylib        0x18323be70 _pthread_wqthread`
`15 libsystem_pthread.dylib        0x18323bb08 start_wqthread`

I´m currently using version 4.14.1, newer versions doesnt mention any fix for the crash.

**Comment by uerceg** [comment]
@fabiankoebel 

Is this the full stack trace of the crash?

**Comment by fabiankoebel** [comment]
@uerceg there`s a bit more, i updated the original post.
I´ve also another stack trace with the above exception:

`Fatal Exception: NSInvalidArgumentException`
`-[ADJActivityState isGdprForgotten]: unrecognized selector sent to instance 0x1c02a36c0`
`0  CoreFoundation                 0x1831d6d8c __exceptionPreprocess`
`1  libobjc.A.dylib                0x1823905ec objc_exception_throw`
`2  CoreFoundation                 0x1831e4098 __methodDescriptionForSelector`
`3  CoreFoundation                 0x1831dc5c8 ___forwarding___`
`4  CoreFoundation                 0x1830c241c _CF_forwarding_prep_0`
`5  ...             0x10023f3b8 -[ADJActivityHandler setDeviceTokenI:deviceToken:] (ADJActivityHandler.m:1362)`
`6 ...            0x1002604b8 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke (ADJUtil.m:1271)`
`7  libdispatch.dylib              0x182ac8aa0 _dispatch_call_block_and_release`
`8  libdispatch.dylib              0x182ac8a60 _dispatch_client_callout`
`9  libdispatch.dylib              0x182ad29b4 _dispatch_queue_serial_drain$VARIANT$mp`
`10 libdispatch.dylib              0x182ad32fc _dispatch_queue_invoke$VARIANT$mp`
`11 libdispatch.dylib              0x182ad3cc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp`
`12 libdispatch.dylib              0x182adc098 _dispatch_workloop_worker_thread$VARIANT$mp`
`13 libsystem_pthread.dylib        0x182dfbe70 _pthread_wqthread`
`14 libsystem_pthread.dylib        0x182dfbb08 start_wqthread`

**Comment by uerceg** [comment]
@fabiankoebel 

This is quite weird and honestly at this moment I have no idea how can this even happen. Error you are getting is pretty straight forward in it's description -> `ADJActivityState` doesn't contain `isGdprForgotten` field. Which is weird, because `ADJActivityState` class in v4.14.1 which you are using does contain that filed: https://github.com/adjust/ios_sdk/blob/v4.14.1/Adjust/ADJActivityState.h#L15

Also, line numbers from stack trace seem to be kinda skewed (not sure how trustworthy they actually are). For example:

```
0x1002604b8 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke (ADJUtil.m:1271)
```

Line 1271 in `ADJUtil.m` from v4.14.1 looks like this: https://github.com/adjust/ios_sdk/blob/v4.14.1/Adjust/ADJUtil.m#L1271
Method that is mentioned that is getting invoked (launchInQueue:selfInject:block:) is in line 1250: https://github.com/adjust/ios_sdk/blob/v4.14.1/Adjust/ADJUtil.m#L1250

How did you add our SDK to your app?

**Comment by fabiankoebel** [comment]
Thanks for your hints with the line numbers! It turned out that there was a conflict between two Adjust versions in the project, so that isGdprForgotten was really not a the place.

Sorry for the circumstances!
