### ISSUE TITLE
Data races

### ISSUE THREAD

**Issue by ogres** [adjust/ios_sdk#348]
Hello,

I am running Adjust (4.15.0) with Thread-Sanitizer and it reports few data-races.
Here are the logs:

![screen shot 2018-09-26 at 11 34 30](https://user-images.githubusercontent.com/2391557/46071549-8e2ba600-c180-11e8-8bb9-8932bfeeafcb.png)

![screen shot 2018-09-26 at 11 34 42](https://user-images.githubusercontent.com/2391557/46071556-92f05a00-c180-11e8-86ae-07ca656629d0.png)

**Comment by uerceg** [comment]
Hi @ogres 

Thanks for reporting and sorry for a bit delayed answer. Is this something you can reproduce every time? If yes, can you explain the steps?

**Comment by ogres** [comment]
It is not always reproducible, but it usually happens when I try to multiple ads via mediations.

**Comment by ogres** [comment]
because of the nature of the bug, it is not always reproducible, but I don't do anything advanced, just tracking few events ...

**Comment by uerceg** [comment]
HI @ogres 

Wanted to check if this is still happening with latest state of SDK for you? If yes, would it be possible to share SDK initialisation code you're using?

Cheers

**Comment by uerceg** [comment]
👋 @ogres 

We tried to address some issues in [latest iOS SDK release](https://github.com/adjust/ios_sdk/releases/tag/v4.21.3) and I think it should hopefully address this issue as well. In case you can give it a shot and let us know if the issue is still there, feel free to comment/reopen the issue.

Cheers

**Comment by ogres** [comment]
Unfortunately I have not used SDK for a while and cannot confirm whether it is fixed. But lets hope it is 👍
