### ISSUE TITLE
How to test for App Secret?

### ISSUE THREAD

**Issue by amedakedo** [adjust/ios_sdk#354]
Hello guys,

I just wanted to confirm how could I test if an App Secret is working correctly or not? I've already incorporated it into my app, then went to the SDK Signature section in the Adjust dashboard but it says "not enough data" I'm assuming since I've only installed it into a couple of devices?!

So, any insight into how I could test if my App Secret is setup correctly would be appreciated. 
Thanks in advance.

**Comment by uerceg** [comment]
Hi @amedakedo,

Are you testing in sandbox mode? If yes, were you looking at sandbox traffic in the dashboard?

**Comment by amedakedo** [comment]
Thanks @uerceg for the quick reply. Yes I'm testing in sandbox mode.
But, I wasn't checking the sandbox data!!! I was also looking into the wrong section it appears!
After opening the SDK Signature data, I wasn't able to figure out how to set it to show sandbox data.
But going to the statistics page and then turning sandbox mode ON in the filters I was able to see the data!
Again, thanks a lot for your help.

**Comment by uerceg** [comment]
Glad it worked. I'll close the issue but in case you bump into any other issue or question, feel free to reopen it and ping us in here.

Cheers!

**Comment by amedakedo** [comment]
I'm sorry but I have another question. Let's say I want to set the `enforce SDK Signature` option to `OFF`. How can I confirm that the App Secret is set correctly?

If I set it to `ON` and test on a test-device, that will allow me to confirm by looking into the device data from the test console. As the app containing the app secret will have its `TrackName` set to `organic` but the ones without the app secret will be set to `Untrusted Devices::Invalid Signature`

From what I understand if you set the `enforce SDK Signature` to `ON` then all applications installed without the app secret will be considered untrusted devices. This will result in all users downloading the app to become untrusted devices. So, I can't set it to `ON` until I release the app containing the app secret.

But before releasing it I want to confirm that it works as expected. How can I go about accomplishing that?

**Comment by uerceg** [comment]
Okay, lemme try to go through the feature a bit. Like you said, you have a choice, either to set toggle to ON or OFF. 

If it's ON, signature from your app installs will be expected by our backend. If install from your app pings our backend with valid app secret, it will be attributed to it's source. If install from your app pings our backend without app secret or with invalid app secret (deactivated or wrong one), it will be attributed to untrusted devices.

If it's OFF, signature with your app installs is not something our backend will need to attribute installs to their source. If install from your app comes without app secret, it will be attributed to it's source. If install from your apps comes with valid app secret (valid means the one from your app secrets from the dashboard that is active and not deactivated), it will still be attributed to it's source. If install from your app comes with invalid app secret (deactivated or wrong one), it will be attributed to untrusted devices.

If you chose to use app secret and you put it to your app and update it on the app store, switching toggle to ON in the moment when your app is released will not start all of a sudden to treat all your previous app version installs without app secret as untrusted. Those installs are already attributed to it's source and will continue to be treated as such. Switching toggle to ON is only affecting installs which are gonna hit our backend from that moment (moment of switching the toggle) on.

I didn't reply you directly to your question, but I hope that this explanation threw some light on doubts you have. In case it didn't, feel free to ping with additional questions.

Cheers

**Comment by amedakedo** [comment]
Thanks again for the quick reply.
Just to confirm I'm understanding you correctly

If the toggle is set to ON:
1. App with valid app secret → will be attributed to its source.
1. App with no app secret or with an invalid one (deactivated or wrong one) → will be attributed to untrusted devices.

If the toggle is set to OFF:
1. App with valid app secret → will be attributed to its source
1. App with no app secret → will be attributed to its source
1. App with invalid app secret → will be attributed to untrusted devices

If that is the case, is there is a way to change the source to which the app is attributed to (while toggle is OFF), so that I can differentiate between apps with a valid app secret and the ones with no app secret?

**Comment by uerceg** [comment]
Your recap - I'd say that's how it is. But, in case you wanna check with people who are really knowledgable when it comes to that and also about your second question, might be good idea to ping either your dedicated account manager or send an email to support@adjust.com because this second question you have kinda goes out of our team's scope. :)

**Comment by amedakedo** [comment]
Okay, will do just that! Thanks a lot for your help 🙏
