### ISSUE TITLE
AdjustSDK static framework doesn't include a module map and is unusable from Swift

### ISSUE THREAD

**Issue by jeffremer** [adjust/ios_sdk#361]
In attempting to replace our Cocoapods installation of the AdjustSDK with the static framework available in the releases I ran into an issue attempting to use the SDK from Swift. Neither `import Adjust` nor `import AdjustSDK` work, so I took a look inside the framework and it is indeed missing a module map, rendering it unusable from Swift. The dynamic version of the framework does include a module map.

This is easily reproducible:

1. Create a new Swift iOS project
2. Drag the static framework into the link binary with libraries build phase
3. Try to `import Adjust` or `import AdjustSDK` or `importAdjustSdk` from Swift
4. Build and watch it fail

It's pretty easy to fix as well, by manually creating a Modules directory and the module map file in there…

AdjustSdk.framework > Modules > module.modulemap
```
framework module AdjustSdk {
  umbrella header "Adjust.h"

  export *
  module * { export * }
}
```

Of course, as a consumer of this SDK I'd have to do this manual step whenever I integrate a new version of it.

**Comment by uerceg** [comment]
Hi @jeffremer and thanks for reporting this. We’ll take a look. Will keep you posted.

**Comment by uerceg** [comment]
Hi @jeffremer 

And sorry for a bit delayed answer. I am checking this topic now and wondering is there a reason why are you choosing static over dynamic framework? Generated dynamic framework seems to have module map like you have defined it and should be usable from Swift right away.

Reason why we are still having static framework in place is rather historical - we still support iOS 6.0 and we need it for some non native platforms which still didn't manage to find a way to handle dynamic frameworks. But if your app is supporting iOS 8.0 and above, dynamic framework should be fine to use.

Looking forward to hear from you.

Cheers

**Comment by jeffremer** [comment]
Dynamic library loading can be and is often slower than compared to statically building an SDK like yours into the app binary, especially if the app links a lot of dynamic frameworks (like ours does). If the SDK is only used in one binary in the app and is required at launch I don't see much benefit in requiring that it be a dynamic framework.

**Comment by uerceg** [comment]
Fair enough. I'm now currently looking into best way how to add `Modules` folder into static framework structure without doing it super manually. Will keep you posted.

**Comment by uerceg** [comment]
Having in mind that static framework as target doesn't exist in Xcode, rather we use script to build it that way from static libraries and headers, I just took the road of editing script to manually create `AdjustSdk.framework/Modules` folder and place predefined `module.modulemap` file in it. Seems to be working fine with Swift app. Will be live with upcoming 4.17.2 release.

**Comment by uerceg** [comment]
Should be solved with latest [release](https://github.com/adjust/ios_sdk/releases/tag/v4.17.2). In case this issue still persists with it as well, please feel free to reopen it.
