### ISSUE TITLE
Failed to verify bitcode !

### ISSUE THREAD

**Issue by cs4alhaider** [adjust/ios_sdk#364]
I'm getting Failed to verify bitcode in AdjustSdk.framework/AdjustSdk when distributing my archive via ad hoc!

error: Cannot extract bundle from /var/folders/4s/3ws4dx852zb5qtd17fkvzhhw0000gn/T/XcodeDistPipeline.XTS/Root/Payload/MyProject.app/Frameworks/AdjustSdk.framework/AdjustSdk (i386)

**Comment by uerceg** [comment]
Hi @cs4alhaider 

Not sure if this related to Bitcode itself. Maybe the fact that dynamic framework contains simulator targets (i386, x86_64) bothers your archiving. Try to remove them from our framework and see if it helps.

Info on how it can be done:
- http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
- https://stackoverflow.com/a/42642209/1498352

**Comment by firewood** [comment]
We're facing the same issue. After removing the simulator binaries by lipo, the log says that
```
Details:  Error Domain=DVTFoundationErrorDomain Code=-1 "Couldn't determine platform family for AdjustSdk." UserInfo={NSFilePath=/Users/...(snipped).../AdjustSdk/AdjustSdk.framework.dSYM/Contents/Resources/DWARF/AdjustSdk, NSLocalizedDescription=Couldn't determine platform family for AdjustSdk., NSLocalizedRecoverySuggestion=None of the available platform families (iOS, macOS, tvOS, and watchOS) matched an LC_VERSION_MIN load command.}
...
error: exportArchive: Failed to verify bitcode in AdjustSdk.framework/AdjustSdk:
error: Cannot extract bundle from /var/folders/42/sq_xvlq95lsc59jp37cfnlbh0000gp/T/XcodeDistPipeline.hRu/Root/Payload/Beta.app/AdjustSdk/AdjustSdk.framework/AdjustSdk (i386)
```
I guess the first error leads the second error?

**Comment by firewood** [comment]
There seemed that there was a garbage in our repository. The issue is gone after we cleaned up our repository.

**Comment by uerceg** [comment]
@firewood Thanks for update! Glad it worked afterwards.
@cs4alhaider Are you still facing this issue?

**Comment by cs4alhaider** [comment]
I added a scrpit you proveded earlier and it seems working fine

**Comment by uerceg** [comment]
Thanks for the update! Cheers.
