### ISSUE TITLE
Tracking a series of events (funnels)

### ISSUE THREAD

**Issue by murad1981** [adjust/ios_sdk#367]
Is there a way to track a series of events, so that I can see a specific path inside the app that the user follows ? exactly like funnels in Firebase console.

**Comment by uerceg** [comment]
Hi @murad1981

Honestly just read a bit about what funnels in Firebase are. Seems like an interesting thing. If you are wondering if there is such a concept in Adjust dashboard in which you can group some events you created into some higher abstraction structure (like these funnels in Firebase case), I don't think there is such an option. 

To get definite confirmation, you might ask this our support team by writing an email to support@adjust.com.
