### ISSUE TITLE
Could not generate bitcode

### ISSUE THREAD

**Issue by matthiasnagel** [adjust/ios_sdk#368]
If we use `pod 'Adjust'` at the same time with `pod 'Leanplum-iOS-SDK'` we get the following:

> ld: bitcode bundle could not be generated because .../Build/Products/Debug-iphoneos/Adjust/Adjust.framework/Adjust' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '.../Build/Products/Debug-iphoneos/Adjust/Adjust.framework/Adjust' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

On simulator it's completely fine but for our arm64 device bitcode could not be generated.

**Comment by uerceg** [comment]
Hi @matthiasnagel 

Which Xcode / Cocoapods version are you using? Which device are you testing with?

**Comment by matthiasnagel** [comment]
@uerceg I'm using Xcode 10.1 (10B61) and an iPhone XS Max. The pod versions are:
`Adjust (4.17.1)`
`Leanplum-iOS-SDK (2.3.1)`

Let me know if you need more information.

**Comment by uerceg** [comment]
Thanks for the info.

🤔 iPhone XS Max should have `arm64e` architecture (all latest iPhones these days with A12 chipset should have it). Is there any chance just to give older device a try (iPhone X for example) just to see if error happens when non `arm64e` device is attached as well?

**Comment by matthiasnagel** [comment]
@uerceg we get the same error

**Comment by manuellohner2018** [comment]
@uerceg, we also have the same Error. Tested on older Devices as well. Any Update so dar?

**Comment by nzagorchev** [comment]
Is Adjust using bitcode generation?

Until this is resolved from either side, there is a workaround for it:
1. Install the pods
2. Go to Your project Target -> Pods. Edit the following files:
Pods-SampleObjC.debug.xcconfig
Pods-SampleObjC.release.xcconfig

Change the first line regarding the BITCODE_GENERATION_MODE from:
BITCODE_GENERATION_MODE = bitcode
to:
BITCODE_GENERATION_MODE = marker

3. Do this for both files and now run the project.
4. You will need to do this again if you do pod update or pod install since it will remove the changes to those files.

**Comment by matthiasnagel** [comment]
@nzagorchev thanks for the workaround. This works and we can use Adjust and Leanplum together.
Nevertheless are you planning to fix the original problem?

**Comment by uerceg** [comment]
Hey guys, thanks for the useful discussion on this issue and sorry about the delay, these days our iOS crew is OOO. We will check this out next week and hopefully provide an update which addresses this issue. Will keep you posted and ping in case we need any additional info from you.

**Comment by uerceg** [comment]
@nzagorchev @matthiasnagel 

I tried to reproduce the issue, but no luck. Do you guys maybe have an idea what should be changed in Adjust SDK so that this actually solves your issue? I was trying to check bitcode settings in our SDK and seems like we have it enabled in project settings:

- `BITCODE_GENERATION_MODE = bitcode;`
- `OTHER_CFLAGS = "-fembed-bitcode";`
- `ENABLE_BITCODE = YES;`

Is there anything else which you see that we did not properly enable?

**Comment by matthiasnagel** [comment]
@uerceg pretty simple one.

1. Create a new Xcode project, call it `test`. Let it empty.
2. Create a `Podfile` with the following content:
`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'test' do
    pod 'Leanplum-iOS-SDK'
    pod 'Adjust'
end`

3.  Run `pod install`
4. Open `test.xcworkspace`
5. Build and run on an iPhone. Due to the fact thats an architectural problem it doesn't happen on simulator.

Please let me know if you need more information here.

**Comment by uerceg** [comment]
Great, thanks for this one, will give it a try today and keep you posted.

**Comment by uerceg** [comment]
Hm, still not sure why is this happening with our pod. Here's the update from my side after checking out this issue:

- I managed to reproduce the issue with your advices - thanks for that!
- Reason for this error is the fact that once Adjust pod is added, `BITCODE_GENERATION_MODE=bitcode` doesn't seem to be available in Adjust target Build Settings in `Pods` solution. You can check this if you select `Pods` solution and then check `Adjust` and `Leanplum-iOS-SDK` target. Search for `BITCODE_GENERATION_MODE` setting and you'll see that `Leanplum-iOS-SDK` has it, but `Adjust` somehow doesn't.
- If you add this option on your own to our framework target, error is gone, but this is definitely not the way to do it, I agree.
- Until now, I did not find the reason why is out framework target not having this user defined build setting enabled in its target once added as pod. We have those settings set for our entire `Adjust` project and each of the targets.
- What I did as a potential fix and which works when adding our SDK via Cocoapods in this scenario of yours is to add `s.pod_target_xcconfig = { 'BITCODE_GENERATION_MODE' => 'bitcode' }` into `Adjust.podspec` file. After this, everything works just fine. But seems a bit hacky and `Leanplum.podspec` doesn't seem to have it.

I will continue to investigate what's causing `BITCODE_GENERATION_MODE` which is defined in our project not to be present in our target within `Pods` solution. In case you maybe know what might solve this, any advice is more than welcome.

**Comment by uerceg** [comment]
Okay, should be solved with latest [release](https://github.com/adjust/ios_sdk/releases/tag/v4.17.2). In case this issue still persists with it as well, please feel free to reopen it.
