### ISSUE TITLE
Crash on app launch: +[Adjust appDidLaunch:] + 84

### ISSUE THREAD

**Issue by matteinn** [adjust/ios_sdk#369]
Hi!
Found a crash right on app opening using the latest native iOS SDK 4.17.1.
I have attached the stacktrace for reference.
I don't have steps to replicate since it only happened once so far on the production app, it's probably worth noting that the SafeDK 0.31.11 SDK is integrated as well.

Crashed: com.apple.main-thread
EXC_BAD_INSTRUCTION 0x00000000c176b115
[crash.txt](https://github.com/adjust/ios_sdk/files/2954409/crash.txt)

**Comment by uerceg** [comment]
Hi @matteinn,

And thanks for the report. Our iOS crew is currently OOO this week, so we will most probably find some time to check this more in depth next week, but will keep you posted. In case you encounter this again and (with a bit of luck) with steps on how to reproduce this, feel free to update the issue with new info.

**Comment by uerceg** [comment]
Hey @matteinn 

Did you ever face this crash again to share maybe some additional info? We were unable to reproduce this on our end.

**Comment by uerceg** [comment]
In case you obtain any additional info on the crash, feel free to share it with us and reopen the issue.
