### ISSUE TITLE
JSR universal links are not being tracked

### ISSUE THREAD

**Issue by kublaios** [adjust/ios_sdk#372]
I am using `https://app.adjust.com/jsr` to pass encoded iOS universal link using `url` parameter. It opens the app, however, the tracker ID I pass is not being tracked on the dashboard.

On documentation, `adjust_t` parameter is being used to pass the tracker ID so that's how I tried, I also tried `adjust_tracker` parameter but it didn't work either.

Here are 2 sample URLs I tried:
- Pass tracker ID in the URL parameter: https://app.adjust.com/jsr?url=https%3A%2F%2Fmyapp.adj.st%26adjust_t%3D123456%26adjust_tracker%3D123456
- Pass tracker ID as a second parameter to `jsr` path: https://app.adjust.com/jsr?url=https%3A%2F%2Fmyapp.adj.st&adjust_t=123456&adjust_tracker=123456

Is it not working because I am using a wrong key or because Adjust deeplinking does not have this feature?

**Comment by sletthaug** [comment]
Hi there @kublaios 

Please reach out to your Adjust account manager who can escalate the issue internally as required.
This will also allow you to share the real URLs you are testing as opposed to ones filled with dummy values.
