### ISSUE TITLE
Framework Issue: App crashes

### ISSUE THREAD

**Issue by azeemohd786** [adjust/ios_sdk#377]
After adding frameworks and change build phases setting, app crashes and shows this error,

> dyld: Library not loaded: @rpath/AdjustSdkIm.framework/AdjustSdkIm
>   Referenced from: /Users/jmatics3/Library/Developer/CoreSimulator/Devices/9ECF5EE4-4804-46D9-B6EE-C7666989DD33/data/Containers/Bundle/Application/7A335CE7-DFE1-400E-97FB-39507DCFBAA8/Clubby App.app/Clubby App
>   Reason: image not found

**Comment by uerceg** [comment]
Hi @azeemohd786 

Did you try adding `AdjustSdkIm.framework` to `Embedded Binaries` list in your app's project settings?

**Comment by azeemohd786** [comment]
@uerceg Added link binary with libraries but not sure with Embedded Binaries. Although Issue solved when I removed all manual frameworks(like AdjustSdkIm.framework), and went with just pod installation of pod 'Adjust'.
