### ISSUE TITLE
Send Custom value to Adjust SDK

### ISSUE THREAD

**Issue by vijayviswas** [adjust/ios_sdk#380]
My requirement is to send custom  value like "ProdID" to Adjust SDK. I was reading the documentation. I am confused with partner parameter and callbackID. 

Should I set "setCallbackId"? 
Is the below solution correct?

Solution 
ADJEvent *event = [ADJEvent eventWithEventToken:@"abc123"];
[event addPartnerParameter:@"ProdID" value:@"value"];
[Adjust trackEvent:event];

**Comment by uerceg** [comment]
Hi @vijayviswas

That depends what do you want to do with your `ProdID` later inside Adjust ecosystem. Do you expect to get it later as the part of the callback you have set behind that event on the dashboard?

**Comment by vijayviswas** [comment]
@uerceg -My use case is to see the "ProdID" in Adjust dashboard.

**Comment by uerceg** [comment]
Hi @vijayviswas,

I am not quite sure if something like this is even possible. Callback and partner parameters are used by our backend from incoming SDK requests just for purpose of appending them to callback URLs you have placed in our dashboard or which your partners are having set and are never persisted, rather instantly deleted after appending and callback pinging. Answers in here are provided by our SDK developers, so we are not the best address when it comes to getting answers to dashboard related topics. For getting answer to those kinds of questions, you should try to either ping your dedicated account manager or if none available, try writing to support@adjust.com.

Cheers

**Comment by vijayviswas** [comment]
@uerceg  Thanks
