### ISSUE TITLE
Can I get Ads-Media Flag From SDK?

### ISSUE THREAD

**Issue by xiongdi9456** [adjust/ios_sdk#381]
Hello, We have several Ads-medias to help us publish app to users. 
we will create track urls in Adjust dashboard, if user install our app by these ads-media, I think we should have some flags to recognize which media the user is from, can I get it from sdk and how? thanks

**Comment by uerceg** [comment]
Hi @xiongdi9456 

Sounds to me like you're looking for [attribution callback](https://github.com/adjust/ios_sdk#attribution-callback)? Values which `ADJAttribution` object in that callback will provide you, should tell you also the tracker which you have used in your URLs.
