### ISSUE TITLE
Adjust exitSignalHandler

### ISSUE THREAD

**Issue by gowthamyemme** [adjust/ios_sdk#382]
crash_info_entry_0 | CoreSimulator 587.35 - Device: iPhone Xʀ (9A010D2E-D366-4EA6-B8CD-A1C6C3FB7847) - Runtime: iOS 12.2 (16E226) - DeviceType: iPhone Xʀ
-- | --

0Crashed: com.apple.main-threadEXC_BAD_INSTRUCTION EXC_I386_INVOP 0x0000000000000000 Raw Text
--
0 | libsystem_platform.dylib | _os_unfair_lock_recursive_abort + 23
6 | libsystem_c.dylib | exit + 48
7 | Adjust | exitSignalHandler + 11
8 | libsystem_platform.dylib | _sigtramp + 29
43 | UIKitCore | UIApplicationMain + 140
44 | Activehours | AppDelegate.swift line 6main + 6
45 | libdyld.dylib | start + 1

**Comment by uerceg** [comment]
Hi @gowthamyemme,

Can you maybe provide us with some more detailed info on this crash?

**Comment by uerceg** [comment]
In case you have any detailed info about the crash, feel free to share it with us and reopen the issue.
