### ISSUE TITLE
`convertDeviceToken` will return different values under iOS 13

### ISSUE THREAD

**Issue by craigomac** [adjust/ios_sdk#386]
The method `convertDeviceToken` in `ADJUtil.m` [here](https://github.com/adjust/ios_sdk/blob/40e4db214db32d2863307b0e29a199a0826e062e/Adjust/ADJUtil.m#L1225) relies on the following logic to generate a device token:

    [deviceToken.description stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@"<>"]]

Apps linked against iOS 13 no longer return a neat hexadecimal version of `NSData` bytes and this code should be replaced with a solution like one of those from here: https://stackoverflow.com/questions/1305225/best-way-to-serialize-an-nsdata-into-a-hexadeximal-string?rq=1.

**Comment by uerceg** [comment]
Hi @craigomac,

Thanks for reporting, will be checked and addressed in upcoming versions. 

Will keep you posted in here.

Cheers

**Comment by uerceg** [comment]
Hi @craigomac,

We have released [v4.18.1](https://github.com/adjust/ios_sdk/releases/tag/v4.18.1) which addresses this upcoming iOS 13 change. 

Cheers!
