### ISSUE TITLE
Attribution's trackerToken and campaign is wrong in iOS 13

### ISSUE THREAD

**Issue by artursDerkintis** [adjust/ios_sdk#389]
When opening link 
https://xxxx.adj.st/?adjust_t=xyz1234&adjust_deeplink=myapp://
I run into issue where on iOS 13 the trackerToken `xyz1234` value is completely different when retrieving in on `adjustAttributionChanged`. Also campaign name is generic `Campaign name (1234567890)` and not what we've defined for the specific tracker.
We're relying to show different localisations for different campaigns so this will break a lot of things in our app.

I've attached a screenshot of the values I get back.
<img width="675" alt="Screenshot 2019-09-04 at 10 01 47 pm" src="https://user-images.githubusercontent.com/13361618/64286202-ac3f8000-cf65-11e9-8b04-623f992b469c.png">

Also its worth noting that it works perfectly as expected in iOS 10-12.

**Comment by uerceg** [comment]
@artursDerkintis 

Thanks for reporting this. Are you seeing this in production or while testing with iOS 13 beta? Does it happen only when you open your app with deep link like in scenario described above or do you see it happening when performing clean install? Also, if while testing, do you see this on device or simulator (or both)?

**Comment by uerceg** [comment]
@artursDerkintis 

Also, if you can, please check my email in GitHub profile and send me the information about app token and `adid` from this test you did in screenshot above so that we can check logs out side and see what exactly happened.

Thanks in advance.

**Comment by artursDerkintis** [comment]
@uerceg thanks for getting back so quickly. 
Yes it happens both production and sandbox environment. 
It also happens from clean install. I wasn't able to open the link with that format in simulator to test this in right was as it can't find App Store on sim.

**Comment by uerceg** [comment]
@artursDerkintis

Thanks for the infos. Getting your test device ID (IDFA or `adid`) and app token per email would be great so that we can investigate this on our side and see what happened. 

Looking forward to hear from you. 

Cheers

**Comment by uerceg** [comment]
Hi @artursDerkintis 

Thanks for follow up email and info in there. I think I understand what's the issue in your case. You have been attributed to dummy iAd click values since install of your app on that test device origins from 2018 year just a bit before backend deployed filters on our side. That should not be the case anymore.

What you need to do is take your device's IDFA, go to testing console in dashboard, forget the device for your app, uninstall it from test device and then perform your test again.

Let us know how that went.

**Comment by artursDerkintis** [comment]
Hi @uerceg 
That solved the issue. Thanks a lot.
