### ISSUE TITLE
Universal link doesn't work properly.

### ISSUE THREAD

**Issue by rumaniel** [adjust/ios_sdk#397]
Hi, Team.

I implement the adjust and our team using adjust deep link as a promotion.
But I got a report that it didn't work properly on some apps on some ios devices.

The app is a multi-platform app that has Android, iOS and Facebook Canvas so we always add a **fallback** URL on deep link URL.

I made a deep link URL _https://app.adjust.com/bvbkt79?fallback=http://apps.facebook.com/jackpotjoyslots&amp;deep_link=com.gamesyssocial.jackpotjoy://&amp;fallback_lp=com.gamesyssocial.jackpotjoy://http://apps.facebook.com/jackpotjoyslots&amp;://adjust?action=_

Our team delivery this via email. And found that on iPad with Gmail, it redirects to the fallback URL which Facebook canvas app. But I expected that it will redirect to the installed app.

So I checked the [documents](http://help.adjust.com/en/optimize/re-engagement/deeplinks/direct-links-for-ios#create-cross-platform-direct-links-for-apps-configured-as-multi-platform-in-adjust) and made a Cross-platform direct link URL _https://gqyg.adj.st?adjust_t=bvbkt79&fallback=http%3A%2F%2Fapps.facebook.com%2Fjackpotjoyslots%26amp%3Bdeep_link%3Dcom.gamesyssocial.jackpotjoy%3A%2F%2F%26amp%3Bfallback_lp%3Dcom.gamesyssocial.jackpotjoy%3A%2F%2Fhttp%3A%2F%2Fapps.facebook.com%2Fjackpotjoyslots%26amp%3B%3A%2F%2Fadjust%3Faction%3D%0A_.

I tested this and got another issue on OSX. With adjust deeplink on OSX, it redirected to Facebook canvas app. But with Universal Link, it redirected to the app store page on apple.com. And also on Android, it redirected Google Play market page, not open the app.

So Universal Link doesn't work on other platforms but adjust deeplink works but not all the cases on iOS. 

Is there any point that I mistake or good solution to solve this case?

I think this issue related to #287 but there is no more update so I make a new issue.

Thanks.

**Comment by sletthaug** [comment]
Hi @rumaniel 
Please reach out to your Adjust account manager, who will help you out with this issue. 

Your account manager can then escalate this internally as needed.

Thanks.
