### ISSUE TITLE
ADID returning nil

### ISSUE THREAD

**Issue by brurend** [adjust/ios_sdk#399]
Anywhere we try to access the adid using '[Adjust adid]' it always returning nil. Everything else seems to be working as expected.

SDK version: 4.18.3
iOS version: 13.2.3

**Comment by uerceg** [comment]
Hi @brurend 

Where are you calling this method and where are you initialising the SDK?

Cheers

**Comment by brurend** [comment]
I'm initialising the SDK at the AppDelegate. We tried calling this method in many different places and flows.

**Comment by uerceg** [comment]
Any chance you can perform following test:

1. Uninstall app from your test device.
2. Set SDK to sandbox environment and log level to verbose. 
3. Print the output of `[Adjust adid]` call.
4. Run the debug version of your app from Xcode on test device.
5. Pick up logs and send them over.

?

Feel free to censore any sensitive parts from the logs (app token and/or anything else you think of as sensitive). Or if you don't feel comfortable with posting logs in here, send me an email and reference this issue and I'll take a look.

**Comment by brurend** [comment]
Hi, we found out it was an error on the implementation on our end, we were using the wrong instance to get adid and it wasn't initialized. It's working as intended now, thank you.

**Comment by uerceg** [comment]
Thanks for the update! Cheers.

**Comment by dervisyilm** [comment]
Hi everyone,
I added Adjust SDK (latest version) on my project, and call Adjust.getInstance()?.idfa() and Adjust.adid() function in the 
 AppDelegate "didFinishLaunchingWithOptions" method, but Adjust.getInstance()?.idfa() and Adjust.adid() return "nil" 
 Please help me
