### ISSUE TITLE
No events tracked in iOS production environment

### ISSUE THREAD

**Issue by thuannhanACM** [adjust/ios_sdk#402]
Hi guys,
In my app, no events are tracked with the iOS build which submitted to app store (environment: Production, LogLevel: Suppress). Noted that sandbox worked well for both android and iOS; and the android build production worked too.
I already have a build with same defines as the app store build,, same adjust environment, log level...and this build tracked install event as well.
Is there anything could harm the process of the adjust SDK?

**Comment by apoorva-techie** [comment]
I am facing the same issue right now. Getting all the event tracks and logs on debug environment on iOS but not on Production. And despite the fact that event success callbacks are being received in the code in both sandbox and production (verified this).

**Comment by uerceg** [comment]
Hi @thuannhanACM and @apoorva-techie 

Can you please tell me which SDK version are you using in your apps?

Environment setting should not affect tracking at all. Only difference between sandbox and production is the fact that network request payload SDK sends to backend will contain different value for environment parameter and that's it. So if SDK worked well in sandbox for you, it should work in exact same way in production as well (minus logging which we're trying to suppress in production).

**Comment by thuannhanACM** [comment]
i'm using 4.11.4 which had been implemented years ago. but only figured that the iOS install not tracked in production recently. i'm collecting more informations. will update the tickets asap.

**Comment by thuannhanACM** [comment]
OK guys, i got the reason for my case, our iOS deployment process should automatically set the appToken, but it doesn't. So, correct the process and the iOS events tracked as well.
Thanks for reading.
