### ISSUE TITLE
Swift 5 build issue

### ISSUE THREAD

**Issue by kohlidevils** [adjust/ios_sdk#403]
I am getting following error when try to build with swift 5 Xcode 11.3, 
`'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

**Comment by uerceg** [comment]
Hi @kohlidevils,

Sorry for delay in replying. Are you still facing this issue or did you manage to solve it?

Cheers

**Comment by ergunkocak** [comment]
I experienced the same issue and solved it by removing the pod install from my app extension ;)

**Comment by uerceg** [comment]
Thanks for suggestion @ergunkocak.

@kohlidevils In case issue is still there, feel free to comment / reopen.

Cheers
