### ISSUE TITLE
Update README for Swift Code Example

### ISSUE THREAD

**Issue by EmreSURK** [adjust/ios_sdk#410]
We have code examples in ObjC. It may nice adding Swift versions of these examples.
For example;

```
#import "Adjust.h"

NSString *yourAppToken = @"{YourAppToken}";
NSString *environment = ADJEnvironmentSandbox;
ADJConfig *adjustConfig = [ADJConfig configWithAppToken:yourAppToken
                                            environment:environment];

[Adjust appDidLaunch:adjustConfig];
```

It should be;

```
let yourAppToken = ""
let environment = ADJEnvironmentSandbox
let adjustConfig = ADJConfig.init(
	appToken: yourAppToken,
	environment: environment
)
Adjust.appDidLaunch(adjustConfig)
```

Do you open to contribution? I can just open a pull request.

**Comment by nonelse** [comment]
We do have an example app in [Swift](https://github.com/adjust/ios_sdk/tree/master/examples/AdjustExample-Swift), but we have not update the README guide to include Swift examples.
We are also somewhat burdened by the obj-c origin of our API's and cannot really change it's signatures for a nicer Swift interface until a new major version update.
We do accept Pull requests and have added contributions from the community before, so if you want to try to add some, you can.

**Comment by uerceg** [comment]
Hey guys,

We're in process of moving official SDK integration docs into the help center on our official web page: https://help.adjust.com/en/article/get-started-ios-sdk.

In there, you should be able to find Swift code snippets as well.

Sorry for a bit of delay on this one. In case you have any further questions, feel free to comment/reopen.

Cheers
