### ISSUE TITLE
Tracker URL

### ISSUE THREAD

**Issue by brurend** [adjust/ios_sdk#412]
Hi, I'm trying to integrate our app with a tracker URL but its not registering any events. I tried setting up a default tracker on the app but it didn't work. Is there anything else that I might be doing wrong?

**Comment by uerceg** [comment]
Hi @brurend 

I am not sure from your description what exactly are you trying to test. Can you maybe just be more detailed and describe:

- How does your test case look like?
- What are you expecting to happen?
- What is happening instead?

Cheers
Ugi

**Comment by uerceg** [comment]
Hi @brurend 

Any update on this one?

Cheers

**Comment by brurend** [comment]
Hi @uerceg , apologize for taking so long to answer.

We contacted the Adjust support directly and we managed to solve our problem with the default Tracker.
We still believe something is wrong with our data but it probably is an implementation problem and support is helping us.
