### ISSUE TITLE
Guideline 1.3 - Safety - Kids Category

### ISSUE THREAD

**Issue by Beyond-Chao** [adjust/ios_sdk#413]
Apple refuse mail:

"We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. 

Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties."

**Comment by uerceg** [comment]
Hey @Beyond-Chao 

Thanks for reaching out. Feel free to ping your dedicated account manager or if you don't have any, send email to support@adjust.com with this question and our support team will help you with this.

Cheers
