### ISSUE TITLE
No update possible when including criteo in cartfile

### ISSUE THREAD

**Issue by DanielLeberle** [adjust/ios_sdk#416]
Hi everyone,

I have problems updating to the latest adjust version. In my Cartfile I have 
`github "adjust/ios_sdk" "criteo"` 
and when I run 
`carthage update ios_sdk --platform iOS`
carthage always checks out commit 3138a451237d27fb3df9d5e1f26e146e60ce8a71.

I haven't found out yet how to define the framework version or commit hash in the cartfile while also having the criteo plugin added to the adjust line. Do you have any idea how I can fix this?
Thanks in advance!

**Comment by uerceg** [comment]
Hey @DanielLeberle 

Did you solve this issue and if yes, what was the problem?

Cheers
