### ISSUE TITLE
Missing nil check of [data writeToFile:filePath ... at ADJUtil.m

### ISSUE THREAD

**Issue by sidepelican** [adjust/ios_sdk#417]
In this line, it's crashing because the nil check of `filePath` is forgotten.

https://github.com/adjust/ios_sdk/blob/08c99313c7cce8578ed32f5bc7a09fd4790854f3/Adjust/ADJUtil.m#L387

![スクリーンショット 2020-04-01 15 12 52](https://user-images.githubusercontent.com/19257572/78105361-f4efe680-742b-11ea-8462-b13bba74f350.png)

**Comment by sidepelican** [comment]
We're using Version 4.21.0.

**Comment by uerceg** [comment]
@sidepelican Thanks for reporting. Is it always reproducible in your app?

**Comment by sidepelican** [comment]
It's rare crash event (maybe less than 1%).
I can’t reproduce by myself.

**Comment by uerceg** [comment]
Thanks for the update. We'll release patch update to add this check nevertheless. Will keep you posted.

**Comment by uerceg** [comment]
Hi @sidepelican 

Thanks one more time for reporting this. This should now hopefully be fixed in our latest SDK update (https://github.com/adjust/ios_sdk/releases/tag/v4.21.1).

In case you still notice the issue with latest version, please feel free to comment/reopen.

Cheers
