### ISSUE TITLE
Wont compile on Xcode 11.3 and possibly on older versions

### ISSUE THREAD

**Issue by arkenthera** [adjust/ios_sdk#428]
Hi,

Latest version 4.21.3 and probably starting from 4.21.1 (#420), you will get linker errors saying invalid bitcode when building a Unity project on Xcode 11.3 (should also apply to non-Unity projects). It took me a while to find out that Adjust was the culprit (since error logs dont actually say Adjust) but I can say that there are no linker errors building Adjust 4.20.x on Xcode 11.3. 

If you disable bitcode, there are no linker errors but that's not an option for me.

Is this an intended change ?

Error:

```
❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture armv7
 ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have to use Xcode 11.3 due to some linker bugs on Xcode 11.4 so updating to Xcode 11.4 is not an option as well.

**Comment by uerceg** [comment]
Hi @arkenthera 

Yes, we tend to always build releases we attach to release page with latest official Xcode version. I have just rebuild the binaries and re-attached them built with lower Xcode version. Feel free to give it a shot and comment/reopen in case you're still facing this issue.

Cheers
