### ISSUE TITLE
please, update webview bridge.

### ISSUE THREAD

**Issue by pingwinator** [adjust/ios_sdk#431]
Apple has added[ a native js bridge in ios 8](https://developer.apple.com/documentation/webkit/wkusercontentcontroller?language=objc). Please, remove the workaround with a custom js bridge. This is not actual for years. 
ps - you could use [Facebook](https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.m#L839) implementation as a reference.

**Comment by Phobetor** [comment]
This would be a great improvement! The current implementation is just crazy.

Could you use the same interface like in the android implementation?
In that case the JavaScript-side could just look the same and doesn't need two different implementations depending on the platform of the SDK.

**Comment by uerceg** [comment]
Hey guys,

Sorry for quite a bit delayed reply on this one. Thanks for the tips and for the references. Yes, this is definitely something we want to get away from (custom bridge implementation we're using right now). We have this in our roadmap for next iOS SDK major release (v5.0.0) and we'll try to clean that up then. For the time being in v4, we're gonna leave things as they are.

In case you have any other questions/concerns about this one, feel free to comment/reopen.

Cheers
