### ISSUE TITLE
Potential bug with ADJSubscription's copyWithZone method

### ISSUE THREAD

**Issue by atilimcetin** [adjust/ios_sdk#436]
Inside `copyWithZone` method, `_transactionDate` and `_billingStore` variables are set as the copies of the `receipt` object:
https://github.com/adjust/ios_sdk/blob/69891bd62cd9a9e954eb1bd30b5a9d9bf4516204/Adjust/ADJSubscription.m#L131
https://github.com/adjust/ios_sdk/blob/69891bd62cd9a9e954eb1bd30b5a9d9bf4516204/Adjust/ADJSubscription.m#L134

I think the correct implementation should be similar to:
```
copy->_transactionDate = [self.transactionDate copyWithZone:zone];
copy->_billingStore = [self.billingStore copyWithZone:zone];
```

**Comment by uerceg** [comment]
Hi @atilimcetin 

Thanks for reporting, nice catch. Patch update will be shipped today. Will keep you posted. Also for the record, even - though protocol implementation has been added, it was actually meant for future usage and is not needed at the moment, so everything should be good, but nevertheless, fix is on its way.

**Comment by uerceg** [comment]
Hi @atilimcetin 

Fix has been released: https://github.com/adjust/ios_sdk/releases/tag/v4.22.1

Thank you one more time for your report!

Cheers. 🍺
