### ISSUE TITLE
Criteo version fails to build

### ISSUE THREAD

**Issue by jvk75** [adjust/ios_sdk#439]
Using Adjust SDK Criteo Plugin version with Carthage ```github "adjust/ios_sdk" "criteo"``` fails to build. Started today after new release.

```
/tmp/sandbox/workspace/Carthage/Checkouts/ios_sdk/Adjust/Adjust.m:532:21: error: property 'subscriptionPath' not found on object of type 'AdjustTestOptions *'; did you mean 'subscriptionUrl'?
808
    /tmp/sandbox/workspace/Carthage/Checkouts/ios_sdk/Adjust/Adjust.m:533:29: error: property 'subscriptionPath' not found on object of type 'ADJSavedPreLaunch *'
809
    /tmp/sandbox/workspace/Carthage/Checkouts/ios_sdk/Adjust/Adjust.m:533:60: error: property 'subscriptionPath' not found on object of type 'AdjustTestOptions *'; did you mean 'subscriptionUrl'?
```

**Comment by uerceg** [comment]
Hey @jvk75 

Thanks for reporting, if you can just for the time being revert to previous version, we'll check this and push fix commit soon. Will keep you posted.

**Comment by uerceg** [comment]
@jvk75 

Can you give it a shot again?

**Comment by jvk75** [comment]
@uerceg now it works again!

**Comment by uerceg** [comment]
Thanks for reporting! In case any issue pops up again, feel free to ping. Cheers.
