### ISSUE TITLE
Cocoapod - update - time out

### ISSUE THREAD

**Issue by ergunkocak** [adjust/ios_sdk#440]
Hello,

When i try to update my cocoapods i receive this error :

[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/5/1/d/Adjust/4.22.0/Adjust.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/5/1/d/Adjust/4.22.1/Adjust.podspec.json Response: Timeout was reached

fyi

**Comment by uerceg** [comment]
Hi @ergunkocak 

Thanks for reporting. Hm. Does the same happen if you remove Adjust pod and readd it?

**Comment by ugi** [comment]
In case issue still persists, feel free to comment/reopen.
