### ISSUE TITLE
Commits being deleted?

### ISSUE THREAD

**Issue by yhkaplan** [adjust/ios_sdk#441]
Several times a year our CI stops working because the commit in our Cartfile.resolved file was deleted from this repository. Is there some way to avoid this? 

This might not apply to the master branch, but on the `criteo` branch, we set the version to specific commits (as there don't appear to be release tags for that branch). However, commits seem to be deleted every once in awhile, which means I have to stop everything and update the SDK to a newer version to fix the CI.

**Comment by uerceg** [comment]
Hi @yhkaplan 

Very interesting, thanks for sharing your use case. I think that might be the reason of taking shortcuts several times and `git push -f`-ing things. But now that you made us aware of how you use this branch, we'll pay attention to this in the future. 

Cheers!

**Comment by yhkaplan** [comment]
Thanks in advance!
