### ISSUE TITLE
Why do we need to use criteo branch?

### ISSUE THREAD

**Issue by shindyu** [adjust/ios_sdk#442]
Hi!. I have a question about the criteo branch.

This page tells us to use the criteo branch when implementing Adjust's Criteo Plugin.
https://appdoc.criteotilt.com/jp/adjust/a/ios/

However, the commit hash of the criteo branch seems to change frequently, so it seems that there are many issues where the build fails.

Why do we need to use criteo instead of releases? Is it safe to use releases?

**Comment by uerceg** [comment]
Hi @shindyu 

Criteo API is not part of the Adjust iOS SDK source code on `master` branch of our repository (also not part of any official SDK release we make). It's kept on a separate branch which pretty much reflects state of official release + adds Criteo API on top. So if you want to use Criteo, you should be using state of SDK code from that branch, official release will not contain Criteo API.

We have Criteo (also Trademob and Sociomantic) API outside of core SDK code and are thinking of these as plugins to our SDK code, thus not part of the core part and placed on separate branches.

In case you have any further questions, feel free to ping.

Cheers
