### ISSUE TITLE
Adjust energy crashes

### ISSUE THREAD

**Issue by ab-rdarts** [adjust/ios_sdk#447]
As you can see we have discovered energy crashes on user devices in the production mode like on screenshot. It seems they are related to writing Adjust packages in background thread.

After investigating of Adjust code we see that potentially it can lead to bad performance on devices with bad internet connection or no internet connection. All packages are added one by one and also removed one by one. Adjust writes all accumulated packages to disk on every such operation. So we see degraded performance of application when package buffer contains more than 3000 events.

Adjust SDK 4.22.1

<img width="979" alt="Screen Shot 2020-07-25 at 14 12 42" src="https://user-images.githubusercontent.com/9376541/88455772-e9b04300-ce80-11ea-8b02-0ef778f25bb8.png">

**Comment by ugi** [comment]
Hey @ab-rdarts 

Thanks for detailed report. Is this maybe something you are able to reproduce when testing your app locally?

**Comment by ab-rdarts** [comment]
@ugi We have reproduced only degrated performance, but not crash itself

**Comment by ugi** [comment]
Thanks for your input, we'll try to investigate this by looking in this direction of having lots of packages queued. 

@kantanta can it be that in your app this can also happen - really big number of packages being queued?

Also @ab-rdarts if I may ask what is the use case of the SDK in your app when you are getting so many packages queued and not sent?

**Comment by ab-rdarts** [comment]
@ugi Our application sends a lot events to adjust so during bad internet connection such scenario is quite possible. It depends on application state but approximately 1 event in 0.5 second, sometimes it can be even more often sometimes less often. Also our application still works while offline.

**Comment by uerceg** [comment]
Hi @ab-rdarts,

Sorry for delay in here. We have just added one [change](https://github.com/adjust/ios_sdk/pull/626) to our SDK as advised by the client who seems to be having similar-ish issues which are being shown in this example you faced with. In case you are still facing these issues, we'd be curious if iOS SDK v4.32.1 solves this issue for you or would you still be experiencing it.

Cheers

**Comment by uerceg** [comment]
In case you're still facing this issue with iOS SDK v4.33.4 (or later), feel free to comment / reopen. Cheers.
