### ISSUE TITLE
GDPR opt-in and install attribution

### ISSUE THREAD

**Issue by MaximeLM** [adjust/ios_sdk#450]
Hi,

I am implementing GDPR opt-in in an application. This means that the Adjust SDK should not be enabled until the user has accepted analytics.

In my application:didFinishLaunchingWithOptions: method, i have this code:

```
let config = ADJConfig(appToken: appToken, environment: environment)
Adjust.setEnabled(isAnalyticsEnabled)
Adjust.appDidLaunch(config)
```

I have 2 questions:
- Is it ok to call Adjust.setEnabled before Adjust.appDidLaunch?
- If the SDK is enabled later, will the installation event be lost (used for attribution) ?

**Comment by siriusdely** [comment]
Hi @MaximeLM , 

have you found the answer to this question? I am basically wondering for the same thing too.

Thank you.

**Comment by MaximeLM** [comment]
@siriusdely no, I didn't get an answer.

**Comment by uerceg** [comment]
Sorry guys for delay in here.

Support is probably best place to ask for specific flows in your app, but we can speak from purely SDK functionality perspective in here. 

```swift
let config = ADJConfig(appToken: appToken, environment: environment)
Adjust.setEnabled(isAnalyticsEnabled)
Adjust.appDidLaunch(config)
```

☝️ Doing this would initialise SDK in disabled state. So it would just initialise certain stuff in memory, but no tracking will happen. In case you call `Adjust.setEnabled(true)` at later point, then from that moment on, SDK will start the tracking. Install session will be created in that moment and sent.

In case you have more questions about the flow in SDK in this case, feel free to ask.

Sorry one more time for this long waiting.

Cheers

**Comment by uerceg** [comment]
In case you have any further questions, feel free to comment/reopen.

Cheers
