### ISSUE TITLE
4.23.0 – Float cast overflow in ADJSystemProfile.m:835 on Simulator

### ISSUE THREAD

**Issue by antiraum** [adjust/ios_sdk#457]
When running on Simulator with Undefined Behaviour Sanitizer enabled, a Float cast overflow is reported for line ADJSystemProfile.m:835.

```
-100 is outside the range of representable values of type 'unsigned long'
```

**Comment by ugi** [comment]
Hey @antiraum 

Thanks for reporting, we'll change destination type in next release, but semantically wise, doesn't harm any logic.

Cheers

**Comment by ugi** [comment]
Hi @antiraum 

Sorry for not updating this issue, but as of v4.23.1, this should be resolved. Feel free to give latest SDK version a shot and comment/reopen in case issue is not fixed.

Cheers
