### ISSUE TITLE
Adjust.requestTrackingAuthorization does not always show prompt

### ISSUE THREAD

**Issue by KristopherGBaker** [adjust/ios_sdk#460]
Hi,

I’m working on adding support for iOS 14's AppTrackingTransparency and also upgrading the Adjust SDK to 4.23.0 for my company's app.

I'm using Xcode 12 beta 5, an iPhone X running iOS 14 beta 5, and CocoaPods for including the SDK.

I'm trying to use the wrapper method for requestTrackingAuthorizationWithCompletionHandler included with 4.23.0, but it does not always seem to work in my testing.

If I use ATTrackingManager directly instead of the Adjust wrapper, it works fine.

If I use the Adjust wrapper, it seems appTrackingManager in Adjust/Core/UIDevice+ADJAdditions.m is nil, and so the actual requestTrackingAuthorization call is never made (it did seem to work a few times however when stepping through the code line by line, but not if I just set a breakpoint in UIDevice+ADJAdditions.m).
So calling requestTrackingAuthorizationWithCompletionHandler seems to just return here - https://github.com/adjust/ios_sdk/blob/03d4f16f0773b85430ed66dcbeb361b336a45a79/Adjust/ADJAdditions/UIDevice%2BADJAdditions.m#L63

Are you aware of any issues around this, or is there anything additional I should be doing?

If I call ATTTrackingManager directly first, then call the Adjust wrapper, the appTrackingManager seems to be non-nil, so it seems the AppTrackingTransparency framework may not always be loaded at the time of calling the Adjust wrapper on its own.

I've shared the verbose log with my company's Adjust support contact, but there doesn't seem to be anything in the logs that might be helpful.

**Comment by ugi** [comment]
Hi @KristopherGBaker,

Hm, interesting. We are not aware of issues like this. Do you have `AppTrackingTransparency.framework` added to your `Frameworks, Libraries and Embedded Content` part of your project settings?

<img width="609" alt="Screenshot 2020-08-25 at 09 52 19" src="https://user-images.githubusercontent.com/1741635/91147594-c57e9680-e6b8-11ea-8bce-b7f6aad19fb4.png">

**Comment by KristopherGBaker** [comment]
Thanks for the quick response @ugi !

I somehow seem to have missed that. Thanks! It seems to be working now.

**Comment by euroboy** [comment]
I've added the **AppTrackingTransparency.framework** to **Frameworks, Libraries and Embedded Content** but alert is still not showing.
