### ISSUE TITLE
What happens if our app already has SKAdNetwork setup, will there be duplicates installs and events?

### ISSUE THREAD

**Issue by nadirg** [adjust/ios_sdk#461]
Since Adjust now has it too, what happens if it's set by default in Adjust? Will you dedup events and installs?

**Comment by ugi** [comment]
Hi @nadirg 

The fact that Adjust SDK offers a possibility to automatically handle SKAdNetwork flow doesn't really affect anything on SKAdNetwork side. For example, default behaviour is that our SDK will handle flow for SKAdNetwork by default, meaning that it will fire call to [register](https://developer.apple.com/documentation/storekit/skadnetwork/2943654-registerappforadnetworkattributi?language=objc) method upon launch. If you do this on your own or if any other library/SDK from your app does it, it will not create duplicate installs on Apple's end - only first registration call is important for Apple to figure out that it's supposed to look for attribution for your app install. Subsequent calls to register method will simply be ignored. So nothing really to deduplicate when it comes to install.

When it comes to events, you can set conversion values for certain events in Adjust dashboard and then our SDK might make a call to conversion value update method once these happen. Again this call is nothing but updating conversion value for your user. Nothing for us in here to deduplicate on either I'd say (for more info on how things work on dashboard end - feel free to ping our support team).

Cheers

**Comment by nadirg** [comment]
Hi @ugi I see now; thank you, so it's clear

**Comment by ugi** [comment]
In case you have any further questions/concerns, feel free to comment/reopen.
