### ISSUE TITLE
4.23.0 Cocoapods missing Apptrackingtransparency.framework in Other Linker Flag

### ISSUE THREAD

**Issue by PhilipSo6w** [adjust/ios_sdk#462]
### Reproduce steps:

1. use Cocoapods to install 4.23.0
2. open Xcode workspace and check Other Linker Flag

expected: Apptrackingtransparency.framework should have added with -weak_framework on it as it has an iOS 14 wrapper function.

<img width="508" alt="Screenshot 2020-09-02 at 12 30 35 PM" src="https://user-images.githubusercontent.com/28971101/91932271-43c1e500-ed18-11ea-8d8e-db6883e81481.png">

**Comment by rabc** [comment]
Hey @PhilipSo6w 

Right now we can't add `AppTrackingTransparency.framework` in the podspec because the build would fail in Xcode 11. We will add it in a new release as soon as Xcode 12 and iOS 14 are officially released.

For the time being, you can add it manually in your project.
