### ISSUE TITLE
requestTrackingAuthorizationWithCompletionHandler is not triggering permission popup.

### ISSUE THREAD

**Issue by suatkarakusoglu** [adjust/ios_sdk#463]
While using ATTrackingManager's requestTracking method, it prompts with permission dialog and works quite well. 
But using the Adjust's wrapper function to feed the adjust with the related idfa, it doesn't prompt and even callback is not triggered.

Is there something that I am missing?

**Comment by ugi** [comment]
Hi @suatkarakusoglu 

Have you added `AppTrackingTransparency.framework` to list of linked frameworks to your app in Xcode project settings?

**Comment by suatkarakusoglu** [comment]
Thank you @ugi, this has fixed.
I wasn't aware of this step. Have a nice one ;)

**Comment by suatkarakusoglu** [comment]
If anyone encounters this, fixing it via adding to linked libraries okey. 
But for lower than iOS 14 devices, the linking should be optional otherwise it doesn't compile.

![Screen Shot 2020-09-03 at 16 47 15](https://user-images.githubusercontent.com/1485071/92123294-23238900-ee05-11ea-94bc-1efdd8a1a795.png)

**Comment by ugi** [comment]
Yep, it should be, added this to [README](https://github.com/adjust/ios_sdk/pull/465) as well. Thanks for pointing out!
