### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by farev** [adjust/ios_sdk#469]
<img width="1440" alt="Screen Shot 2020-09-16 at 7 57 20 PM" src="https://user-images.githubusercontent.com/50063514/93410821-fafd4680-f856-11ea-8e88-6ff2e464480f.png">
Hello, I added the adjust sdk to my game by following the steps  in the readme. I am sure I did everything correctly but when I try to run my game I get 3 errors. 

Undefined symbol: _OBJC_CLASS_$_Adjust

Undefined symbol: _OBJC_CLASS_$_ADJConfig

Undefined symbol: _ADJEnvironmentProduction

I have searched for several days now but I haven't been able to fix it.

**Comment by ugi** [comment]
Hi @farev 

Which SDK version are you using? Is your game native app or built with some other mobile framework (Unity, React Native, etc)?

**Comment by farev** [comment]
I am using the newest version of the AdjustSdkDynamic.framework. I made it with buildbox but that isn't the problem because I was able to build and upload my game to the app store.

**Comment by ugi** [comment]
Thanks for the answers, we'll check it out on our end and keep you posted.

**Comment by farev** [comment]
Ok thank you

**Comment by ugi** [comment]
Hi @farev 

Just tried adding dynamic framework of the latest v4.23.1 release to the iOS app and it worked without any issues - wasn't able to reproduce these errors on my end. Can you reproduce this behaviour in dummy iOS app and send the project over?

**Comment by farev** [comment]
I tried again in it worked I had done something wrong while implementung it. I had put the AdjustSDKDynamic file when I only needed to put AdjustSDK.framework.

Thank you for your help.

**Comment by ugi** [comment]
Amazing, thanks for letting us know.

Cheers!
