### ISSUE TITLE
Xcode 12 Deprecation warnings

### ISSUE THREAD

**Issue by gilrodar** [adjust/ios_sdk#470]
Xcode version: 12.0
Adjust version: 4.23.1
iOS Version: 14.0

`'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0`

`'initForReadingWithData:' is deprecated: first deprecated in iOS 12.0 - Use -initForReadingFromData:error: instead`

`'unarchiveObjectWithFile:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead`

`'initForReadingWithData:' is deprecated: first deprecated in iOS 12.0 - Use -initForReadingFromData:error: instead`

`'unarchiveObjectWithFile:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead`

`'archiveRootObject:toFile:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: and -writeToURL:options:error: instead`

**Comment by ugi** [comment]
Hey @gilrodar 

Thanks for reporting, we'll check on these deprecations and try to address them. Will keep you posted.

**Comment by uerceg** [comment]
HI @gilrodar

Should be addressed in our [latest release](https://github.com/adjust/ios_sdk/releases/tag/v4.24.0). If you spot anything that is still an issue, feel free to comment/reopen.

Cheers!
