### ISSUE TITLE
Invalid fingerprint through reverse proxy

### ISSUE THREAD

**Issue by andreisergiu98** [adjust/ios_sdk#474]
Hello! 
I'm using adjust to track installations on different platforms, including iOS and Android.
But recently I discovered that `app.adjust.com` is blacklisted by default by Adguard and uBlock on Android.
I tried to circumvent this by creating a proxy to `app.adjust.com` through our own domain, but then the tracking stopped working on iOS.

That's because the fingerprint is based on user's IP address. Since we are using a proxy, the IP address adjust is receiving, when the user clicks the url, is of our own proxy. When the user installs the app through appstore and opens the app, adjust is using the IP address of the user so fingerprints won't match.

I configured nginx like this:
``` 
server {
    listen 443 http2;
    server_name adjust.localhost;

    location / {
        proxy_pass  https://app.adjust.com;

        proxy_set_header        Connection      "";
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cookie_domain     adj.st          $host;
    }
}
```

Could proxying be supported by using `X-Forwarded-For` for the fingerprint if it's provided?

**Comment by ugi** [comment]
Hi @andreisergiu98 

Thanks for reporting this, but this question kinda goes out of scope of us who are replying in here, since it's not really SDK related question. Please contact your dedicated account manager with this question or if you don't have it, please send this to support@adjust.com.

Cheers
