### ISSUE TITLE
Incorrect log format

### ISSUE THREAD

**Issue by nburyak** [adjust/ios_sdk#476]
**Description:**
The error log message has an incorrect format: the path isn't displayed correctly.

**Actual result:**
`[Adjust]e: Error while creating -2107406816irectory`

**Expected result:**
`[Adjust]e: Error while creating /var/mobile/Containers/Data/Application/6E33F1CC-E7A2-40FC-A8CA-BF7D59C0CB72/Library/Application Support directory`

Patch with the fix:
```
diff --git a/Adjust/ADJUtil.m b/Adjust/ADJUtil.m
index 2941d759a0b8ccc4811a0a79575a0af18e543e11..68a5a2ff59d9655586a935002918255685d25b63 100644
--- a/Adjust/ADJUtil.m
+++ b/Adjust/ADJUtil.m
@@ -401,7 +401,7 @@ static NSString * const kDateFormat                 = @"yyyy-MM-dd'T'HH:mm:ss.SS
         NSError *error;
         [[NSFileManager defaultManager] createDirectoryAtPath:path withIntermediateDirectories:NO attributes:nil error:&error];
         if (error != nil) {
-            [[ADJAdjustFactory logger] error:@"Error while creating % directory", path];
+            [[ADJAdjustFactory logger] error:@"Error while creating %@ directory", path];
             [[ADJAdjustFactory logger] error:[error description]];
             return NO;
         }
```

**Comment by ugi** [comment]
Hey @nburyak 

Thanks for reporting. Fix will be part of next patch update. Will keep you posted.

Cheers

**Comment by uerceg** [comment]
Hi @nburyak 

Should be fixed in [latest release](https://github.com/adjust/ios_sdk/releases/tag/v4.24.0).

Thank you one more time for reporting!

Cheers
