### ISSUE TITLE
Safely call Adjust.adid()

### ISSUE THREAD

**Issue by slimshadystark** [adjust/ios_sdk#478]
Hello, 
I'm facing a problem retrieving the adjust id. Often I find the id nil and I suppose that `Adjust.adid()` even if it seems to be synchronous, actually is asynchronous. I think I could wait the `adjustSessionTrackingSucceeded` delegate function to be called and catch the Adjust id there but obviously it's a bad workaround. Is there a way to get the adjust id safely? Why don't you make the `Adjust.adid()` function asynchronous?
Thank you!

**Comment by uerceg** [comment]
Hi @slimshadystark 

All legit statements in your message except **adid** getter is actually synchronous. Back in the days synchronous getter seemed like okay idea for few users who requested this feature, with wider adoption, time has shown that asynchronous path definitely makes more sense. We tend to keep up with policy of not introducing breaking API and behaviour changes within same major version, thus keeping the getter still synchronous, but our next major version update to come is changing this (as a matter a fact, in our next major version development, we already addressed this) and all the getters in Adjust interface will be asynchronous.

Cheers!

**Comment by slimshadystark** [comment]
Hi @uerceg,
Thank you for the clarification. I appreciate your effort to make getters asynchronous in next major version and I'm looking forward to adopt it. 
Cheers!!!!

**Comment by uerceg** [comment]
👍 Will close this one for now, but in case anything on the topic pops up you wanna ask, feel free to comment/reopen.

Cheers

**Comment by callo90** [comment]
I'm having a similar problem @slimshadystark, I'm initializing the SDK before anything else but sometimes the `adid` is nil, might be related to synchronization. This is a very critical problem on my end. Any suggestions?

**Comment by blizkreeg** [comment]
Is the getAdid sync or async in the current version of the sdk?
