### ISSUE TITLE
Crashed: io.adjust.ActivityQueue

### ISSUE THREAD

**Issue by Harry626** [adjust/ios_sdk#485]
Crashed: io.adjust.ActivityQueue
0  IOKit                          0x1853e1c28 IOServiceAddInterestNotification + 44
1  UIKit                          0x18e94eec8 _MatchedBatteries + 112
2  UIKit                          0x18e94eec8 _MatchedBatteries + 112
3  UIKit                          0x18e94edcc -[UIDevice setBatteryMonitoringEnabled:] + 212
4  Adjust                         0x107f808e4 +[ADJSystemProfile chargingStatus] + 845 (ADJSystemProfile.m:845)
5  Adjust                         0x107f8c628 -[UIDevice(ADJAdditions) adjDeviceId:] + 256 (UIDevice+ADJAdditions.m:256)
6  Adjust                         0x107f6e238 -[ADJPackageBuilder getEventParameters:forEventPackage:] + 388 (ADJPackageBuilder.m:388)
7  Adjust                         0x107f6bb7c -[ADJPackageBuilder buildEventPackage:isInDelay:] + 77 (ADJPackageBuilder.m:77)
8  Adjust                         0x107f5a3d0 -[ADJActivityHandler eventI:event:] + 1126 (ADJActivityHandler.m:1126)
9  Adjust                         0x107f55764 __33-[ADJActivityHandler trackEvent:]_block_invoke + 275 (ADJActivityHandler.m:275)
10 Adjust                         0x107f8a0e4 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 780 (ADJUtil.m:780)
11 libdispatch.dylib              0x184af6a54 _dispatch_call_block_and_release + 24
12 libdispatch.dylib              0x184af6a14 _dispatch_client_callout + 16
13 libdispatch.dylib              0x184b0096c _dispatch_queue_serial_drain$VARIANT$mp + 528
14 libdispatch.dylib              0x184b012fc _dispatch_queue_invoke$VARIANT$mp + 340
15 libdispatch.dylib              0x184b01d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
16 libdispatch.dylib              0x184b0a03c _dispatch_workloop_worker_thread$VARIANT$mp + 644
17 libsystem_pthread.dylib        0x184d9ef1c _pthread_wqthread + 932
18 libsystem_pthread.dylib        0x184d9eb6c start_wqthread + 4

**Comment by uerceg** [comment]
Hi @Harry626 

Thanks for reporting. Are you able to reproduce this? If yes, what are the steps? Which SDK version are you using?

**Comment by Harry626** [comment]
> Hi @Harry626
> 
> Thanks for reporting. Are you able to reproduce this? If yes, what are the steps? Which SDK version are you using?

Unable to reproduce stably.
SDK version: 4.23.0

**Comment by uerceg** [comment]
How often do you see this crash happening and do you maybe have some info on devices which are being affected (which devices, which iOS version)?

**Comment by Harry626** [comment]
> How often do you see this crash happening and do you maybe have some info on devices which are being affected (which devices, which iOS version)?

26 crashes in the last 30 days, models include: iPhone6(11.2.5/11.0.0), iPhone5(10.3.3/10.3.4), iPhone 6s(11.0.3/11.2.6), iPhone 8 Plus(11.0.2) etc.

**Comment by uerceg** [comment]
Hey guys,

Part of the code mentioned in this issue doesn't exist since several versions ago in iOS SDK. Feel free to update to newest SDK version and it should not be happening anymore. In case you still face anything similar to this, please feel free to comment/reopen.

Cheers
