### ISSUE TITLE
'ADJThirdPartySharing.h' file not found

### ISSUE THREAD

**Issue by aregler** [adjust/ios_sdk#492]
Hey!

We integrated the Adjust framework via SPM. 
Since V4.25.0 we get the following error message and the framework cannot be built:

![image](https://user-images.githubusercontent.com/14072295/104907647-b3fa9b80-5985-11eb-95fa-17e7c258088f.png)

kind regards,

Arsatius

**Comment by uerceg** [comment]
Hi @aregler 

Thanks for reporting this, we're on it and will keep you posted.

**Comment by uerceg** [comment]
Hi @aregler 

And thanks one more time. We have just released [v4.25.1](https://github.com/adjust/ios_sdk/releases/tag/v4.25.1) with fix for this issue. If you can maybe give it a shot and let us know if the error is gone with that version, would be great.

Thanks in advance!

**Comment by aregler** [comment]
Hi @uerceg,

now it builds. Thank you and your team for the quick fix. Have a nice day 👍🏻
