### ISSUE TITLE
AppTrackingTransparency and ADJConfig.allowIdfaReading

### ISSUE THREAD

**Issue by siriusdely** [adjust/ios_sdk#497]
Hello,

I have a question which quite related to #450 & #459.

Without having to do the _delayed SDK initialization_ and all kind of [issues](https://github.com/adjust/ios_sdk#issues-with-delayed-sdk-initialisation) may come with it.

Is there a way to defer the setting of ADJConfig.allowIdfaReading to later after AppTrackingTransparency permission request is shown and based on user's answer to it?

CMIIW, seems that it is not possible to save the reference on our app, and then update it later because it is a [`@property copy`](https://github.com/adjust/ios_sdk/blob/58f0842/Adjust/ADJActivityHandler.m#L104).

If so, what is the proper way to _initialised_ Adjust SDK based on user's `AppTrackingTransparency` consent?

**Comment by nicorsm** [comment]
Following this thread since I'm facing the same issue.

**Comment by uerceg** [comment]
Hi guys,

Sorry for delay on this one.

In particular thing what you're asking (set **allowIdfaReading** at some later point when SDK might already be initialised) is not possible. All the settings we have as part of **ADJConfig** instance need to be set prior to SDK initialisation and can't be changed during the runtime.

SDK initialisation flow is independent from ATT dialog flow, regardless which method you choose for showing the ATT dialog (standard iOS API or Adjust SDK wrapper method). And pretty much whenever SDK is about to send something, we will send value of IDFA and ATT status which are current for the user at that moment. Meaning before user gives any consent (in post iOS 14.5 world) we will be sending that ATT status is not determined and IDFA zeroed. After that we can either end up with reporting that status is denied and IDFA zeroed OR that status is allowed and IDFA has value.

@siriusdely Seems to me that you would like somehow to instruct to the SDK to send or not send IDFA in specific moments during runtime. Can you maybe clarify a bit more what exactly are you trying to achieve?

**Comment by siriusdely** [comment]
Hi @uerceg, thank you for the answer, it really helps.

My confusion was caused by my lack of understanding about the difference behavior of IDFA before vs after iOS 14.5. And wanted to prevent IDFA access before user's ATT consent (pre 14.5). But now, iOS 14.5 is coming anytime soon, it doesn't really matter anymore.
