### ISSUE TITLE
FR: Support Xcframeworks

### ISSUE THREAD

**Issue by jesusmateos1234** [adjust/ios_sdk#505]
We'll in love if you support xcframeworks

**Comment by S2Ler** [comment]
Up

**Comment by jesusmateos1234** [comment]
Thanks for all @S2Ler

**Comment by jesusmateos1234** [comment]
@S2Ler @uerceg last version 4.29.1 not has precompiled assets :/

**Comment by markusfassbender-parshipgroup** [comment]
Push

**Comment by Aditi3** [comment]
XCFramework support has been added in our latest release [version 4.32.1](https://github.com/adjust/ios_sdk/releases/tag/v4.32.1). 

In case you have any other questions/concerns about this one, feel free to comment/reopen it. Cheers!
