### ISSUE TITLE
ADJConfig properties not getting set

### ISSUE THREAD

**Issue by mockaccount-cs** [adjust/ios_sdk#506]
Hello,
I am using version 4.26.1 of the Adjust SDK  and some of the `ADJConfig` properties are not getting set. Here is an example of what I am doing:

```
class MockAdjustDelegateClass: NSObject, AdjustDelegate { }
// ...
class AdjustWrapper {
  func initialize() {
      guard let config = ADJConfig(appToken: "test", environment: ADJEnvironmentSandbox) else {
             return
      }
      config.logLevel = ADJLogLevelAssert
      config.delegate = MockAdjustDelegateClass()
     print("breakpoint here")
   }
}

var wrapper = AdjustWrapper()
wrapper.initialize()

```

After placing a breakpoint at the `print("breakpoint here")`, this is the output of `po`:

![AdjustRemoteCommand_swift](https://user-images.githubusercontent.com/69769920/107716052-c66aab00-6c8d-11eb-81ec-8d0e251f8e2b.png)

What am I doing wrong?

UPDATE: I managed to set the delegate, but while testing the sample app, I noticed that the `logLevel` also does not get set after [this line](https://github.com/adjust/ios_sdk/blob/a9985f222dcdc47c3fc1208099ad1e311c890fc2/examples/AdjustExample-Swift/AdjustExample-Swift/AppDelegate.swift#L21). 

Please advise. Thanks!

**Comment by uerceg** [comment]
In case this is still an issue for you and you have additional questions, feel free to comment/reopen. Cheers.
