### ISSUE TITLE
ADJAdRevenueSourceMopub string value.

### ISSUE THREAD

**Issue by pieomy** [adjust/ios_sdk#512]
Hi,

I have a little problem `ADJAdRevenueSourceMopub` also `ADJEnvironmentSandbox` and `ADJEnvironmentProduction` return always empty for me (*Note this is my IDE problem), so I ignore this and init sdk with string like 'production' or 'sandbox' (this is worked) but I don't know `ADJAdRevenueSourceMopub` string value, is that 'Mopub' or 'RevenueSourceMopub' or else?

I am trying to use this and I need ADJAdRevenueSourceMopub string value, please can you tell me to right string value for that.
 `[Adjust trackAdRevenue:ADJAdRevenueSourceMopub payload:[impressionData jsonRepresentation]`

*Note: I am using Delphi for delevoping, I can not fix return empty problem and I know Adjust doesn't support this tool, I think I need to just right string for ADJAdRevenueSourceMopub.

Thank you.

**Comment by uerceg** [comment]
Hi @pieomy 

You can find values of all the constants which our SDK uses in [here](https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.m#L22-L46). It should make no difference if you choose to pass string value directly.

Let us know in case you have any further questions.

Cheers

**Comment by pieomy** [comment]
Thank you! I will try 'mopub' and I think it will be work.
