### ISSUE TITLE
Adjust and ATT

### ISSUE THREAD

**Issue by Rishe740** [adjust/ios_sdk#513]
Hello!

I just want to clarify some questions about ATT and how the SDK works. The README is a bit unclear on this topic, sorry. 

1. My Adjust configuration is done on `appDidFinishingLaunching`. To prepare my app for iOS 14.5, do I now need to explicitly set `allowIdfaReading` to `false` on startup ? Kinda related to https://github.com/adjust/ios_sdk/issues/497. 
    - If so, how can it change `allowIdfaReading` to `true` after the user's ATT choice? 
2. Does the SDK behaves the same on IDFA between iOS 14.5 app and < iOS 14.5 app ? 

Thanks in advance, help is appreciated 🙏

**Comment by uerceg** [comment]
Hi @Rishe740 

1. Of course, it depends on what is your use case and what are you trying to achieve, but setting that property to `false` would instruct to our SDK not to send `idfa` parameter to our backend at all. Answer to if this can be toggled back ON later is no, I wrote a bit more detailed explanation in [comment](https://github.com/adjust/ios_sdk/issues/497#issuecomment-797159190) on that issue.
2. Apple's API for reading IDFA didn't change at all, so reading of the IDFA value itself pre and post iOS 14.5 is pretty much the same. What has changed in the past few iOS releases is the mechanism which (dis)allows access to IDFA (LAT in pre iOS 14 days, Allow Apps To Request To Track + ATT dialog in iOS 14 days + the fact that as of iOS 14.5 IDFA will not be accessible anymore unless ATT dialog is displayed and user allowed access to it). But SDK is built in a way to handle all those various scenarios.

In case you have any further questions, feel free to ping.

Cheers

**Comment by Rishe740** [comment]
Everything is clear now, thank you very much!
