### ISSUE TITLE
Sending multiple trackEvent causes memory crash

### ISSUE THREAD

**Issue by sanichdaniel** [adjust/ios_sdk#515]
When Sending numerous (more than 1000) trackEvent in short time (ex. 1~2 minute) app's memory usage grows up exponentially and crashes.
Xcode shows popup `App terminated due to memory issue`

When I set ADJConfig `eventBufferingEnabled` to true, app's memory starts to grow after 1minute and crashes

Below shows example image
<img width="972" alt="스크린샷 2021-03-18 오후 12 40 48" src="https://user-images.githubusercontent.com/29453786/111569981-2bfb0b80-87e7-11eb-9772-8cf5577e4ee4.png">

**Comment by uerceg** [comment]
Hi @sanichdaniel 

Give v4.28.0 a shot, hopefully this should be fixed with it. In case you still encounter the issue with that version, feel free to comment/reopen.

Cheers
