### ISSUE TITLE
Please make sending the "fb_anon_id" optional

### ISSUE THREAD

**Issue by gfoldv** [adjust/ios_sdk#517]
For those who are not using Facebook related services with Adjust this is a serious user privacy concern.

**Comment by uerceg** [comment]
Hi @gfoldv 

Sending was mandated by FB (and we are part of FB MMP program). Also ID is only sent to Facebook if the advertiser activates the FB module and in other cases it is simply being dropped.

In case you have further questions about this, feel free to ping in here or even better your dedicated account manager or support@adjust.com where you can definitely get further clarifications on this topic in case you need any.

Cheers
