### ISSUE TITLE
security key update

### ISSUE THREAD

**Issue by T-10810** [adjust/ios_sdk#521]
security key update 

_Originally posted by @T-10810 in https://github.com/git-touch/git-touch/pull/217#issuecomment-803689183_

**Comment by Lukas-Batema** [comment]
This has nothing to do with that PR. It is just an MD File for how to propose security issues, and what versions still support security updates. It has no code functionality, besides a README-like Markdown file. Please check the Files Changed tab in the PR you originally linked! Thanks!
