### ISSUE TITLE
data residency feature (ADJDataResidencyEU)?

### ISSUE THREAD

**Issue by gerchicov-bp** [adjust/ios_sdk#528]
Could you please explain what does it mean?

**Comment by uerceg** [comment]
Hi @gerchicov-bp

It's a beta feature currently which we rolled out and whose purpose is to allow publishers to have our SDK to aim at our EU endpoints and to have all data we store for that app(s) to reside only within EU. It's a beta feature at this moment and in case you're interested in using it, feel free to ping your dedicated account manager if you have one or if not, our support team (support@adjust.com).

Cheers
