### ISSUE TITLE
Does the current "criteo" branch follow the latest "master" branch?

### ISSUE THREAD

**Issue by shindyu** [adjust/ios_sdk#529]
Hi! Our project uses "criteo" branch.
Does the current "criteo" branch follow the latest "master" branch?
I think the "criteo" branch needs to incorporate the v4.28 fix in order to submit it to the App Store.

Thank you.

**Comment by uerceg** [comment]
Hi @shindyu 

[Yes](https://github.com/adjust/ios_sdk/blob/criteo/VERSION). Give it a shot and let us know if 4.28.0 is running under the hood (it should).

**Comment by uerceg** [comment]
Closing this one. In case you are still facing some issues with `criteo` branch, feel free to comment/reopen.

Cheers
