### ISSUE TITLE
When will the 4.2.9 release be updated

### ISSUE THREAD

**Issue by cangswift** [adjust/ios_sdk#532]
When will the 4.2.9 release be updated

**Comment by uerceg** [comment]
Hi @cangswift 

Still no exact ETA, but we're working on it. Out of curiosity, why are you asking? Are you expecting something in particular to see in this version?

**Comment by cangswift** [comment]
@uerceg About Apple's ATT permission requirements. Are AdjustSDK AD attribution problems working properly?Since our app is not easy to update, we want to confirm the stable version SDK of IOS 14.5,Thank you!

**Comment by uerceg** [comment]
@cangswift 

Everything needed for that topic is part of the several releases behind us including the latest one. So feel free to give it a shot and in case you have any further questions, feel free to comment/reopen.

Cheers
