### ISSUE TITLE
Must adjust get IDFA parameters to track ad users?

### ISSUE THREAD

**Issue by Kangqj** [adjust/ios_sdk#533]
Under iOS14.5 system, if the user does not agree to obtain IDFA permission, can not track whether the user is an advertising user?

if we don't agree IDFA permission, this callback method will not be executed.
'- (void)adjustAttributionChanged:(ADJAttribution *)attribution'

**Comment by uerceg** [comment]
Hi @Kangqj 

Our SDK functionality will not be affected by the fact if user has chosen to allow to be tracked or not. Depending on user's choice, we will communicate this information to our backend and IDFA parameter we send will either contain value (if user gave consent to be tracked) or be zeroed (if consent was not given).

`adjustAttributionChanged:` callback will be triggered regardless of the user's choice as well. It will be triggered to let you know about the user's attribution value right after install has been made and in future any time when attribution for the given user changes.

In case you have any other questions, feel free to ask.
