### ISSUE TITLE
'ADJAdRevenue.h' file not found

### ISSUE THREAD

**Issue by kaybutter** [adjust/ios_sdk#535]
When integrating the AdjustSDK 4.29.0  using SPM, the SDK won't compile, complaining about the missing 'ADJAdRevenue.h'

As far as I can tell, the header exists, but is not located in the include folder, which is why the umbrella header can't just import it.

**Comment by andrew-shoonya** [comment]
I can confirm the header does not exist in the `include/` folder. Line 15 of `Adjust/Adjust.h`, which reads `#import "ADJAdRevenue.h",` is the newest edit. Adding to the `include/` folder a macOS alias to the missing header makes Xcode thrash. But...adding a Unix-style symlink lets me build my project.

```
% cd /Users/.../Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/ios_sdk/Adjust/include
% ln -s ../ADJAdRevenue.h ADJAdRevenue.h

```

**Comment by travismmorgan** [comment]
Same issue. I am using Swift Package Manager, Xcode 12.5, Adjust 4.29.0

**Comment by uerceg** [comment]
Hey guys,

Thanks for reporting, will be fixed soon. Will keep you posted.

**Comment by uerceg** [comment]
We just released [v4.29.1](https://github.com/adjust/ios_sdk/releases/tag/v4.29.1) with fix for this issue. Let us know if worked for you.

**Comment by pvroosendaal** [comment]
Same issue here. Will check the latest version right away.

**Comment by kaybutter** [comment]
Just tested the new version and it seems to work for me 👍

**Comment by pvroosendaal** [comment]
Yes, it works! Thanks very much.

**Comment by uerceg** [comment]
Great! Thank you guys for the feedback. Closing this one, feel free to reopen if needed. Cheers.
