### ISSUE TITLE
Adjust.requestTrackingAuthorization does not show the permission alert. 

### ISSUE THREAD

**Issue by muratyilmaz** [adjust/ios_sdk#538]
I have installed Adjust 4.29.0. But when I request tracking permission using requestTrackingAuthorization alert does not show.
But ATTrackingManager.requestTrackingAuthorization is working.

**Comment by muratyilmaz** [comment]
Os ver 14.4.2

**Comment by muratyilmaz** [comment]
ok resolved. 

AppTrackingTransparency.framework - This framework is needed in iOS 14 and later for SDK to be able to wrap user's tracking consent dialog and access to value of the user's consent to be tracked or not.

**Comment by euroboy** [comment]
I added **AppTrackingTransparency.framework** but alert still not showing. `ATTrackingManager.requestTrackingAuthorization` shows the alert as intended.
