### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by mtarekswvl** [adjust/ios_sdk#539]
Since updating to Adjust 4.28.0 from Adjust 4.26.1 we've been receiving a lot of crashes from Adjust SDK.

Fatal Exception: NSInvalidArgumentException
*** -[_NSPlaceholderData initWithBase64EncodedString:options:]: nil string argument
_hidden#59_

> Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x184070128 __exceptionPreprocess
1  libobjc.A.dylib                0x197d83480 objc_exception_throw
2  Foundation                     0x1852b68f8 -[NSDateInterval copyWithZone:]
3  Swvl                           0x1001e05c0 _hidden#59_
4  CoreFoundation                 0x184074b60 __invoking___
5  CoreFoundation                 0x183f565e0 -[NSInvocation invoke]
6  Adjust                         0x101197b88 _hidden#1700_ + 311 (__hidden#1835_:311)
7  Adjust                         0x1011972bc _hidden#1691_ + 173 (__hidden#1835_:173)
8  Adjust                         0x1011970bc _hidden#1690_ + 145 (__hidden#1835_:145)
9  Adjust                         0x1011810fc _hidden#95_ + 608 (__hidden#814_:608)
10 Adjust                         0x101180530 _hidden#86_ + 419 (__hidden#814_:419)
11 Adjust                         0x101187d98 _hidden#187_ + 1731 (__hidden#814_:1731)
12 libdispatch.dylib              0x183ca72b0 _dispatch_call_block_and_release
13 libdispatch.dylib              0x183ca8298 _dispatch_client_callout
14 libdispatch.dylib              0x183c8073c _dispatch_queue_override_invoke
15 libdispatch.dylib              0x183c8d2cc _dispatch_root_queue_drain
16 libdispatch.dylib              0x183c8da64 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0x1cc375580 _pthread_wqthread
18 libsystem_pthread.dylib        0x1cc37886c start_wqthread

Also we're receiving this crash.
Fatal Exception: NSInvalidArgumentException
*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil
_hidden#59_

> Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1961d586c __exceptionPreprocess
1  libobjc.A.dylib                0x1ab1f1c50 objc_exception_throw
2  CoreFoundation                 0x196245e1c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1962524c0 -[__NSDictionaryM setObject:forKeyedSubscript:].cold.2
4  CoreFoundation                 0x1960bb118 -[__NSDictionaryM setObject:forKeyedSubscript:]
5  Swvl                           0x104633d20 _hidden#59_
6  CoreFoundation                 0x1961da8f4 __invoking___
7  CoreFoundation                 0x1960b1df8 -[NSInvocation invoke]
8  Adjust                         0x1055ebb94 _hidden#1700_ + 311 (__hidden#1835_:311)
9  Adjust                         0x1055eb2c8 _hidden#1691_ + 173 (__hidden#1835_:173)
10 Adjust                         0x1055eb0c8 _hidden#1690_ + 145 (__hidden#1835_:145)
11 Adjust                         0x1055d50f4 _hidden#95_ + 608 (__hidden#814_:608)
12 Adjust                         0x1055d4528 _hidden#86_ + 419 (__hidden#814_:419)
13 Adjust                         0x1055dbd98 _hidden#187_ + 1731 (__hidden#814_:1731)
14 libdispatch.dylib              0x195dc824c _dispatch_call_block_and_release
15 libdispatch.dylib              0x195dc9db0 _dispatch_client_callout
16 libdispatch.dylib              0x195dccddc _dispatch_queue_override_invoke
17 libdispatch.dylib              0x195dda93c _dispatch_root_queue_drain
18 libdispatch.dylib              0x195ddb120 _dispatch_worker_thread2
19 libsystem_pthread.dylib        0x1e1c857d8 _pthread_wqthread
20 libsystem_pthread.dylib        0x1e1c8c76c start_wqthread

**Comment by uerceg** [comment]
Hi @mtarekswvl 

Thanks for reporting this. Is there any chance to see what is hidden in these lines:

```
6 Adjust 0x101197b88 hidden#1700 + 311 (_hidden#1835:311)
7 Adjust 0x1011972bc hidden#1691 + 173 (_hidden#1835:173)
8 Adjust 0x1011970bc hidden#1690 + 145 (_hidden#1835:145)
9 Adjust 0x1011810fc hidden#95 + 608 (_hidden#814:608)
10 Adjust 0x101180530 hidden#86 + 419 (_hidden#814:419)
11 Adjust 0x101187d98 hidden#187 + 1731 (_hidden#814:1731)
```

```
8 Adjust 0x1055ebb94 hidden#1700 + 311 (_hidden#1835:311)
9 Adjust 0x1055eb2c8 hidden#1691 + 173 (_hidden#1835:173)
10 Adjust 0x1055eb0c8 hidden#1690 + 145 (_hidden#1835:145)
11 Adjust 0x1055d50f4 hidden#95 + 608 (_hidden#814:608)
12 Adjust 0x1055d4528 hidden#86 + 419 (_hidden#814:419)
13 Adjust 0x1055dbd98 hidden#187 + 1731 (_hidden#814:1731)
```
?

**Comment by mtarekswvl** [comment]
Hi @uerceg
I am not exactly sure why are those lines hidden. Adjust SDK is the only SDK we're using that is producing that kind of hidden stack traces. Do you have any idea why is this happening?

**Comment by uerceg** [comment]
No idea TBH. Usually lines belonging to our SDK are always visible in stack traces which we get. What tool are you using to get these crash stack traces?

**Comment by mtarekswvl** [comment]
@uerceg Firebase's Crashlytics

**Comment by mtarekswvl** [comment]
@uerceg We're using Cocoapods to add Adjust into our app. Also please note that the stack trace is also hidden in Xcode's organizer.

**Comment by uerceg** [comment]
Hm. I had doubt that maybe you were using dynamic framework, but seems not to be the case. Honestly not sure how to approach this since without actual lines where crash is happening, we're not even sure where to look. Can you maybe reproduce any of these crashes on your own?

**Comment by mtarekswvl** [comment]
@uerceg Here's a new stack trace that is not hidden.
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1a1de65b4 __exceptionPreprocess
1  libobjc.A.dylib                0x1b68657a8 objc_exception_throw
2  Foundation                     0x1a30bec68 -[NSDateInterval copyWithZone:]
3  Swvl                           0x104b0b81c _hidden#59_
4  CoreFoundation                 0x1a1deb874 __invoking___
5  CoreFoundation                 0x1a1cbeba4 -[NSInvocation invoke]
6  Adjust                         0x105b9c6e8 -[ADJPackageBuilder signWithSigV2Plugin:] + 311 (ADJPackageBuilder.m:311)
7  Adjust                         0x105b9be1c -[ADJPackageBuilder buildClickPackage:extraParameters:] + 173 (ADJPackageBuilder.m:173)
8  Adjust                         0x105b9bc1c -[ADJPackageBuilder buildClickPackage:token:errorCodeNumber:] + 145 (ADJPackageBuilder.m:145)
9  Adjust                         0x105b85d00 -[ADJActivityHandler sendAdServicesClickPackage:token:errorCodeNumber:] + 608 (ADJActivityHandler.m:608)
10 Adjust                         0x105b85134 -[ADJActivityHandler setAdServicesAttributionToken:error:] + 419 (ADJActivityHandler.m:419)
11 Adjust                         0x105b8c98c __53-[ADJActivityHandler checkForAdServicesAttributionI:]_block_invoke + 1731 (ADJActivityHandler.m:1731)
12 libdispatch.dylib              0x1a19d1a54 _dispatch_call_block_and_release
13 libdispatch.dylib              0x1a19d37ec _dispatch_client_callout
14 libdispatch.dylib              0x1a19d6938 _dispatch_queue_override_invoke
15 libdispatch.dylib              0x1a19e4fb0 _dispatch_root_queue_drain
16 libdispatch.dylib              0x1a19e57a8 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0x1ed91e768 _pthread_wqthread
18 libsystem_pthread.dylib        0x1ed92574c start_wqthread
```

**Comment by uerceg** [comment]
Hi @mtarekswvl 

Thanks for providing this stack trace, it gives us way more clarity now. You'll get pinged soon with instructions what to do about this issue.

**Comment by dimim** [comment]
Hello @mtarekswvl.

Thank you for getting in touch. The issue has been examined. Your Account Manager will get in touch with the next steps that should address the issue present. Let's keep this issue open until it's resolved.

**Comment by sceren** [comment]
Hello @mtarekswvl 
Account Management team would like to send you an email with the instructions and for that we need your email address and account name in Adjust. You can also send an email to support@adjust.com and we can reply to that with the instructions right away.

**Comment by safa-ads** [comment]
@sceren we sent an email to support@adjust.com regarding this matter.
