### ISSUE TITLE
[Xcode 13b1] `attribution` multiple candidates

### ISSUE THREAD

**Issue by amaurydavid** [adjust/ios_sdk#546]
When building Adjust 4.28.0 with Xcode 13b1, this code generates two errors:
```objc
+ (ADJAttribution *)attribution {
    @synchronized (self) {
        return [[Adjust getInstance] attribution];
    }
}
```
> 1. Multiple methods named 'attribution' found with mismatched result, parameter type or attributes
> 2. Implicit conversion of 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') to 'ADJAttribution * _Nullable' is disallowed with ARC

Those errors seem to be caused by the `Adjust.getInstance` function to return an `id` instead of an `instancetype`. With the new `NSURLRequest.attribution` property from iOS 15, Xcode doesn't know which one to use.

**Comment by uerceg** [comment]
Hey guys,

In case you don't follow https://github.com/adjust/ios_sdk/pull/547, we have just released iOS SDK v4.29.3 update which should hopefully address this issue.

Cheers!
