### ISSUE TITLE
[WARNING] Umbrella header does not include header 'ADJLinkResolution.h'

### ISSUE THREAD

**Issue by drlukas6** [adjust/ios_sdk#550]
Affected versions: >= 4.29.2

During compilation the following warning occurs:

`Umbrella header for module 'Adjust' does not include header 'ADJLinkResolution.h'`

I suppose adding that header to `adjust.h` would fix the warning?

**Comment by uerceg** [comment]
Hi @drlukas6 

Yeah, sounds like it's related to that. How are you adding Adjust SDK to your app?

**Comment by drlukas6** [comment]
Hi!

I'm using SPM configured as `4.29.3 - Next Major` but during debugging i noticed this occurs also with `4.29.2`

**Comment by uerceg** [comment]
Ah, SPM, thanks. We'll investigate on our end. Will keep you posted.

**Comment by uerceg** [comment]
Should hopefully be fixed in latest [v4.29.4](https://github.com/adjust/ios_sdk/releases/tag/v4.29.4) release. In case you still face the issue with this version, feel free to comment / reopen. Cheers!
