### ISSUE TITLE
(error)No such module 'AdjustBridge' on Swift

### ISSUE THREAD

**Issue by Toshiki-Shimosawa** [adjust/ios_sdk#552]
I described `pod 'Adjust / WebBridge','~> 4.29.3'` in the podfile, and pod install & pod update
and I wrote the following in the file I want to use, but only Adjust Bridge causes an error and can not be used
```
import Adjust
import AdjustBridge
```
`No such module 'AdjustBridge'`

I'm just getting started with swift so please let me know

**Comment by hungwei0331** [comment]
I face same issue,
Could I ask do you resolve it ?

**Comment by uerceg** [comment]
Sorry guys for the delay. In case you are still facing this issue with the latest SDK (and bridge) version, please feel free to comment / reopen the issue. Cheers.
