### ISSUE TITLE
Xcode 13 b3 - SwiftPackageManager error App Extensions

### ISSUE THREAD

**Issue by mattiacantalu** [adjust/ios_sdk#555]
Using SPM with latest version of Adjust `4.29.3` and `Xcode 13.0 beta 3 (13A5192i)` the App Extensions targets don't compile due:
```
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```
and
```
'openURL:' is unavailable: not available on iOS (App Extension)
```

**Comment by akbashev** [comment]
Probably due to:
```
Swift Packages
Resolved in Xcode 13 Beta 3
Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)
```

**Comment by mattiacantalu** [comment]
PR opened here https://github.com/adjust/ios_sdk/pull/559

**Comment by mattiacantalu** [comment]
@uerceg any news to move on above PR?

**Comment by uerceg** [comment]
It's actually under our internal review and hopefully part of the next patch release. No super specific ETA, but I hope we can have it live by the end of the next week.

**Comment by markusfassbender-parshipgroup** [comment]
Still open?

**Comment by uerceg** [comment]
Yep (a bit of back and forth in the [PR](https://github.com/adjust/ios_sdk/pull/559)). Hopefully closed by Friday. Will keep you posted.

**Comment by uerceg** [comment]
Should hopefully be fixed in latest [v4.29.4](https://github.com/adjust/ios_sdk/releases/tag/v4.29.4) release. In case you still face the issue with this version, feel free to comment / reopen. Cheers!

**Comment by mattiacantalu** [comment]
Swift Packages
Resolved in Xcode 13 Beta 5

    You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)

**Comment by uerceg** [comment]
Of course. :) Thanks for sharing, we're gonna check out if we can cut some annotations we have in place with latest patch release.
