### ISSUE TITLE
Even after requestTrackingAuthorization authorize permission from user adjust says No user consent

### ISSUE THREAD

**Issue by sheshnathiicmr** [adjust/ios_sdk#564]
I am using adjust wrapper to get tracking authorization from the user sample code below

```
override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 14, *) {
            Adjust.requestTrackingAuthorization { [weak self] status in
                print("Tracking status: \(status)")
                if let adjust = Adjust.attribution() {
                    if let network = adjust.network {
                        print("network: \(network)")
                    }
                }
            }
        }else {
           //fallback
        }
    }
```

even after the user allows to track calling adjust.network returns "No user consent"

**Comment by sohail-dragon** [comment]
This is happening with use as well. ATT status has been granted but getting "No user consent".
1. Launch app -> "No user consent"
2. Grant ATT via native modal
3. Re-launch app -> "No user consent"
4. Attribution status correctly updated on adjust testing console dashboard
5. Wait a few hours
6. Re-launch app -> Attribution correctly appears
7. Force re-attribute using a deeplink
8. Attribution status in app -> "No user consent"
9. Attribution status on testing console -> Updated to new track from force re-attribution.

We're using `react-native-adjust: 4.29.4` which should be using `iOS@v4.29.5` and `Android@v4.28.4`. We're also in touch with adjust supporting regarding this as it's affecting a live campaign
