### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x268b2cc70)

### ISSUE THREAD

**Issue by qq850405** [adjust/ios_sdk#567]
We update 4.29.6 version discover this crash : 
EXC_BAD_ACCESS (code=1, address=0x467261656c6
<img width="1305" alt="截屏2021-09-28 下午4 03 14" src="https://user-images.githubusercontent.com/21189991/135048061-72770b90-8c95-4dd1-a504-7e3b9c96a7b4.png">
<img width="412" alt="截屏2021-09-28 下午4 15 49" src="https://user-images.githubusercontent.com/21189991/135049881-e05c3b87-2039-41c6-af86-8d52a948a8a3.png">

**Comment by uerceg** [comment]
Hi @qq850405,

Thank you for reporting this. Few questions:

1. Are you able to reproduce this locally? If yes, can you give us the steps to reproduce it on our end?
2. Are you using setting [URL strategy](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJConfig.h#L215) on your `ADJConfig` object in your SDK setup and if yes, what's the value you're setting in there?

**Comment by qq850405** [comment]
1. We are run 'Start the active scheme' [https://github.com/adjust/ios_sdk/pull/547#issue-914377180](url)
2. We no modify ADJConfig

**Comment by qq850405** [comment]
Hi,
1.  I updated to version 4.29.6 to try and fix #547, and it crashes right after I run "Start the active Scheme".
2. I didn't make any modifications to it.
