### ISSUE TITLE
#567

### ISSUE THREAD

**Issue by qq850405** [adjust/ios_sdk#568]
We update 4.29.6 version discover this crash : 
EXC_BAD_ACCESS (code=1, address=0x467261656c6
<img width="1305" alt="截屏2021-09-28 下午4 03 14" src="https://user-images.githubusercontent.com/21189991/135048061-72770b90-8c95-4dd1-a504-7e3b9c96a7b4.png">
<img width="412" alt="截屏2021-09-28 下午4 15 49" src="https://user-images.githubusercontent.com/21189991/135049881-e05c3b87-2039-41c6-af86-8d52a948a8a3.png">

<img width="922" alt="截屏2021-09-29 下午3 34 33" src="https://user-images.githubusercontent.com/21189991/135223589-98cfd967-7f88-4114-8673-6e23a3066592.png">
Hi,

1. I updated to version 4.29.6 to try and fix Fix: Xcode 13 build errors #547, and it crashes right after I run "Start the active Scheme".
2. I didn't make any modifications to it.

**Comment by uerceg** [comment]
Hey @qq850405,

Are you still facing this issue with the latest SDK version?
