### ISSUE TITLE
Crashed: io.adjust.PackageQueue

### ISSUE THREAD

**Issue by travismmorgan** [adjust/ios_sdk#574]
SDK Version: 4.29.6
OS: iOS 12.4.0-12.5.5
Device: iPhone

Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x140244 CFBasicHashFindBucket
1  CoreFoundation                 0x77a40 CFDictionaryGetValue
2  �hzo                          0x29c48 (Missing)
3  �hzo                          0xc10c (Missing)
4  �hzo                          0xbcdc (Missing)
5  Foundation                     0x1304a8 -[NSString localizedStandardCompare:]
6  CoreFoundation                 0xb5738 __CFSimpleMergeSort
7  CoreFoundation                 0xb57e0 __CFSimpleMergeSort
8  CoreFoundation                 0xb57e0 __CFSimpleMergeSort
9  CoreFoundation                 0xb57e0 __CFSimpleMergeSort
10 CoreFoundation                 0xb57c8 __CFSimpleMergeSort
11 CoreFoundation                 0xb525c CFSortIndexes
12 CoreFoundation                 0x59a0 -[NSArray sortedArrayFromRange:options:usingComparator:]
13 CoreFoundation                 0x8528 -[NSArray sortedArrayUsingSelector:]
14 Rain                           0x41b014 -[ADJActivityPackage extendedString] + 24 (ADJActivityPackage.m:24)
15 Rain                           0x432ed0 -[ADJPackageHandler addI:package:] + 216 (ADJPackageHandler.m:216)
16 Rain                           0x441150 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 813 (ADJUtil.m:813)
17 libdispatch.dylib              0x5fa38 _dispatch_call_block_and_release
18 libdispatch.dylib              0x607d4 _dispatch_client_callout
19 libdispatch.dylib              0x9324 _dispatch_lane_serial_drain$VARIANT$mp
20 libdispatch.dylib              0x9e40 _dispatch_lane_invoke$VARIANT$mp
21 libdispatch.dylib              0x124ac _dispatch_workloop_worker_thread
22 libsystem_pthread.dylib        0xc114 _pthread_wqthread
23 libsystem_pthread.dylib        0xecd4 start_wqthread

**Comment by genadyb** [comment]
Hello @travismmorgan. 
Thank you for your report. We are looking into this issue.
Could you post couple of full crash reports including Exception information and other threads info as well, please?
It will help us.
Thank you for your kind assistance.
Genady.

**Comment by uerceg** [comment]
In case you are experiencing this issue still with iOS SDK v4.33.4 (or later), please feel free to comment / reopen. Cheers.
