### ISSUE TITLE
Crash [__NSArrayI objectAtindex:]: message sent to deallocated instance

### ISSUE THREAD

**Issue by satan0124** [adjust/ios_sdk#576]
![image](https://user-images.githubusercontent.com/78458479/140472483-6394c508-db54-4c69-8634-3ff1a1bc1418.png)
![image](https://user-images.githubusercontent.com/78458479/140472501-f8f169b5-a354-474f-a5c1-0da362b08bd3.png)

I updated to version 4.29.6 to try and fix Fix: Xcode 13 build errors Fix: Xcode 13 build errors #547, and it crashes after I run "Start the active Scheme".

**Comment by uerceg** [comment]
Hi @satan0124 & @perovovao,

Are you always able to reproduce this issue? If yes, can you provide us steps to do so? Especially interested in:

- SDK version you are using (seems like latest one is being talked about, but just to make sure)
- How does you SDK initialization code look like?
- Which device are you using?

**Comment by uerceg** [comment]
In case you're still facing this issue with latest SDK version, feel free to comment / reopen. Cheers.
