### ISSUE TITLE
Adyen3DS2.ADYRuntimeError Code=1 "Secure channel setup failed."

### ISSUE THREAD

**Issue by Jack25apr** [adjust/ios_sdk#581]
Hello, 
We got successfully implemented test environment (iOS Drop-in + our "proxy"-backend)
[iOS,  Adyen (4.5.0), Adyen3DS2 (2.2.4)] 

Then we wanted to test as much as possible in live.

During testing in live with live card 5168 **** **** **** (not stored method, just newly entered)
I've got the next code after testing in live environment inside Framework:
com.adyen.Adyen3DS2.ADYRuntimeError Code=1 "Secure channel setup failed."

I cant go deeper - internals are hidden the framework.

(Some live card gave success - "no funds" - thats ok).

The last request as I can see with Charles (error persists on that card without proxy-tool ):

https://checkoutshopper-live.adyen.com/checkoutshopper/v1/submitThreeDS2Fingerprint?clientKey=live_H**********S

Request:
`{
  "clientKey": "live_HS",
  "fingerprintResult": "e*******9",
  "paymentData": "Ag***************=="
}`

Response: 200

`{
  "action": {
    "authorisationToken": "Ab******=",
    "subtype": "challenge",
    "token": "ey*******==",
    "type": "threeDS2"
  },
  "type": "action"
}`

Any ideas ?

**Comment by uerceg** [comment]
Hi @Jack25apr

Are you sure you posted this question in the right repository?

Sounds unrelated to Adjust iOS SDK.

**Comment by Jack25apr** [comment]
Sorry, my bad. closed.
