### ISSUE TITLE
How to delay the start of an app using swift

### ISSUE THREAD

**Issue by naissa12** [adjust/ios_sdk#593]
How can I delay the start of an app using swift? There’s document to call setStartDelay on adjustConfig in objective c but not in swift. How can I do the same thing in swift?

**Comment by tikidunpon** [comment]
`adjustConfig?.delayStart = 10.0` is should be work.

**Comment by uerceg** [comment]
Exactly as @tikidunpon suggested (thank you). It's also shown in our [Swift example app](https://github.com/adjust/ios_sdk/blob/master/examples/AdjustExample-Swift/AdjustExample-Swift/AppDelegate.swift#L36). In case you still have some questions, feel free to comment / reopen. Cheers.
