### ISSUE TITLE
AdjustSigSdk' for architecture arm64

### ISSUE THREAD

**Issue by razor313** [adjust/ios_sdk#596]
I've added the SDK via SPM and when I'm trying to build my project on a Mac with an M1 CPU, I'll face this error.

`Frameworks/AdjustSigSdk.framework/AdjustSigSdk' for architecture arm64`

If I run Xcode using the Rosseta option the error will be gone, but it's not a real solution, it's a kinda hack. :)

Is there any idea or solution?

**Comment by uerceg** [comment]
Hi @razor313,

Please reach out to your dedicated account manager or in case you don't have one, send an email to support@adjust.com referencing this issue and they'll be able to assist you with it.

Cheers!
