### ISSUE TITLE
Idfa is not sent.

### ISSUE THREAD

**Issue by suatkarakusogludtek** [adjust/ios_sdk#599]
There is a strange situation that we are facing.

Adjust.idfa() method is returning empty even though the permission is granted.
I can check the idfa value through native methods.

_ = ASIdentifierManager.shared().advertisingIdentifier.uuidString

This provides me with idfa value.
Leaving this code block inside the code causes Adjust.idfa() to work.
But deleting it makes it return "" string again.

The behaviour seems strange, and i wonder why there is such a relation. 

--
Adjust version is 4.29.7

**Comment by uerceg** [comment]
Hi @suatkarakusogludtek,

Thank you for reporting. That's strange, indeed. Just for sake of reproduction on our end - are able see this issue (Adjust API not returning IDFA) after you make this call in [requestTrackingAuthorizationWithCompletionHandler's](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorizationwith?language=objc) callback method after getting [ATTrackingManagerAuthorizationStatusAuthorized](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanagerauthorizationstatus/attrackingmanagerauthorizationstatusauthorized?language=objc) state?

**Comment by suatkarakusogludtek** [comment]
Yes this situation occurs after ensuring authorized state. Logging through Adjust.info() is empty unfortunately.
--
iOS version 15.3.1

**Comment by uerceg** [comment]
Gotcha, thanks for confirmation. We'll investigate this on our end and get back to you with the findings.

**Comment by uerceg** [comment]
@suatkarakusogludtek 

We have checked this on our end and we were unable to reproduce this behavior. 🤔 What does `Adjust.idfa()` return if you call it before displaying ATT dialog (it should return zeroed IDFA string)?

**Comment by uerceg** [comment]
In case this is still an issue even with latest SDK version, feel free to comment / reopen. Cheers.
