### ISSUE TITLE
4.30.0=======ADJUtil.m:337======[ADJUtil writeObject:fileName:objectName:syncObject:]===crash

### ISSUE THREAD

**Issue by 405092901** [adjust/ios_sdk#623]
Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x30dd8 _CFArrayReplaceValues + 980
1  CoreFoundation                 0x56ef8 CFArrayAppendValue + 268
2  CoreFoundation                 0x2f7e4 _flattenPlist + 292
3  CoreFoundation                 0x2f9bc _flattenPlist + 764
4  CoreFoundation                 0x2f958 _flattenPlist + 664
5  CoreFoundation                 0x2f9bc _flattenPlist + 764
6  CoreFoundation                 0x2f958 _flattenPlist + 664
7  CoreFoundation                 0x1297c __CFBinaryPlistWriteOrPresize + 260
8  Foundation                     0x59790 -[NSKeyedArchiver finishEncoding] + 548
9  Foundation                     0x9c4ec -[NSKeyedArchiver encodedData] + 76
10 Foundation                     0x32b54 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 124
11 xxxx                           0x2fa3980 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 337 (ADJUtil.m:337)
12 xxxx                           0x2f95090 -[ADJPackageHandler writePackageQueueS:] + 324 (ADJPackageHandler.m:324)
13 xxxx                           0x2f94638 -[ADJPackageHandler addI : package:] + 218 (ADJPackageHandler.m:218)
14 xxxx                           0x2fa6260 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 813 (ADJUtil.m:813)
15 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
16 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
17 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
18 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
19 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
20 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
21 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by Aditi3** [comment]
I believe this is another manifestation of #608.
