### ISSUE TITLE
Same problem

### ISSUE THREAD

**Issue by Shahid-Chawdhary** [adjust/ios_sdk#643]
Someone can help  me?

**Comment by Shahid-Chawdhary** [comment]
Hi Why you close 


Shahid Chawdhary
(Mobile Apps Developer)

**Comment by uerceg** [comment]
Hi @Shahid-Chawdhary,

Your initial post and content showed no context or any useful information at all, thus the closure. Feel free to describe us your problem in detail and we'll check if we can do anything to help you.

Cheers
