### ISSUE TITLE
SKAdNetwork: Error while updating conversion value: Error Domain=SKANErrorDomain Code=10 "(null)"

### ISSUE THREAD

**Issue by eslami-mhmd** [adjust/ios_sdk#649]
I implemented below example based on the below link of adjust documents:
https://help.adjust.com/en/article/skadnetwork-ios-sdk#example-1 

I set the environment to ADJEnvironmentSandbox and log level to ADJLogLevelVerbose.
```
if #available(iOS 16.1, *) {
    Adjust.updatePostbackConversionValue(
        0,
        coarseValue: SKAdNetwork.CoarseConversionValue.low.rawValue,
        lockWindow: false) { _ in
        }
}
```        
But I got below error in console:
SKAdNetwork: Error while updating conversion value: Error Domain=SKANErrorDomain Code=10 "(null)"

If I call `Adjust.updateConversionValue(0)` that is the old way for updating conversion values, the operation is successful.
So It seems there is a problem in the new way of updating conversion values? Should I use the old way at the moment?

**Comment by uerceg** [comment]
Hi @eslami-mhmd,

That is pretty much what executing those `SKAdNetwork` methods will cause if you run them from the app outside of App Store. When you are using above mentioned Adjust SDK API, you're pretty much just using our wrappers which are forwarding your call to actual `StoreKit.framework` API. In the example from above, [this one](https://developer.apple.com/documentation/storekit/skadnetwork/4097267-updatepostbackconversionvalue?language=objc). If you would try to run the `StoreKit.framework` API on your own (not via our wrapper), you'd see that you'd be getting exact same error in completion handler.

From what we saw when it comes to `SKAdNetwork` API, it is not the richest and most informative when it comes to some logs which would explain what happens, but the old API how you call it is pretty much just a parameterless `void` method which has never printed any console logs in the past when it was being invoked. So the fact that you see nothing when you invoke that method doesn't necessarily mean that it works and that the new API doesn't. Maybe they behave under the hood in exact same way, but absence of any return information from Apple's API is just not showing us that. Unfortunately, like said, nothing really useful one can read in the official docs (or assume from some console logs) about this.
