### ISSUE TITLE
Clarification: Set up uninstall and reinstall for ios is available or not

### ISSUE THREAD

**Issue by jesphinpt** [adjust/ios_sdk#657]
I have found the doc for the Set up uninstall and reinstall for Android. But there is no docs for ios. How can I track the install status for my app using the adjust.

https://help.adjust.com/en/article/set-up-uninstall-reinstall-recording-in-the-adjust-sdk

**Comment by uerceg** [comment]
Hi @jesphinpt,

Thanks for reaching out, but for topics like this, it would be the best if you can fire an email to our support team (support@adjust.com) or reach out directly to your dedicated account manager in case you have one to get a proper advice on this particular product.

Cheers.
