### ISSUE TITLE
Memory leaks in trackEvent

### ISSUE THREAD

**Issue by JordyFri** [adjust/ios_sdk#668]
Hello, 

In order to have an application 100% memory leaks free we monitor our application constantly, we notice that our application is having memory issues just after sending a trackEvent with Adjust SDK, 

we are  sending a trackEvent as the documentation says, for example:
![Screenshot 2023-07-19 at 11 46 17](https://github.com/adjust/ios_sdk/assets/127796622/8f724b24-91e5-452e-adfa-7a713a0d3d96)

and we got the memory issue (always when you call the trackEvent, new memory leaks are created):
![Screenshot 2023-07-19 at 11 39 47](https://github.com/adjust/ios_sdk/assets/127796622/d7dcf1fe-e493-4c6f-bf4f-2781ccd50c7e)

Any options o suggestions to solve this memory issue?

**Comment by uerceg** [comment]
Hi @JordyFri,

Thank you for reporting this, we will check this on our end and keep you posted. Just to double check - which iOS SDK version is that you are experiencing this with?

**Comment by JordyFri** [comment]
Hey @uerceg we are using the Adjust SDK v4.33.5

**Comment by uerceg** [comment]
Thank you. We'll investigate this and will ping in here as soon as we have some update.

**Comment by uerceg** [comment]
Hi @JordyFri,

We have just shipped the [v4.33.6](https://github.com/adjust/ios_sdk/releases/tag/v4.33.6) release where we tried to address this issue. If you can give it a shot and let us know if you might still be facing this issue on your end, that would be great.

Looking forward to hearing back from you.

Cheers

**Comment by JordyFri** [comment]
@uerceg Thanks so much for the support, it looks like the issue go away with the last version.

**Comment by uerceg** [comment]
Amazing, thank you very much for the update. I'll close this ticket, but in case you still spot the issue later down the road, feel free to comment / reopen. Cheers!
