### ISSUE TITLE
Change swift package name to something more unique e.g. "Adjust"

### ISSUE THREAD

**Issue by ohserezha** [adjust/ios_sdk#669]
Currently used name "ios_sdk" is too general. I'd suggest changing it to something more specific
The problem is there are a bunch of thoughtlessly named swift packages out there and it makes impossible to use more than one. 
I'm using a package from ASATools also named "ios_sdk" therefore i haven't been able to integrate ASATools and Adjust via SPM at the same time and been forced to use anything except SPM for one of them

**Comment by Aditi3** [comment]
Hi @ohserezha 

Sorry for the delayed reply on this one. Thank you for the feedback. 

We have included your suggestion in our roadmap for the next major iOS SDK release (v5.0.0) and will make every effort to address this improvement at that time.

We cannot modify the existing SDK version since this is a breaking change on our side. 

Thanks again for the feedback!

**Comment by Bathilde** [comment]
Hi!
Is it possible to have an idea of when the new version will be available ? Unfortunately I have the exact same issue.

Thank you.

**Comment by uerceg** [comment]
Hey @Bathilde,

For the time being, closest we can get with some ETAs is that it's definitely going to be in 2024 and that we're aiming to have it done as soon as possible. In terms of work, we are close to have the full feature parity between the v4 and v5 and we are actively looking for clients who would be willing to give beta testing of SDK v5 a shot. In case you might be interested in such thing, feel free to ping us (or your dedicated account manager).

I will close this ticket now, but in case you have any further questions, feel free to comment / reopen.

Cheers.

**Comment by ohserezha** [comment]
new version is out but repository name is still not resolved. As far as i understand, all you need to do is to duplicate the repo into something like `git@github.com:adjust/adjust_ios_sdk.git`

**Comment by uerceg** [comment]
Hi @ohserezha,

Thanks for the follow up and indeed, we still didn't manage to change the repo name. Sorry about that. Not that we haven't thought about it, but we weren't able to fit that into a tight v5 schedule.

You are right, it does look like that changing the repo name to something you suggested (which is probably going to be the exact name we will use in case we proceed with the renaming) would solve this interestingly weird SPM behavior. However, we will most probably need to focus on this task a bit later down the road. We haven't forgotten about this issue, it's still on our radar in lights of this topic, even thought it's closed. For the time being, the suggestion would be to integrate our SDK (or the conflicting one) in some non-SPM way of doing things (CocoaPods, frameworks, Carthage) as an in-between solution.

As soon as we get back to this task on our end, we will definitely post an update in here.

Cheers.

**Comment by ohserezha** [comment]
Thanks for letting know! 
And I totally agree on weird decision to identify packages basing on repo's URL last path component
