### ISSUE TITLE
'ADJPurchase.h' file not found in 4.34.0

### ISSUE THREAD

**Issue by takehilo** [adjust/ios_sdk#673]
After updating to `4.34.0`, I got a compile error with the error `'ADJPurchase.h' file not found`. Is it possible that there is a problem on the library?

**Comment by uerceg** [comment]
@takehilo Thank you for reporting. How are you adding the Adjust SDK to your app (framework, xcframework, Cocoapods / Carthage / something else)?

**Comment by dujavca** [comment]
I have the same error, using Swift Package Manager.

**Comment by takehilo** [comment]
@uerceg 
SPM

**Comment by Stafox** [comment]
Same here

**Comment by ismailislakadesso** [comment]
I have the same error, using Swift Package Manager.

**Comment by uerceg** [comment]
Thanks for reporting guys, we'll ship the fix soon.

**Comment by uerceg** [comment]
Hey guys,

If you can give [v4.34.1](https://github.com/adjust/ios_sdk/releases/tag/v4.34.1) a shot and let us know if it works for you, that'd be great.

Cheers

**Comment by dujavca** [comment]
Problem solved for me.

**Comment by uerceg** [comment]
Thanks for the check and confirmation. In case issue is still there for someone, feel free to comment / reopen.

**Comment by takehilo** [comment]
The problem has been solved. Thanks for fixing it so quickly!
