### ISSUE TITLE
Support App Privacy Manifest

### ISSUE THREAD

**Issue by jolyot** [adjust/ios_sdk#681]
First, thank you for the awesome product.

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs will need to provide a privacy manifest.[^1]

It looks like the Adjust SDK will need to do this because it makes use of UserDefaults APIs, which are now considered "required reason" APIs.[^2]

Is this update on the roadmap for the SDK at all? 

I would like to know when it will be supported, because a reason will be required to update or upload app to App Store Connect by Spring 2024.[^3]

[^1]: https://developer.apple.com/videos/play/wwdc2023/10060/
[^2]: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
[^3]: https://developer.apple.com/news/?id=av1nevon/

**Comment by Aditi3** [comment]
Hi @jolyot 

We are pleased to know that you enjoyed using our product.

Regarding the iOS 17 & Privacy Manifests, We are currently working on updating our SDK to align with the new privacy manifests that come with the iOS 17 release. Our team is making the necessary changes to ensure our SDK meets Apple's requirements and timeline.

[Here's](https://www.adjust.com/blog/privacy-changes-for-app-developers-ios-17/) the link to Adjust's blog post discussing our preparations for changes in iOS 17.

If you have any further questions, feel free to ask.

**Comment by uerceg** [comment]
Closing this one for now, but in case you do have any further questions, feel free to comment / reopen. Cheers.
