### ISSUE TITLE
Link is unattr and Link name is "Unattributed" after calling Adjust.appDidLaunch after ATT Prompt

### ISSUE THREAD

**Issue by siva-cosmicinsights** [adjust/ios_sdk#695]
Hi,

In our app, we were calling Adjust.appDidLaunch method in didFinishLaunchingWithOptions of UIApplicationDelegate and after user sign up or login, we will call ATT(App Tracking Transparency) Prompt to get IDFA.

And app events was tracking fine under Adjust Custom Link.

Now, we have moved ATT Prompt to get IDFA once in applicationDidBecomeActive and once user responds to the prompt, we will call Adjust.appDidLaunch.

After this flow change, in some devices, events are not tracking under proper Custom Link.

In the Test Console, we are getting the following details, with Link as unattr and Link name as Unattributed.

State | Installed
-- | --
Link | unattr
Link name | Unattributed
First link | unattr
First link name | Unattributed
Click time | 0001-01-01T00:00:00Z

In one out of 5 devices, we are getting the issue.

Am i doing anything wrong by waiting for ATT Prompt response to call Adjust.appDidLaunch?

Also, previously, in some devices i used to get Link name as "Organic" like below.

State ® | Installed
-- | --
Link | <SOME_LINK>
Link name | Organic
First link | <SOME_LINK>
First link name | Organic
Click time | 0001-01-01T00:00:00Z

Is Organic same as Unattributed? Am i missing anything?

I would like to know whether it is normal and possibilities for Unattributed and Organic even when user click Custom Link and install app?

Please advise, Thank you.

**Comment by uerceg** [comment]
Hello @siva-cosmicinsights,

And thank you for detailed question. Questions like this (concerning attribution logic which happens on the backend side) are a bit out of scope of us who are replying in here and who are mostly focused on helping with issues related to SDK behavior. I would encourage you to send this question either to your dedicated account manager in case you have one, or to support@adjust.com and link this GitHub issue for the context.

Cheers
