### ISSUE TITLE
4.38.0 Missing nullability type specifier

### ISSUE THREAD

**Issue by JanikReese** [adjust/ios_sdk#703]
iOS: 17.2
Adjust SDK: Upgraded from 4.37.0 to 4.38.0
Xcode: 15.2

We are seeing warning about missing nullability type specifier in `ADJUrlStrategy.h` and `ADJUtil.h`.
Those warnings convert into build errors within the testing target and the module won't build.

<img width="1285" alt="image" src="https://github.com/adjust/ios_sdk/assets/23358483/61a93c95-59bc-4ac7-ba78-8dfc1f04971e">
<img width="1285" alt="image" src="https://github.com/adjust/ios_sdk/assets/23358483/514192c0-48d9-4b48-9794-8f92771efcc1">

**Comment by Aditi3** [comment]
Hi @JanikReese 

I tried to reproduce this for our example application but could not do so on my end. 

Can you check if the `Treat Warnings as Errors` option is set to `Yes` under Build Settings for your application? Setting it to `No` may help.

**Comment by JanikReese** [comment]
Hey @Aditi3 and thanks for your answer.

This is also reproducible within a freshly created demo project.
Regardless if this warning is treated as an error or not we aim for 0 warnings in our project and a fix would be much appreciated.

![image](https://github.com/adjust/ios_sdk/assets/23358483/bf5ed924-316a-4c2f-b792-24044df73d16)

**Comment by Aditi3** [comment]
We have added this to our roadmap and will work on eliminating warnings from our SDK soon.

Thanks again for bringing this to our attention @JanikReese

**Comment by Aditi3** [comment]
Hi @JanikReese,

Our latest release addresses the issue. We would appreciate it if you could give [v4.38.1](https://github.com/adjust/ios_sdk/releases/tag/v4.38.1) a shot and let us know if it works.

Thank you in advance!

**Comment by JanikReese** [comment]
Hi @Aditi3, it seems to be working fine now.
Thanks for you super quick support.
