### ISSUE TITLE
Push latest releases to CocoaPods

### ISSUE THREAD

**Issue by calebd** [adjust/ios_sdk#71]

**Comment by JanGorman** [comment]
Seconded, I'm trying to add this as a dependency to another pod but dependencies can't refer to specific git repositories/tags

`pod trunk push` should only take you a minute

**Comment by nonelse** [comment]
it was published https://github.com/CocoaPods/Specs/tree/master/Specs/Adjust, but it's not yet listed at http://cocoapods.org/?q=adjust

**Comment by wellle** [comment]
Version 4.0.5 is now listed: http://cocoapods.org/?q=adjust
