### ISSUE TITLE
setDeduplicationId method not found

### ISSUE THREAD

**Issue by Vaberer** [adjust/ios_sdk#722]
I'm trying to use setDeduplicationId as per documentation but the iOS sdk does not have such this method. Is the dod out of date?
https://dev.adjust.com/en/sdk/ios/features/events/?version=v5#deduplicate-revenue-events

Thank you

**Comment by uerceg** [comment]
Hey @Vaberer,

What you are looking at are the docs for our still in beta SDK v5. If you scroll up the document, you'll see the version toggle. In case you are using v4, make sure v4 is selected.

Event deduplication in v4 is historically tied to passing `transactionId:` to `ADJEvent`, so the method in v4 you're looking for is `setTransactionId:`. In upcoming v5 we have decoupled the concepts and created hopefully more intuitive method for that purpose.

In case you have any other questions, feel free to ping.

**Comment by Vaberer** [comment]
Thank you for the explanation @uerceg! 
Once v5 is out of beta, will I need to set both setTransactionId and setDeduplicationId?

**Comment by uerceg** [comment]
Nope. If your goal is just to deduplicate event tracking on SDK level, you will then just need to call `setDeduplicationId:` and pass some string which is what you'd like to perform the deduplication based upon.

`setTransactionId:` method is going to remain on `ADJEvent` instance in v5, but its purpose is from v5 onwards going to be for purchase verification only (in case you want us to perform server side receipt verification with Apple).

**Comment by Vaberer** [comment]
Sound good to me. For setDeduplicationId, passing transactionId could work. Am I right?

**Comment by uerceg** [comment]
Absolutely. For historical reasons, we had deduplication in method name tied to transaction ID (which is probably pretty good choice for assigning something unique to the event), but we just wanted to logically decouple the two and how we are just expecting you to pass us a "deduplication ID" which can also continue to be the transaction ID.

While already on the topic, SDK v5 is also going to give you the ability to [set max number of deduplication IDs](https://github.com/adjust/ios_sdk/blob/v5/Adjust/ADJConfig.h#L234) you'd like SDK to have stored for you and dedupe upon. So far, it was always 10 values, but now in case you'd like more, as of v5, you'll have the ability to set that.

**Comment by Vaberer** [comment]
Thank you for the explanation. I'm closing the ticket.
