### ISSUE TITLE
[Adjust]e: Missing signature library, SDK can't be initialised

### ISSUE THREAD

**Issue by kuroky** [adjust/ios_sdk#729]
Adjust 5.0.0 init fail

**Environment**
SDK Version: 5.0.0
iOS Version: iOS 17.2.1
Xcode： 15.2
Installation Method: manual

**SDK Init**
NSString *environment = mDebug ? ADJEnvironmentSandbox : ADJEnvironmentProduction;
ADJConfig *adjustConfig = [[ADJConfig alloc] initWithAppToken:appToken
                                                      environment:environment];
adjustConfig.logLevel = mDebug?ADJLogLevelVerbose:ADJLogLevelInfo;
adjustConfig.delegate = self;
[Adjust initSdk:adjustConfig];
[Adjust addGlobalCallbackParameter:MSDKDeivceInfo.msdkDid forKey:@"msdk_did"];
    
[Adjust adidWithCompletionHandler:^(NSString * _Nullable adid) {
    self.adjustAdid = adid;
}];

**Message**
[Adjust]w: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
[Adjust]d: Delegate implements adjustAttributionChanged:
[Adjust]d: Delegate implements adjustEventTrackingSucceeded:
[Adjust]d: Delegate implements adjustEventTrackingFailed:
[Adjust]d: Delegate implements adjustSessionTrackingSucceeded:
[Adjust]d: Delegate implements adjustSessionTrackingFailed:
[Adjust]e: Missing signature library, SDK can't be initialised
[Adjust]w: Adjust not initialized, but adding global callback parameter saved for launch
[Adjust]e: Please initialize Adjust by calling initSdk: before

**Comment by uerceg** [comment]
Hey @kuroky,

As of v5, iOS SDK is signing all the traffic to provide clients with greater spoofing protection. If you're not using CocoaPods / SPM way of integrating, then make sure to add latest version of [signature plugin](https://github.com/adjust/adjust_signature_sdk/releases) as well next to iOS SDK v5.0.0.

Looking forward to hear from you if that solved the issue.

**Comment by kuroky** [comment]
@uerceg thanks

**Comment by bluce** [comment]
[Adjust]w: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
[Adjust]d: Delegate implements adjustAttributionChanged:
[Adjust]d: Delegate implements adjustEventTrackingSucceeded:
[Adjust]d: Delegate implements adjustEventTrackingFailed:
[Adjust]e: Missing signature library, SDK can't be initialised
[Adjust]w: Adjust not initialized, but read attribution request saved for launch


how to fixed this!

I use cocos2dx_sdk  project v5.0.2

I have added the AdjustSdk.framework and AdjustSigSdk.a into Xcode Project and set the libary search paths!


Help me please!

**Comment by bluce** [comment]
> [Adjust]w: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing [Adjust]d: Delegate implements adjustAttributionChanged: [Adjust]d: Delegate implements adjustEventTrackingSucceeded: [Adjust]d: Delegate implements adjustEventTrackingFailed: [Adjust]e: Missing signature library, SDK can't be initialised [Adjust]w: Adjust not initialized, but read attribution request saved for launch
> 
> how to fixed this!
> 
> I use cocos2dx_sdk project v5.0.2
> 
> I have added the AdjustSdk.framework and AdjustSigSdk.a into Xcode Project and set the libary search paths!
> 
> Help me please!

I has Fixed this!
