### ISSUE TITLE
invalid archive returned

### ISSUE THREAD

**Issue by kasraq** [adjust/ios_sdk#736]
Since yesterday we have the issue when building our app: 

`
invalid archive returned from 'https://github.com/adjust/adjust_signature_sdk/releases/download/v3.20.2/AdjustSigSdk-iOS-tvOS-Dynamic-3.20.2.xcframework.zip' which is required
`

And this is only happening on build device with this architecture:

Xcode 15.4
Build version 15F31d
Apple M2 Pro, 14.2.1 (23C71)

Any idea why?

**Comment by a-ilin** [comment]
Hi @kasraq ,

Could you please specify which package manager gives this error?

In case of `Cocoapods`, could you please execute the following commands in the directory of the project, and repeat the build?

```sh
pod deintegrate
pod repo update
pod update
```

**Comment by kasraq** [comment]
Hi @a-ilin ,
SPM is used. Check both versions 5.0.1 and 5.0.0, have same problem.

**Comment by a-ilin** [comment]
Hi @kasraq ,

Unfortunately, we cannot reproduce the issue. Could you please attempt to reset the SPM cache using the sequence below:
1. Navigate to `~/Library/Caches/org.swift.swiftpm/repositories` and delete the folders and lock files related to the packages:
  a. `adjust_signature_sdk-*`
  b. `ios_sdk-*`
2. Then, in Xcode, run `File -> Packages -> Reset Package Caches`

In case of the issue persists after the cache reset, could you please share the SPM package config (usually `Package.swift`) used in the application?

**Comment by kasraq** [comment]
@a-ilin I actually did remove the cache. I just created a test project for this issue, and no package file is used, but here is how the package added: 

![package](https://github.com/user-attachments/assets/d8ad0571-aab4-430e-925e-d1f6794bdab8)

and you see the package in Derived data is in Zip format which I guess should be wrong.

![DData](https://github.com/user-attachments/assets/bb58ed16-74a6-4c9d-8a39-b6240987e31d)

and here is the error:

![error](https://github.com/user-attachments/assets/ac60dfa4-6f62-4995-b1aa-e5d4e5a31345)

**Comment by a-ilin** [comment]
Hi @kasraq ,

Unfortunately, the issue still cannot be reproduced. I can build a newly created test app successfully adding the package via UI, as shown on the provided screenshot.

On the screenshot displaying the file system, `AdjustSignature` folder contents has a ZIP file, which does not look correct. Moreover, on the screenshot it displays size of 9 bytes, which is certainly wrong. With the properly processed dependency that folder should have `AdjustSigSdk.xcframework` directory.

I can confirm that [AdjustSdk](https://github.com/adjust/ios_sdk/blob/master/Package.swift) references the latest version of [AdjustSignature](https://github.com/adjust/adjust_signature_sdk/blob/v3.20.2/Package.swift), where the correct ZIP file is specified.

However, there is a similar issue reported for SPM itself: https://github.com/swiftlang/swift-package-manager/issues/6635

Perhaps, some of the recommendations in the comments for this ticket may be helpful?

**Comment by kasraq** [comment]
Thanks found the solution. 
Deleting this file ~/Library/Caches/org.swift.swiftpm solved the issue.
