### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by synoptase** [adjust/ios_sdk#75]
`/.../Libs/Adjust/AIActivityHandler.h:34:39: Expected a type`

```
In file included from /.../Libs/Adjust/AIAdditions/UIDevice+AIAdditions.m:9:
In file included from /.../Libs/Adjust/AIAdditions/UIDevice+AIAdditions.h:10:
/.../Libs/Adjust/AIActivityHandler.h:34:39: error: expected a type
- (void)finishedTrackingWithResponse:(AIResponseData *)response deepLink:(NSString *)deepLink;
```

Adding `#import "AIResponseData.h"` in the file fixed the issue.

**Comment by nonelse** [comment]
Thanks, we will include it in the next release.
Since we didn't detect that issue, can you tell how did you find it out?
Thank you

**Comment by synoptase** [comment]
I updated the SDK:
- overwrite old folder with new one
- remove adjust folder from xcode
- add folder back from finder to xcode
- build

Note that i have a `#import "Adjust.h"` and `#import "AdjustDefines.h"` in my `.pch` file.

**Comment by wellle** [comment]
@synoptase: Is there anything left to do here?

**Comment by synoptase** [comment]
Nothing else on my side.
