### ISSUE TITLE
Adjust class is not prefixed

### ISSUE THREAD

**Issue by ajimix** [adjust/ios_sdk#81]
[According to Apple](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html), is recommended to prefix your classes so they don't collide in the future (as objective-c doesn't offer namespacing).

The main class [Adjust](https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.h) is not prefixed...

Thanks

**Comment by wellle** [comment]
Thanks for the heads up, but I don't know if we should take that literally in this case. We already prefix all other classes with `ADJ` to avoid collisions there. I don't think `Adjust` is going to collide anytime soon. And if you prefer, you can read it as `ADJUst` if you like :wink:

But seriously, would you really like to see it being called `ADJAdjust` instead?

**Comment by ajimix** [comment]
Yes I would like to see it named ADJAdjust to follow the Apple guidelines.
