### ISSUE TITLE
Xamarin Binding

### ISSUE THREAD

**Issue by DavePilks** [adjust/ios_sdk#88]
I was just wondering why this wasn't created as a static library. That why it can easily be compiled and reused. 

 I need to create Xamarin bindings for this SDK and I need it as a library to do that. 

Do you perhaps know of any Xamarin bindings or even compiled libraries for this SDK?

**Comment by wellle** [comment]
@DavePilks: You can download `libAdjust.a` from [our releases](https://github.com/adjust/ios_sdk/releases).

**Comment by DavePilks** [comment]
I also need the header files though? Is there a way that I can extract them from the binary?

**Comment by nonelse** [comment]
Hi @DavePilks, I just followed this somewhat outdate, but still relevant [guide](http://kyleroucis.com/Kyle_Roucis/Blog/Entries/2009/10/7_Custom_Embedded_Static_Library_for_iPhone.html) to use our static library: 
1. Add it to the project
2. Drag it to the frameworks folder
3. Make sure that the membership of the lib is with your project
4. Copy full path of the lib from the info
5. Search for "Header Search Path" in the Build Settings
5.1 Make sure that "Always search user header search paths" is YES
5.2 Add full path of the lib into the "User Header Search Paths" with recursive option for the path
6. Search for "Other Linker Flags" in the Build Settings
6.1 Add "-ObjC" flag
7. Rebuild

The header files are under an `Adjust` folder, so importing will be:
`#import "Adjust/Adjust.m"`

Is this enough or were expecting to do it some other way?

**Comment by DavePilks** [comment]
Thanks for the response. I will try this and get back to you.

Sent from Outlook




On Wed, Mar 25, 2015 at 6:37 AM -0700, "Pedro Filipe" <notifications@github.com> wrote:












Hi @DavePilks, I just followed this somewhat outdate, but still relevant guide to use our static library: 

1. Add it to the project

2. Drag it to the frameworks folder

3. Make sure that the membership of the lib is with your project

4. Copy full path of the lib from the info

5. Search for "Header Search Path" in the Build Settings

5.1 Make sure that "Always search user header search paths" is YES

5.2 Add full path of the lib into the "User Header Search Paths" with recursive option for the path

6. Search for "Other Linker Flags" in the Build Settings

6.1 Add "-ObjC" flag

7. Rebuild



The header files are under an Adjust folder, so importing will be:

#import "Adjust/Adjust.m"



Is this enough or were expecting to do it some other way?

**Comment by nonelse** [comment]
We've followed this [guide](http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial), in the new v4.1.1 release with the PR #91. It includes a zipped framework file that contains the architectures: 
 - armv7: Used in the oldest iOS 7-supporting devices
 - armv7s: As used in iPhone 5 and 5C
 - arm64: For the 64-bit ARM processor in iPhone 5S
 - i386: For the 32-bit simulator
 - x86_64: Used in 64-bit simulator

Thanks for the feedback!

**Comment by DavePilks** [comment]
Hi

I have successfully created the Xamarin bindings, thanks for your assistence. I will respond to the email conversation regarding the other concerns.

**Comment by nonelse** [comment]
We also have now official binding for [Xamarin](https://github.com/adjust/xamarin_sdk)
