### ISSUE TITLE
Event sending retry policy

### ISSUE THREAD

**Issue by vsochinsky** [adjust/ios_sdk#95]
Hi guys!
We are having issues with events quantity in Adjust not matching with that on Mixpanel. Adjust dashboard always shows about 10-20% more events than Mixpanel. This is definitely not connected with the timezone.
I assume the answer may possibly lie in the event sending retry policy on bad internet connection or something else connected with offline caching. Can you please check this out, it is very important for us to know that?

**Comment by wellle** [comment]
@vsochinsky: No, we do server side event deduplication. If the SDK sends one event package twice, the second time it will be ignored. To recognize that we compare the event count (it's like a package ID) and the time against the last recorded values.

Go ahead and test it. You should see something like this in the logs:
```
Ignoring duplicate event. Last event count: ... this event count: ... last event time: ... this event time: ...
```

**Comment by vsochinsky** [comment]
@wellle thanks for clarification, we see that in logs as well. Can you suggest any possible issues we can be having on our side?

**Comment by wellle** [comment]
Could it be that Mixpanel is underreporting? Do you use their SDK or our partner integration?

**Comment by vsochinsky** [comment]
We use their sdk. Mixpanel underreporting is also possible, we've asked their support and are waiting.

**Comment by vsochinsky** [comment]
Most probably the problem is caused by the flush behavior in Mixpanel sdk (default flush interval is 60 sec). As I understand Adjust defaults to sending events immediately.

**Comment by wellle** [comment]
Yes that's right.

So I guess we can close this issue?

**Comment by vsochinsky** [comment]
Yes, @wellle thanks for help. I'm closing it.
